### ISSUE TITLE
Moving Page or Folder to different parent doesn't work

### ISSUE THREAD

**Issue by MarcAckermann** [blueriver/MuraCMS#1173]
Selecting a different content parent for a page or folder does not work! 
You can easy reproduce the issue like this:

I have the following site structure

Home/page1
Home/folder1/page2

I need to move the folder 'folder1' and all subpages (in my case that's over 6000pages) to be located under page1:
Home/page1/folder1/page2

So I edit 'folder1' and on the publishing tab I select the new content parent. After clicking "publish" the spinner starts but never ends and nothing happens.

Mura v. 6.1.5635

**Comment by jgibba** [comment]
I see the same issue across multiple site installs of Mura 6.1 and later, even only re-assigning one content node that doesn't have lots of child pages to a new parent folder. Any thoughts on how to to temporarily resolve this issue?

Thanks!

**Comment by mattlevine** [comment]
I can' reproduce this issue in 6.2 , but if updating is not something you want to do the two relevant columns in tcontent are parentid and path Use a sql tool to edit the record in tcontent that has the contentid that you want to move and set the parentid the contentid of the where you want to move it.

They may be many records in tcontent with the same contentid, add an additional filter of active=1 to your query to get the active content version's records.

After updating the db create a temp.cfm in your Mura root with this in it:

````
<cfscript>
application.serviceFactory.getBean("contentUtility"). updateGlobalMaterializedPath('YOURSITEID');
</cfscript>
````

**Comment by jgibba** [comment]
Thanks for reply Matt - I found a similar thread suggesting issue is specific to Firefox which was the same case for me. Worked fine using Chrome or Safari.

https://github.com/blueriver/MuraCMS/issues/1220

Jon

**Comment by mattlevine** [comment]
Thanks for the further information.  It does work in 6.2 in FF as well.  So for anyone that runs into this issue, please update and retest or switch to Chrome.

Thanks,
-Matt
