### ISSUE TITLE
Not able to login into MURA admin in the produciton server

### ISSUE THREAD

**Issue by jvsivaram** [blueriver/MuraCMS#1194]
We have a huge system built on MURA and we have separated staging and production environments. When we installed MURA on production everything worked fine and we could able to login and do the changes related to sites and worked well. Due to security resons, our clients Network team renamed the admin folder few days back. As we did not have many changes in the frontend, we did not use it. 

We want to update some data on some of the pages as such we have renamed back the admin folder again today. We are not able to login into the system. We have only two users to access the production environment. I have tried several things, but could not login. Can anyone help me in this regard ?

My environment details:

Sun Solaries, Coldfusion 10, Oracle 11g and Load balancer for production environment.

**Comment by stevewithington** [comment]
Closing since this issue was resolved 2013-12-26
