### ISSUE TITLE
Quick upload problem with Chrome

### ISSUE THREAD

**Issue by EPSRCwebteam** [blueriver/MuraCMS#1299]
You can add 2-3 files using Quick Upload feature and Chrome seems to cope, however when you go above this only a few go through (ie only 2 reported and 2 actually uploaded) when using Chrome. Firefox seems fine, and can cope with any number (well we tried with drag'n'dropping 6 files and they were ok in FF). Could there be browser compatibility issues here? Anyone else having these kind of problems?

**Comment by JeffreyBouva** [comment]
We have the same issue here! with 3 to 4 images it works great, after that is breaks down and we get a lot of javascript errors. I think it's about the size of the images! Because we can upload 10 small images of a few KB or 3 of a few MB. Can somebody pick this up? This is a real bug!
