### ISSUE TITLE
CKEditor image2 plugin breaks ability to style images

### ISSUE THREAD

**Issue by beamerweb** [blueriver/MuraCMS#1438]
I apologize in advance for the long post ... Here's the general jist:
Since 6.1, i think, we have had the image2 plugin by default in CKEditor. I didn't notice this until now, but that image2 plugin breaks the ability to choose an image and apply classes to it via the Styles dropdown. Even if you select the image with the arrow keys and get the styles to show up, they aren't applied when selected.

Here are the steps to reproduce:
In a default Mura install, edit a page and in the CKE area, place an image. Now try clicking that image and apply a style via the style dropdown. Notice there are no image styles listed, despite their being configured in the styles.js file of the default bootstrap3 theme (and, in fact, default ckeditor styles).

Ok - now for details ... sorry! :)

After a few hours of digging and confirming it wasn't just some style configuration issue, I downloaded the latest CKEditor zip, added the image2 plugin in their demo and was able to reproduce the same issue.

In Mura's widgets/ckeditor/config.js.cfm, I removed the image2 plugin from config.extraPlugins (line 121ish) and then i was able to click the image and set classes via the style menu (just like CKE's demo page). Unfortunately, this isn't a complete solution as the customized toolbars all reference the image2 plugin as well.

Rather than digging into why image2 is broken, I figured it's easier for Mura to just go back to using the default Image system instead. As a temporary fix at the theme-level, I have implemented the following code in my js/editor/config.js.cfm file:

```
CKEDITOR.editorConfig = function( config )
{
	// Strip the image2 plugin to restore ability to set classes on image tags
	config.extraPlugins = config.extraPlugins.replace('image2,', '');
	
	// Replace all instances of the image2 plugin in custom toolbars with the default Image button
	for (var i in config) {
		if (i.match("^toolbar_")) {
			for (var groups in config[i]) {
				for (var items in config[i][groups]) {
					for (var item in config[i][groups][items]) {
						if (config[i][groups][items][item] == "image2") {
							config[i][groups][items][item] = "Image";
						}
					}
				}
			}
		}
	}
};
```

This is definitely NOT optimal - looping through all those arrays is unfortunately the only way I could think of to safely replace all references to the plugin without breaking the upgrade path or other custom toolbars.

**Comment by damienbkx** [comment]
Is there any update on this issue? I cant't get it to work using the laster versions of both Mura core and site. 
According to ck editor doc and demo, it should work... 
http://ckeditor.com/tmp/4.4.0/widget-styles.html

Here is my code in my theme style.js .Did I miss something?

```javascript
/* Widget Styles : http://ckeditor.com/tmp/4.4.0/widget-styles.html */
        { name: 'Rounded Image', type: 'widget', widget: 'image', attributes: { 'class': 'img-rounded' } },
        { name: 'Circled Image', type: 'widget', widget: 'image', attributes: { 'class': 'img-circle' } },
        { name: 'Thumbnail Image', type: 'widget', widget: 'image', attributes: { 'class': 'img-thumbnail' } },
       
```

**Comment by stevewithington** [comment]
@damienbkx this works for me in the latest version of Mura:
https://github.com/blueriver/MuraCMS/blob/030a5a01ca3eae5775674a9c51b0b692183c69d6/default/includes/themes/MuraBootstrap3/js/editor/styles.js#L55-L56

If you don't have anything after the last definition, you may want to try removing the trailing comma ... just a thought.

**Comment by stevewithington** [comment]
@damienbkx well, I thought it _was_ working, but I don't see it in the Styles dropdown.

**Comment by damienbkx** [comment]
Same for me. 
I tried with the MuraBootstrap theme, then switched back to my theme (to rule out a problem specific to my theme) but It did not work in both cases
I'm using mura 6.2.6338 for core and site.

I hope it helps..

**Comment by stevewithington** [comment]
@damienbkx I've just submitted some updates to address this issue (https://github.com/blueriver/MuraCMS/pull/1925). This should end up in the next available update.

**Comment by damienbkx** [comment]
Hi Steve. I just updated Mura Core & Sites and I confirm it now works.  Thanks and keep up the good work!
