### ISSUE TITLE
Italian translation are wrong in admin site

### ISSUE THREAD

**Issue by lucavarini** [blueriver/MuraCMS#1457]
Hello,
the file located in
<wwwroot>\cms\requirements\mura\resourceBundle\resources\it.properties 
is in portugese (or spanish) language.
(mura 6.1.5839)
Is italian language supported in the admin site?

Thank you

Luca

**Comment by stevewithington** [comment]
@lucavarini we rely on the community to help us with translations. If you would like to help, please fee free to visit our project on CrowdIn: https://crowdin.com/project/muracms Thanks!
