### ISSUE TITLE
Categories being set when they should not be. 

### ISSUE THREAD

**Issue by jsieber-aca** [blueriver/MuraCMS#1460]
We've noticed in 6.1 that if we have categories that are limited to specific groups and a member of that group creates content, but is unable to publish the content, the categories that were restricted to the user creating the content are set when a user with permissions publishes the page. 

So, when the user creates the content and saves the content with no categories, any restricted categories that the original user is restricted from are set when an admin user publishes the content.

**Comment by jsieber-aca** [comment]
We are actually still seeing this is version 7.0.6872. If a category is restricted to specific groups and a user edits a page that is not part of the defined groups, when the page is published the groups are being set. In our case, we had seven categories in a folder. One category was restricted to specific groups, but when a user edited content and published the page, all categories in the folder were being set. If we change the category permissions to be " all groups" the issue is resolved.

**Comment by mattlevine** [comment]
So a category is being applied when the user who sees it has it restricted from them?

**Comment by jsieber-aca** [comment]
Hi Matt, 
Yes, categories were being set without the user selecting them in the admin. Once we changed the category permissions to all users, it stopped happening.
-John

**Comment by szabolcsnagy** [comment]
We have the same issue on 7.0.7035. 
In our setup there is an approval chain and a category group that is restricted to the group first in the approval chain.
People with editor permission edited the page and sent it for approval. 
The people first on the approval chain noticed  the incoming 'pending approval' pages has all the categories assigned from their category group.

-Szabolcs

**Comment by mattlevine** [comment]
Can you define what "their category group" means?  Is it their user profile interest groups?  

Also, are category assignments being replaced, or does it only happen when the version going through the chain has no assigned categories?

-Matt

**Comment by jsieber-aca** [comment]
Original poster from years back. For us, it is was just System User groups that wererestricted in the settings of the category. A user might have edit permissions to a specific page that included that category, but if the category restrictions did not include that users System Group all of the categories were being set for that page. We were not using approval chains, so I there may be even more to this than just what we were seeing.

**Comment by szabolcsnagy** [comment]
I created main categories with subcategories. The main categories are the ones I called category group in my post. The main categories are not assignable, but have the permission set to a system group.

The original post had no assigned categories. The pending approval version had all subcategories assigned.

Szabolcs
