### ISSUE TITLE
[Feature Request] Related Content Inbound Links

### ISSUE THREAD

**Issue by Jimcumming** [blueriver/MuraCMS#1473]
It would be great if the related content panel displayed items which link to a content item you are viewing as well as just outgoing links. This would make managing related content loads easier.

**Comment by davidpanzarella** [comment]
@mattlevine did this get added?

**Comment by mattlevine** [comment]
It's not available via the UI, but via the api you can use 

```
related=$.content().getRelatedContentIterator(reverse=true);
```

**Comment by davidpanzarella** [comment]
@mattlevine Right, i was aware of this as well, but the feature I'm referring to is within the admin actually. See what I mean here: https://github.com/blueriver/MuraCMS/issues/1212

Essentially if a user relates 2 objects to one another there should some way to know in the admin. Ideally, you should be able to specify each side as well. An example might be a blog post and person. Related set on blog might be related authors, but on the person it'd be authored content that way there is context to the relationship, and it sets either side correctly.
