### ISSUE TITLE
spam, cfformprotect and cacheItem

### ISSUE THREAD

**Issue by julienprisma** [blueriver/MuraCMS#1478]
Hello,

My website is configured with "Site Caching" to true.

I have a form that uses cfformprotect to check my fields.

In "dsp_form_protect.cfm", we can see "request.cacheItem=false".

But my hidden fields (necessary to validate my form) aren't regenerated when i reload my page.
For example, the hidden field used for "timedFormSubmission" returns the same value after two reloads.

Submitting my form returns a spam detection because of "timedFormSubmission" validation.

I have to add ?nocache=1 (in URL on the page that displays my form) to post correctly my form.

Have you ever had this problem? 
Is this a known issue?

Best regards,

Julien

**Comment by jgibba** [comment]
Hey Julien,

I think there is a Mura forms issue in 6.2 and you have to add [mura]dspInclude('display_objects/dsp_form_protect.cfm')[/mura] before the closing form tag. It might have been fixed in the core but that works for now.

Jon

**Comment by jsieber** [comment]
Also worth moving over to the Google ReCaptcha if you are able. It can be
configured in your site settings on 6.2 and if present, will be used
instead of cfformprotect.
