### ISSUE TITLE
Form validation error

### ISSUE THREAD

**Issue by stevefarwell** [blueriver/MuraCMS#1514]
upgraded to version :6.1.5985 

getting Uncaught TypeError: object is not a function when submitting forms

file: global.min.js

**Comment by mrunyon** [comment]
I realize that this topic is quite old, but this is still an issue (in Chrome only (currently executing on 40.0.2214.111 ). 

Upgrading a site from 6.0.5389 to 6.1.6103 broke form elements on all pages where a form's submit button had a name of "submit". 

Error Message: 
`Uncaught TypeError: undefined is not a function               global.min.js:45`

Given Matt's above comment, I assume that this is the case whenever any form in the site has a button with either an 'id="submit"' or 'name="submit"', as both would trigger this error message. 

Obviously, this is not a critical issue, but given that it's a fairly common convention to assign a submit button in a form either a 'name' or 'id' of 'submit', it seems that the validation function could be tweaked a bit to allow this situation to be handled more elegantly.
