### ISSUE TITLE
Rater css to vague ".five"

### ISSUE THREAD

**Issue by MNU-497** [blueriver/MuraCMS#1528]
/default/includes/display_objects/rater/css/rater.min.css

Be more specific. You can't give a star background to all elements with a class of ".five" or you get this: 
![rater](https://cloud.githubusercontent.com/assets/4730399/3846871/9cd78bfa-1e60-11e4-95c4-a7910c8f1d69.jpg)

Please be more specific with something like:

div.svIndex dd.rating.zero { css background here }

**Comment by stevewithington** [comment]
Closing as resolved awhile back.
