### ISSUE TITLE
[Feature Request] Additional Index for Extended Attributes

### ISSUE THREAD

**Issue by davidpanzarella** [blueriver/MuraCMS#1532]
Hi Guys,

So i have some pretty hefty searches where I need to check several Extended Attributes, which works great using addParam(). But once you get a fair bit of data in there, it starts getting slow... really slow. But I found a really easy fix which was to create an additional 2 column index on BaseID and AttributeID. My query speed went from 2000ms to 200ms. 

I found the tip reading this article on Explain: http://www.experts-exchange.com/Database/MySQL/A_1250-3-Ways-to-Speed-Up-MySQL.html. Seeing that addParam will always use the following syntax when searching extended attributes, I figured it'd be an easy update to do.

		OR tcontent.contentHistID IN(
			SELECT
				tclassextenddata.baseID
			FROM
				tclassextenddata
			INNER JOIN tclassextendattributes ON(
				tclassextenddata.attributeID = tclassextendattributes.attributeID
			)
			WHERE
				tclassextendattributes.siteid = 'walnuts'
			AND tclassextendattributes. NAME = 'recipeIngredients'
			AND attributeValue LIKE '%chicken fish%'

By using BaseID and AttributeID as an single index (in addition to the singular indexes for each), it really made a huge difference when there are like 10 or more of these.

Thoughts?

**Comment by eballisty** [comment]
I've added the ability for dbUtility to handle a multiple column index in this commit (which also includes a newly created index for tclassextenddata): https://github.com/blueriver/MuraCMS/commit/a3ce12f043b83e06a5ba5da7d6f44a9bff2a95e9

**Comment by davidpanzarella** [comment]
Boom! :+1:
