### ISSUE TITLE
[Suggestion] Add content at last position not first 

### ISSUE THREAD

**Issue by adeleusiere** [blueriver/MuraCMS#1578]
Hey guys,

Just a small suggestion: when you add a content, it is added in first position. For me and for my experience now with our customers, it would be more logical and efficient to be added as the last element.

That's all! ;-)
Aurel

**Comment by stevewithington** [comment]
@adeleusiere thanks for the suggestion, and as @nsollecito pointed out, our default behavior is easily modified. Cheers!
