### ISSUE TITLE
Error Exporting: ListGetAt(list:string, position:number, [delimiters:string, [includeEmptyFields:boolean]]):string

### ISSUE THREAD

**Issue by al3x-edge** [blueriver/MuraCMS#1588]
I'm not sure if this is related to #915 or not.  I'm trying to export an older site (but currently at the newest version (6057) and I'm getting the error `listgetat(list:string, position:number, [delimiters:string, [includeEmptyFields:boolean]]):string`.  Any help is appreciated.  Currently running this on a Linux/Railo host.

Stacktrace:
invalid call of the function listGetAt, second Argument (posNumber) is invalid, invalid string list index [2] at railo.runtime.functions.list.ListGetAt.call(ListGetAt.java:27):27 at railo.runtime.functions.list.ListGetAt.call(ListGetAt.java:21):21 at content.file.filemanager_cfc$cf._3(/var/www/clients/client14/web73/web/requirements/mura/content/file/fileManager.cfc:644):644 at content.file.filemanager_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/content/file/fileManager.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:103):103 at railo.runtime.type.UDFImpl._call(UDFImpl.java:371):371 at railo.runtime.type.UDFImpl.call(UDFImpl.java:284):284 at railo.runtime.ComponentImpl._call(ComponentImpl.java:607):607 at railo.runtime.ComponentImpl._call(ComponentImpl.java:490):490 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1781):1781 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:723):723 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1506):1506 at settings.settingsbundle_cfc$cf._1(/var/www/clients/client14/web73/web/requirements/mura/settings/settingsBundle.cfc:183):183 at settings.settingsbundle_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/settings/settingsBundle.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:103):103 at railo.runtime.type.UDFImpl._call(UDFImpl.java:371):371 at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:275):275 at railo.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:784):784 at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:749):749 at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1521):1521 at settings.settingsbundle_cfc$cf._call000089(/var/www/clients/client14/web73/web/requirements/mura/settings/settingsBundle.cfc:1324):1324 at settings.settingsbundle_cfc$cf._1(/var/www/clients/client14/web73/web/requirements/mura/settings/settingsBundle.cfc:1190):1190 at settings.settingsbundle_cfc$cf.udfCall(/var/www/clients/client14/web73/web/requirements/mura/settings/settingsBundle.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:103):103 at railo.runtime.type.UDFImpl._call(UDFImpl.java:371):371 at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:275):275 at railo.runtime.ComponentImpl._call(ComponentImpl.java:608):608 at railo.runtime.ComponentImpl._call(ComponentImpl.java:490):490 at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1800):1800 at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:749):749 at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1521):1521 at admin.core.controllers.csettings_cfc$cf._2(/var/www/clients/client14/web73/web/admin/core/controllers/csettings.cfc:260):260 at admin.core.controllers.csettings_cfc$cf.udfCall(/var/www/clients/client14/web73/web/admin/core/controllers/csettings.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:103):103 at railo.runtime.type.UDFImpl._call(UDFImpl.java:371):371 at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:275):275 at railo.runtime.ComponentImpl._call(ComponentImpl.java:608):608 at railo.runtime.ComponentImpl._call(ComponentImpl.java:490):490 at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1796):1796 at railo.runtime.tag.Invoke.doComponent(Invoke.java:209):209 at railo.runtime.tag.Invoke.doEndTag(Invoke.java:182):182 at admin.framework_cfc$cf._6(/var/www/clients/client14/web73/web/admin/framework.cfc:1308):1308 at admin.framework_cfc$cf.udfCall(/var/www/clients/client14/web73/web/admin/framework.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:103):103 at railo.runtime.type.UDFImpl._call(UDFImpl.java:371):371 at railo.runtime.type.UDFImpl.call(UDFImpl.java:284):284 at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:775):775 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:723):723 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1506):1506 at admin.framework_cfc$cf._2(/var/www/clients/client14/web73/web/admin/framework.cfc:517):517 at admin.framework_cfc$cf.udfCall(/var/www/clients/client14/web73/web/admin/framework.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:103):103 at railo.runtime.type.UDFImpl._call(UDFImpl.java:371):371 at railo.runtime.type.UDFImpl.call(UDFImpl.java:284):284 at railo.runtime.ComponentImpl._call(ComponentImpl.java:607):607 at railo.runtime.ComponentImpl._call(ComponentImpl.java:490):490 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1781):1781 at railo.runtime.listener.ModernAppListener.call(ModernAppListener.java:346):346 at railo.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:181):181 at railo.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:18):18 at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2255):2255 at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2222):2222 at railo.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:315):315 at railo.loader.servlet.CFMLServlet.service(CFMLServlet.java:29):29 at javax.servlet.http.HttpServlet.service(HttpServlet.java:722):722 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305):305 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210):210 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224):224 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169):169 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472):472 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168):168 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98):98 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118):118 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407):407 at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200):200 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579):579 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307):307 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615 at java.lang.Thread.run(Thread.java:745):745

**Comment by davidhartwig** [comment]
I ran into the same issue.  Tried all sort of things.  Then deleted (backed up 1st) the contents of my <side id>/cache folder and it worked like a charm.

**Comment by al3x-edge** [comment]
@davidhartwig Did you post on the wrong issue or deleting /cache didn't really work? Wondering why your comment is gone.

**Comment by davidhartwig** [comment]
I ran across some other ideas and decided to hold off on the post.  In the
end, deleting the cache files did work however.

**Comment by al3x-edge** [comment]
Sadly, deleting the `default/cache` directory didn't fix the issue.

**Comment by al3x-edge** [comment]
Still have a feeling this is like another Mura upgrade (this instance was upgraded in the past) where files not supposed to be in the root (#1812).  I think the instance was borked but not bad enough to quit out.  The client has since kept using it.  At a point where it's going to need to be re-done / just rely on database and filesystem backups.  There are errors reported to Sentry daily about MuraScope issues.

Thanks for the comment though @davidhartwig

**Comment by al3x-edge** [comment]
Ran again just hoping it to work and actually got a out of memory on heap space.  Will screw around with the memory settings and see if I can get it to actually output.

**Comment by davidhartwig** [comment]
Did you try leaving the directory and just deleting the files?

What happened for us was a long while back the database had some corruption issues where files previously uploaded were no longer being found (an error in our Mura site would occur.)  In a nutshell, the hash for the cached file name wasn't matching the database entry.  We pushed through it and just rebuilt/reuploaded the important content....not all of it, just what we needed to get back up quickly.

So what I think was happening on my end was related to this out-of-sync condition where -some- files in the cache weren't matching up with the database.  The create site bundles wasn't able to find matches for -all- the files and went poo-poo.

The solution was to selectively delete files in the cache directory.  -Deleting all the files made it work right off, but this didn't make for much of a site bundle.  So kept adding files back in until it was 'close enough' and didn't break.

**Comment by stevewithington** [comment]
This issue should be resolved now. Also, you should never delete any files located under /{siteid}/cache
Thank you,
Steve

**Comment by al3x-edge** [comment]
@stevewithington  Don't know if it's resolved or not. Can you link to a commit that may have fixed it? Haven't upgraded that instance to the newest version and tried to export recently. I'll try that tonight in the after hours. Currently though, this issue is still open for me.

**Comment by stevewithington** [comment]
@al3x-edge We've made several updates to fix issues with exporting content, and this issue should no longer be present. Please update your core and retest. Thanks.

**Comment by al3x-edge** [comment]
@stevewithington Awesome. I'll update and give it a try. :+1: Thanks for the hard work Blue River =]

**Comment by al3x-edge** [comment]
@stevewithington Updated fine without issue, but it's still just `6.1.6239` and not `6.2.xxxx`.  Wasn't able to export a copy of the site still.  There was no error though, just continual spinning without actually exporting the site.  Should I clear out `version.cfm` in order to get it to 6.2 or try something else?

**Comment by stevewithington** [comment]
Here's a list of steps I've been giving to people to update:

1. Back up both your files _and_ the database (just in case you need to revert)
2. Depending on how old your site is, and if your install has been upgraded from 5.x series, I would manually replace this file (your /index.cfm):
https://github.com/blueriver/MuraCMS/blob/457c905ee45d74a3353a4d473009ff40da813c79/index.cfm
3. I would also manually update the autoUpdater.cfc located here:
https://github.com/blueriver/MuraCMS/blob/457c905ee45d74a3353a4d473009ff40da813c79/requirements/mura/autoUpdater/autoUpdater.cfc
4. Delete the file located under /config/version.cfm
5. Also, you'll probably want to update your sites too, so for each site you'll update, remove this file:
/{SiteID}/version.cfm
6. Reload Mura
7. Log into your CF Administrator ... because you'll want to do something here after the next step.
8. Update your Core

9. From the CF Administrator, clear your Template Cache, Component Cache, and any other cache

10. Reload Mura

11. Mura should now be updated

12. After you've successfully updated Mura, then you should be able to update your site/s too.

**Comment by al3x-edge** [comment]
Thanks @stevewithington -- I'll give it a try.  Appreciate the lightning response.
