### ISSUE TITLE
cfapplication.cfc and mappings.cfc not pupulating on FW/1 Plugin edit

### ISSUE THREAD

**Issue by SethNJohnson** [blueriver/MuraCMS#1589]
None of my mappings or ORMCFCLocation settings are populating to mappings.cfm or cfapplication.cfc after I delete these files when updating my FW1 plugin.  

If I remove the try/catch in the MuraCMS / config / buildPluginCFApplication.cfm ( line100 ) I see that it is throwing an error attempting to parse the config.xml.cfm file because the CFFILE just reads the raw contents of the config file without processing the variables contained therein.

An error occured while Parsing an XML document.
The markup in the document following the root element must be well-formed.

**Comment by stevewithington** [comment]
@SethNJohnson, if you're still having this issue, please feel free to submit a ticket on the MuraFW1 project at https://github.com/stevewithington/MuraFW1/issues. Thanks!
