### ISSUE TITLE
Class Extension Manager Multi-Select Populates with Leading Comma

### ISSUE THREAD

**Issue by bhendel** [blueriver/MuraCMS#1621]
Mura 6.1.6059.

I subclassed a "Page" and added a multi-select with this as the Option List: "Action^Drama^Family"

When I edit pages of this subclass, I see the multi select, and I can select one or more values from this select box, but when I look at the output on the front end, I always see a trailing comma. For instance, if I use the List Display Options on the Folder to drag this "genre" property over, the folder list shows trailing commas: ",Drama"

http://www.windsorfilmfestival.com/films/

Similarly, If I output the genre using $.content('genre'), it still shows a trailing space on the film page, though I am currently removing it myself in code using:

    <cfset genre = $.content('genre')>
    
    <cfif left(genre, 1) EQ ",">
       <cfset genre = mid(genre, 2, len(genre))>
    </cfif>

Why is this trailing comma here?

Thanks!

-Brian

**Comment by djiest** [comment]
I can confirm still issue still exists in version 6.2.6239. The comma is stored in the database (table 'tclassextendeddata', field 'attributeValue'
