### ISSUE TITLE
Ability to load jQuery at end of <body> instead of <head>

### ISSUE THREAD

**Issue by koenhoutman1991** [blueriver/MuraCMS#1623]
Hey blue river guys,

So, I spent the last few days working out why your custom javascript insertions we're error-ing out my pages all the time and turns out that within mura templates, you cannot load your javascript (like jQuery) at the bottom of the body, but only in the head. 

I would like to see this fixed, because for performance and rendering reasons on the front-end, I really like to include all my javascript at the end of the page and I thought that this is becoming a new standard among front-end development.

For the rest, still a fan!

**Comment by PeterBowater** [comment]
I used this to move stuff out the head, when not logged into the administrator, though I guess it won't work if you have log-ons enable for the front end site:

```ColdFusion
<cfif len($.currentUser().getValue('username'))>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="#$.siteConfig('themeAssetPath')#/js/global.min.js"></script>
</cfif>
```

I am sure there used to be isUserLoggedOn(), but don't think that works any more, hence the slight 'hack' of using the username in the above.

I did this for web performance optimisation, with no known side-effects to date, and has been in production for months.

**Comment by muracms** [comment]
@PeterBowater, use `$.currentUser().isLoggedIn()` ... we haven't changed that.

**Comment by PeterBowater** [comment]
Thanks! Will look next time in that repo :) :+1:

**Comment by davidpanzarella** [comment]
The primary issue with putting your code to the footer is that you'll have many features (particularly draggable content objects) that won't work if the JQuery is in the footer. In addition, there are other mura core files, such as Global-min.js, shadowbox files, prettify, etc) that will bomb (depending on your set up).  

At the end of the day, what would be ideal is that we have all of these files compile down to a single js, single css, and load in the footer (in the case of JS obviously).

**Comment by MarcAckermann** [comment]
Using the actual browsers I wonder if it really makes performance differences to place all the js in the page footer or if it's just a 'best practise myth' ?

**Comment by damien-git** [comment]
I'm not sure why this was closed. I tried to defer jQuery a while ago, and it seemed to work fine until someone told me Mura calendars were not working anymore. It would be nice if all Mura scripts could be deferred.

**Comment by PeterBowater** [comment]
That's really good news @mattlevine, always been a bug bear, so good it's fixed now :)

**Comment by damien-git** [comment]
I just tried the calendar with Mura 7.1 and jQuery loading with a script with the defer attribute, and indeed it works ! This will help us optimize our sites.
