### ISSUE TITLE
Form tag removed when page opened in editor

### ISSUE THREAD

**Issue by tkjohns** [blueriver/MuraCMS#1650]
I have three pages that each contain several PayPal buttons.  When they are opened in the editor, all of the form content is stripped out.  

This is one that still contains the form tags: http://www.heritageacademyaz.com/index.cfm/registration-fees/fees-laveen/

The client edited this one today and didn't realize that the forms were missing:  http://www.heritageacademyaz.com/index.cfm/registration-fees/fees-mesa/

**Comment by stevewithington** [comment]
this issue has been fixed.
