### ISSUE TITLE
Approval Chain Exempt setting lost on update for Member groups

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#1684]
Select permission for a content section

Issue 1
If you already have a group assigned as an editor, you cannot tick the checkbox for 'Approval Chain Exempt' unless you select one of the other radio option first and then select 'Editor' again. Doing this enabled the checkbox.

Issue 2
Once you have set the 'Approval Chain Exempt' against one of the groups and saved your settings. If you return to this same page, you'll notice the checkbox under 'Approval Chain Exempt' is not checked and is disabled. If you were to update this page without making any changes, any 'Approval Chain Exempt' setting applied from previous edits will be lost.

Note this only happens to Member Groups section, System Groups section works as expected.

![permissions](https://cloud.githubusercontent.com/assets/7131420/5266631/ddf2b9c8-7a42-11e4-8194-ed2f8a6dcc55.png)

**Comment by Miguel-F** [comment]
What has ever become of this bug?  We are seeing the issue on version 6.2.6458.  It looks like the builtin Admin group is the only one that reflects the setting. We have to select the "editor" radio button in order to enable the checkbox. But even so when we update and go back the check box is not checked and the approval chain is still in affect on the page.

**Comment by mattlevine** [comment]
If you update your core the problem should go away.

**Comment by Miguel-F** [comment]
Thanks for the quick reply Matt.  Did you change something just now or was this fixed previously?  _This bug is still open._

**Comment by mattlevine** [comment]
Did you update your core?  I really thought that the checkbox issue was fixed?

Also, the approval chain should not need to be set on each content node.  It should be inherited like you described.  However, when going to the permissions view for a node placed under a parent that has a approval chain assigned to it, you will not see that assignment.  You will only see what has be explicitly assigned to that sub node. Hopefully that makes sense.  I realize that this may be confusing and we hope to improve it in the future.

-Matt

**Comment by Miguel-F** [comment]
We updated the core on our dev server and it did fix the checkbox issue.  Thanks for that.  What you described for the inheritance make sense but it is not what I was trying to describe. I was trying to get it to inherit from a parent page of the approval chain, not a child page of it.  I was hoping that we could check the approval exemption on the home page for example (but that page does not have the approval chain). Then on a child page that does have the approval chain assigned not need to check the exemption box again. Does that make sense? Then we would only need to exempt our admin group in one place. It does not seem to work that way though. It only works if we check the exemption box on the same page that has the approval chain defined.
