### ISSUE TITLE
Admin's 'Current Site' button produces bad link for https sites (with fix)

### ISSUE THREAD

**Issue by szabolcsnagy** [blueriver/MuraCMS#1720]
My site is now switched over to SSL. It is done by  this line in the onRenderStart ```<cfset arguments.$.event('forceSSL',1)>``` (an advice I got on the mailing list. )

It works however on the  admin page the _Current Site_ button has a bad link as it uses http on port 443.
I found that the http protocol is hard coded into  **/admin/common/layouts/includes/header.cfm (line 323)**

I fixed the problem in the following way.
1. added a new variable to the **/requirements/mura/configBean.cfc**
```<cfset variables.instance.secureServerPort="443"/>```
This is just so I don't have to hard code the port number and it would allow people to use SSL on different port.
2. replaced the hardcoded 'http' string in the above file @ line 323 with this.
```<cfif application.configBean.getSecureServerPort() is listLast(application.configBean.getServerPort(),':') > https<cfelse> http</cfif>```

I am wondering if this could be worked into the mura codebase.
Is it better if I send a pull request?

Szabolcs

**Comment by stevewithington** [comment]
There will be a setting in our next version (6.2) that allows for this functionality in the Site Settings. We don't have a release date yet, but hope to have it available soon. Thanks.

**Comment by szabolcsnagy** [comment]
Great, thank you. 
if the new setting could fix this issue for links in the RSS feeds that would be great.

Thanks again,
Szabolcs
