### ISSUE TITLE
Local Index Sections Sorting

### ISSUE THREAD

**Issue by Reyjay** [blueriver/MuraCMS#1734]
(Feature Request)

Hi,

I have been working with many clients that need to create featured feeds based on content from multiple folders.  Right now I am creating an attribute that they can flag on each content page to mark that content as featured.  The issue I was having with this was that is hard to maintain due to all the post being scattered in different folders, and sorting them in a specific order is very complicated if they need to be manual ordered.

Right now you can add specific posts to a local index and see them in a list (see attached image), but you can not sort the order(manually) within that local index.  My feature request would be that the items you choose in the local index have a way to be dragged and dropped, and that order can then be used to display them on the front end.

Thank you so much for your time, you guys make an amazing product!  Let me know if you need any further explanation or examples.

Thanks,
Reyjay
![mura_cms_content_collections_feature-request](https://cloud.githubusercontent.com/assets/1654250/5667224/ebcc6f68-971a-11e4-9a30-2835dbe9fd31.jpg)

**Comment by nsollecito** [comment]
Hey Reyjay, 

Take a look at the [Related Content](http://docs.getmura.com/v6/content-managers/edit-content/related-content-tab/) to see if it might suit your needs. We worked with Blue River to build out this functionality of hand-picked content that can be manually sorted.

You could create a custom Related Content set and then just use that on the content node whenever you need a custom handpicked list of content.

**Comment by Reyjay** [comment]
Your the man Nick!  This is great for page by page usage, and for my current use.    

It would still be amazing to have the ability to drag and drop in content feeds just so everything is in one place and more easily reused.

Thanks,
Reyjay

**Comment by nsollecito** [comment]
No prob, glad to help. 

RE: page by page.. Keep in mind you can always create hidden/utility pages within your Site Tree and load them directly from the API to provide common functionality in your templates... we do that quite a bit.
