### ISSUE TITLE
Unable to update to 5.5 - Object Instantiation Exception.

### ISSUE THREAD

**Issue by alancontino** [blueriver/MuraCMS#1756]
I saw that this issue was posted in a previous thread and the problem was considered "fixed" - however, I'm running into the same error now.    Still looking for instructions on manually updating to version 5.5 or to version 6.0.

Core ver 5.4.4148
Site ver 5.4.4150
MS SQL w/ Cold Fusion 8

Here is the error:

An Error has occured.

Object Instantiation Exception. 

array
1	
struct
COLUMN	0
ID	CF_JAVAPROXY
LINE	492
RAW_TRACE	at cfZip2ecfc2008541841$funcLIST.runFunction(E:\Inetpub\wwwroot\deliriumnetworks.com\requirements\mura\Zip.cfc:492)
TEMPLATE	E:\Inetpub\wwwroot\deliriumnetworks.com\requirements\mura\Zip.cfc
TYPE	CFML
2	
struct
COLUMN	0
ID	CF_TEMPLATEPROXY
LINE	114
RAW_TRACE	at cfautoUpdater2ecfc184453401$funcUPDATE.runFunction(E:\Inetpub\wwwroot\deliriumnetworks.com\requirements\mura\autoUpdater\autoUpdater.cfc:114)
TEMPLATE	E:\Inetpub\wwwroot\deliriumnetworks.com\requirements\mura\autoUpdater\autoUpdater.cfc
TYPE	CFML
3	
struct
COLUMN	0
ID	CF_TEMPLATEPROXY
LINE	253
RAW_TRACE	at cfdsp_list2ecfm138068997.runPage(E:\Inetpub\wwwroot\deliriumnetworks.com\admin\view\vSettings\dsp_list.cfm:253)
TEMPLATE	E:\Inetpub\wwwroot\deliriumnetworks.com\admin\view\vSettings\dsp_list.cfm
TYPE	CFML
4	
struct
COLUMN	0
ID	CFINCLUDE
LINE	275
RAW_TRACE	at cfApplication2ecfc891623114$funcDOFBINCLUDE.runFunction(E:\Inetpub\wwwroot\deliriumnetworks.com\admin\Application.cfc:275)
TEMPLATE	E:\Inetpub\wwwroot\deliriumnetworks.com\admin\Application.cfc
TYPE	CFML
5	
struct
COLUMN	0
ID	CF_UDFMETHOD
LINE	1
RAW_TRACE	at cflist2ecfm296995247.runPage(E:\Inetpub\wwwroot\deliriumnetworks.com\admin\fw1\views\csettings\list.cfm:1)
TEMPLATE	E:\Inetpub\wwwroot\deliriumnetworks.com\admin\fw1\views\csettings\list.cfm
TYPE	CFML
6	
struct
COLUMN	0
ID	CFINCLUDE
LINE	915
RAW_TRACE	at cfframework2ecfc650456792$funcVIEW.runFunction(E:\Inetpub\wwwroot\deliriumnetworks.com\admin\framework.cfc:915)
TEMPLATE	E:\Inetpub\wwwroot\deliriumnetworks.com\admin\framework.cfc
TYPE	CFML
7	
struct
COLUMN	0
ID	CF_UDFMETHOD
LINE	248
RAW_TRACE	at cfframework2ecfc650456792$funcONREQUEST.runFunction(E:\Inetpub\wwwroot\deliriumnetworks.com\admin\framework.cfc:248)
TEMPLATE	E:\Inetpub\wwwroot\deliriumnetworks.com\admin\framework.cfc
TYPE	CFML

**Comment by stevewithington** [comment]
You need to be running on at least ColdFusion 9.0.1 for Mura CMS. It won't
run on ColdFusion 8.

**Comment by MarcAckermann** [comment]
... or simply change to Railo 4.2.
