### ISSUE TITLE
Can't add link to centered image in wysiwyg

### ISSUE THREAD

**Issue by Reyjay** [blueriver/MuraCMS#1757]
You are not able to add a link to a centered image in the wysiwyg.

I searched though current issue and found these 2 for IE.
https://github.com/blueriver/MuraCMS/issues/887
https://github.com/blueriver/MuraCMS/issues/1227

Chrome: Version 40.0.2214.91
Firefox: Version 35.0
Mura: Version  6.1.5937

![1](https://cloud.githubusercontent.com/assets/1654250/5881442/b1664100-a2f5-11e4-89b4-c74a15d68ca8.jpg)
![2](https://cloud.githubusercontent.com/assets/1654250/5881441/b1658efe-a2f5-11e4-8c56-be38c72c1f16.jpg)
![3](https://cloud.githubusercontent.com/assets/1654250/5881440/b1653d82-a2f5-11e4-87ca-7e3ad5f71b06.jpg)

**Comment by stevewithington** [comment]
issue fixed in 6.2
