### ISSUE TITLE
6.2 - cannot delete images in ck finder

### ISSUE THREAD

**Issue by ronnieduke** [blueriver/MuraCMS#1769]
If you right-click and choose "delete" on an image in CK finder, it gives the following error message:

"It was not possible to complete the request due to file system permission restrictions."

Version 6.2.6141

**Comment by stevewithington** [comment]
@ronnieduke it appears this only happens when editing content via the front-end, correct?

**Comment by ronnieduke** [comment]
@stevewithington - No, this was via the admin


--------------------------------------

Ronnie Duke

Blue River Interactive Group

Mura CMS

www.blueriver.com

www.getmura.com

--------------------------------------

**Comment by stevewithington** [comment]
@ronnieduke did you try recently? what's your setup? OS? CF? Railo? Versions? are you getting any errors in the console?
