### ISSUE TITLE
Related Content Migration

### ISSUE THREAD

**Issue by bradgus** [blueriver/MuraCMS#1770]
We found an issue with one of our older projects that has been upgraded a number of times. 

Site was originally built and launched running on version 5.6. Site is now running on the most current version. They have a significant number of pages on the site with related content. They noticed this week that for older pages with older related content (probably posted back when they were running on 5.6), the related content applied to that page does not show in the Mura admin. Note - still works on the front end when using "RelatedContentQuery".

In order to fix and allow any related content to show post-upgrade, the "relatedContentSetID" in "tcontentrelated" table, needs to be updated from "NULL" to "00000000000000000000000000000000000" to any related content assigned historically is added to the default set on the page. 

Let me know if you have any questions on the issue.

Thanks!

**Comment by stevewithington** [comment]
patch submitted.

**Comment by bradgus** [comment]
Great. Thanks Steve!
