### ISSUE TITLE
CKEditor created with CKEDITOR.replace() not using styles or config

### ISSUE THREAD

**Issue by mlgoon** [blueriver/MuraCMS#1775]
When I dynamically create an instance of CKEditor using CKEDITOR.replace(), the instance that's created doesn't use the toolbar config or the editor.css files that would normally be used. Is there an additional configuration that I need to include, or is this a bug?

**Comment by stevewithington** [comment]
@mlgoon, I'm not entirely sure what you're end goal is, but there's a couple different ways to customize the ckeditor instances (that's plural by the way) within Mura.

1. If you simply want to redefine one or more toolbars, you could easily modify the theme's CKEditor config file: https://github.com/blueriver/MuraCMS/blob/c917a06e1687668d9d4dcc0e22d1096307af3c1a/default/includes/themes/MuraBootstrap3/js/editor/config.js.cfm.txt#L20-L24

2. If you're trying to create your own custom instance of CKEditor, then you'll want to follow an example I created at https://gist.github.com/stevewithington/7451982

Thanks,
Steve

**Comment by mlgoon** [comment]
@stevewithington 

I may not have explained it well enough. I have one form with multiple textareas that are all CKEditors. Instead of loading them all when the form loads, I display them as divs and then dynamically convert them to CKEditor instances using CKEDITOR.replace() when the user clicks on the div. The form loads faster and looks cleaner.

When the instance of CKEditor is created that way instead of right away when the page loads, it appears that the instance of CKEditor is not using the same config file as when CKEditor is initialized at the beginning of the page. This is evident in the toolbars that are shown. So, I work around it by including the config in the replace() call.
