### ISSUE TITLE
6.2 Preview (addToHTMLHeadQueue & addToHTMLFootQueue not functioning)

### ISSUE THREAD

**Issue by StevePrescott** [blueriver/MuraCMS#1776]
After updating Mura Core to version 6.2.6149 the contentRenderer methods "addToHTMLHeadQueue" and "addToHTMLFootQueue" are not functioning.
There are no noticeable errors however the intended files are not included/added to either head or foot queues.

**Comment by andrew-dixon** [comment]
We are experiencing this issue as well.

**Comment by martinschaible** [comment]
Strange, i updated several sites with the now final edition 6.2 and these methods are a working.

**Comment by stevewithington** [comment]
Sure would be nIce to know your environment details so we can attempt to reproduce. Thanks!

**Comment by andrew-dixon** [comment]
@stevewithington - What sort of the details are you looking for specifically?

**Comment by stevewithington** [comment]
OS, CFML engine, versions, etc. .. hover over the version info in the admin and copy the details here. Thanks!

**Comment by andrew-dixon** [comment]
@stevewithington - As requested:

App Server Railo (4.2.1.000)
DB Server MySQL (5.6.19-log)
Java Version 1.7.0_75
OS Version Linux (3.10.48-55.140.amzn1.x86_64)

**Comment by StevePrescott** [comment]
Sorry about that...

![image](https://cloud.githubusercontent.com/assets/4126343/6379169/5369fb82-bcfe-11e4-8cd7-e335e9ebbcaf.png)

**Comment by mattlevine** [comment]
Do you guys have any plugins or functions that override addToHTMLHeadQueue or renderHTMLHeadQueue.   Mura no longer uses a comma separated list for the queues.  It now stores the queues as arrays.  For example do you have any plugin that try gzip all your html head or foot?

Also renderHTMLHeadQueue does not exists anymore.  There is now a function called renderHTMLQueue that is used for both the head and foot queues.

**Comment by stevewithington** [comment]
@StevePrescott & @andrew-dixon, 

As Matt eluded to, I suspect you both have the GZip Compress Plugin installed. Correct?

If so, please disable it and contact the plugin author/creator to make it compatible with Mura 6.2. Matt explains the changes in his comment.

If you do not have the plugin installed, please let us know.

Thanks,
Steve

**Comment by andrew-dixon** [comment]
@mattlevine & @stevewithington - Nope we don't have that plugin installed. The only plugin we do have installed is one we have written ourselves. I will need to check with the dev in the morning and see if they are using the renderHTMLHeadQueue function or not.

**Comment by stevewithington** [comment]
@andrew-dixon, ok, please let us know what you find out because I'm unable to reproduce with similar environment conditions. Thanks!

**Comment by StevePrescott** [comment]
@mattlevine & @stevewithington - I have the Slatwall plugin installed but do not know if they have overridden either

**Comment by mattlevine** [comment]
Does your core contentRenderer have this method:

https://github.com/blueriver/MuraCMS/blob/master/requirements/mura/content/contentRenderer.cfc#L3039-L3051

**Comment by mattlevine** [comment]
Also keep in mind that renderer functionality can be overridden in both your theme and site contentRenderer.cfc files.

**Comment by StevePrescott** [comment]
@mattlevine - mura core does have that method. Neither my site or theme contentRenderer (s) has that method overridden. BTW the theme being used is "Down to Business" by blueriver.

**Comment by StevePrescott** [comment]
One area I noticed the issue initially was with regard to the Down To Business Theme. The contentRender for the theme has a dspBxSlider function which is using both methods (addToHTMLHeadQueue and addToHTMLFootQueue). They are used to "slide" testimonials on the page. After noticing they were no longer functioning I tracked that piece of code down and temporarily replace it with "cfhtmlhead" .

**Comment by StevePrescott** [comment]
Completed a search of the Slatwall code and did not find any references to addToHTMLHeadQueue , addToHTMLFootQueue, renderHTMLHeadQueue  or renderHTMLQueue. I won't get to it today but I can see if I can recreate this with a fresh install and site without any plugins.

**Comment by mattlevine** [comment]
Please update and retest.

**Comment by andrew-dixon** [comment]
@mattlevine & @stevewithington - Yes this fixed it, thanks so much.

**Comment by stevewithington** [comment]
@andrew-dixon thanks for letting us know!

**Comment by StevePrescott** [comment]
@mattlevine <https://github.com/mattlevine> & @stevewithington
<https://github.com/stevewithington> - Same here. Thank You!
