### ISSUE TITLE
Components Not Displaying Content

### ISSUE THREAD

**Issue by dnordyke** [blueriver/MuraCMS#1780]
I'm using MuraCloud with with a deployed a site bundle.  I noticed that any newly added associated images were not being displayed.  When I viewed the src of the image the path was something like this:
```
<img src="/breakthroughsinc2/cache/file//opt/apache-tomcat-7.0.27/webapps/ROOT/breakthroughsinc2/cache/file/41EEC671-3BC5-445C-A8E16DD1F1DAD24A_small.jpg">

```

So I updated the site files and the core files and the images do not show AND now none of the components/content collections for that site will display anywhere.  The html output for those components looks like this:
```
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
    <title>Untitled Document</title>
```

Please advise.

**Comment by ronnieduke** [comment]
@dnordyke - Can you post this in the Mura Google group as well? Curious to see if anyone else has run into this.

**Comment by dnordyke** [comment]
So I took a site bundle of the current site and deployed it on a Windows/CF10 environment.  Got the same result  with the components not displaying and the image referencing the server root.

This is only happening on newly uploaded images.
