### ISSUE TITLE
Advertising Module

### ISSUE THREAD

**Issue by manking109** [blueriver/MuraCMS#1783]
So I uploaded 6.2 Preview.

No advertising Module, No warning that it was being shelved. 

No backward compatibility? 

We have sites that make their living from advertising revenue from the advertising module.  Now these sites will be left at 6.1.61##.

It is one of the only ways that sites can use local advertising to generate revenue.

**Comment by stevewithington** [comment]
@manking109,

Actually, this has been in the works and discussed within the community for quite some time.

Anyway, if you have an instance of Mura that is using the ad manager you can edit your `config/settings.ini.cfm` and set `admanager=true` and reload.  After that you can turn it on in your **Site Settings > Modules** tab.  However, I would start planning to migrate to something else.

Also, we have no immediate plans of removing any other global modules at the moment. 
Sorry for the inconvenience.

**Comment by manking109** [comment]
Thank you for the great response.  We have begun to look at some of the alternatives..
