### ISSUE TITLE
Update to 6.2 final not working / version.cfm file

### ISSUE THREAD

**Issue by MarcAckermann** [blueriver/MuraCMS#1786]
Now that 6.2 final is out I tried to update mura on a server. Result: the update is still not working without deleting the version.cfm file.

**Comment by martinschaible** [comment]
I usually restart Mura after the deletion of this file. I think this is needed that Mura can get it's version again

**Comment by MarcAckermann** [comment]
I also had to delete /default/version.cfm cause the site version was shown as 6.2.6164 but the site files haven't been updated to the current version. So after deleting version.cfm and hitting "Update Site" again the new files were pulled.

**Comment by sihu** [comment]
for some older versions, the auto-update did not work too, i had to do some manual work:
* requirements/mura/autoUpdater/autoUpdater.cfc (copy newest manually)
* requirements/mura/Zip.cfc
* requirements/mura/fileWriter.cfc

after that i could update. that might could work also for you. but i suggest you to backup everything before.

**Comment by stevewithington** [comment]
We're aware of this issue for some people, although it doesn't impact everyone and depends on which version you were on before auto-updating. Once a successful update has occurred, hopefully this shouldn't be an issue again. 

I'll also add that if you've been updating from 5.x, you may also have to manually replace `muraroot/index.cfm` as well.

Thank you all for your feedback!
