### ISSUE TITLE
Mura upgrade error

### ISSUE THREAD

**Issue by jgibba** [blueriver/MuraCMS#1787]
Upgrading Mura core from version 6.0 to the latest version threw the attached error message in /config/applicationSettings.cfm:

Element ${iif(listLen(cgi.server_name,".") EQ 1,de("local"),iif(findNoCase(".<site_name>.com",cgi.server_name) AND ListFirst(cgi.server_name,".") NEQ "www",de(de("development")),de(de("production"))))} is undefined in a CFML structure referenced as part of an expression.

I am no longer able to access the Mura admin even after trying to reload the app in the url. Please advise. Thank you!

![mura_upgrade_error](https://cloud.githubusercontent.com/assets/5321848/6402408/66c20bf2-bdd5-11e4-8d0d-182cb4f9ce45.png)

**Comment by stevewithington** [comment]
@jgibba i'm not able to reproduce this error. However, I would recommend doing a few things:

1. Remove the file located under `/config/version.cfm`
2. Log into your CF Administrator, and clear your Component Cache, Template Cache, Object Cache, etc.

Then attempt to access your admin area again and perform the udpate once more.

**Comment by bradgus** [comment]
Steve - 

We're seeing this on another site upgrade. Same error message as above - only we're upgrading from 6.1.57.

We'll post if we come up with a resolution in the meantime.

Brad

**Comment by stevewithington** [comment]
@bradgus, did you try my recommended steps?

**Comment by bradgus** [comment]
Thanks Steve. We did through the steps. Getting the same result, but we're also seeing this message in the admin when running the core update:

![update-error](https://cloud.githubusercontent.com/assets/755533/6587229/02a3124c-c758-11e4-8220-21c6f05bcd4c.jpg)

**Comment by stevewithington** [comment]
@bradgus, I've not seen this error before. Could you please try to manually update your autoUpdater.cfc to this: https://github.com/blueriver/MuraCMS/blob/0dcd864baad77992aeb7fb4a657c97fc595763f5/requirements/mura/autoUpdater/autoUpdater.cfc

Then try again and let us know how it goes?

**Comment by bradgus** [comment]
Thanks Steve. Manually updated the autoupdate file, removed the version.cfm file and and ran the core update again. Getting the same error message on the Global Settings page.

**Comment by stevewithington** [comment]
@bradgus after replacing the autoUpdater.cfc file, did you reload Mura before trying to update again?

Otherwise, I would probably just try to do a dump/abort of the `rs` created on line 163 to see if there's anything unusual in there. I've just never run into your issue ... maybe even dump the `variables.fileDelim` to make sure it's not an empty string? Without having access to your specific install, I'm throwing darts in the dark here.
