### ISSUE TITLE
The property name [fieldname] is not valid

### ISSUE THREAD

**Issue by pdayquotient** [blueriver/MuraCMS#1792]
I am experiencing an issue when setting a field as not required in a form.

Version: 6.1.6102
Site Version: 6.1.6103
CF 10
Windows Server 2008

**My form field configuration:**

![screen shot 2015-03-02 at 10 10 17 am](https://cloud.githubusercontent.com/assets/11273264/6443280/d1f952ae-c0c3-11e4-8212-33022c2b2860.png)

![screen shot 2015-03-02 at 10 22 34 am](https://cloud.githubusercontent.com/assets/11273264/6443535/82b099e4-c0c5-11e4-99cb-8d26406293c4.png)

![screen shot 2015-03-02 at 10 21 28 am](https://cloud.githubusercontent.com/assets/11273264/6443508/556a68b6-c0c5-11e4-938e-3a30d4ba47a9.png)

**The form:**

![screen shot 2015-03-02 at 10 11 31 am](https://cloud.githubusercontent.com/assets/11273264/6443298/edeaa6f2-c0c3-11e4-9b15-f395053c82d6.png)

**The outcome:**

![screen shot 2015-03-02 at 10 12 11 am](https://cloud.githubusercontent.com/assets/11273264/6443305/0558d958-c0c4-11e4-93f7-61c55edf388e.png)

Now, if i place a value in the email field, it will work. But if I submit blank, I always get "The property name 'email' is not valid."

**Comment by al3x-edge** [comment]
Re-opened issues / example of #1596.

**Comment by stevewithington** [comment]
Thanks for the screenshots. We've been able to replicate and should have a fix up shortly. Thanks!

**Comment by al3x-edge** [comment]
:+1:

**Comment by stevewithington** [comment]
This should be fixed now. Thanks!
