### ISSUE TITLE
Instabile after Update

### ISSUE THREAD

**Issue by sihu** [blueriver/MuraCMS#1794]
Not for the first time, i updated mura and got a version, that is not under your latest releases (newest is actually 6.2.6161 but i got 6.2.6181. is that an issue, that it is possible to update to the latest commit, instead of the latest tag? i think, some cms have the possibility to select whether to update to nightly builds or only to stabile tags. that would be a great improvement.

**Comment by codeartch** [comment]
can confirm this issue.

**Comment by Walkeezy** [comment]
Same here.

**Comment by stevewithington** [comment]
We don't create a "tag" for every update. If you use the auto-update feature, it updates to the latest commit in our Master branch.

Cheers,
Steve
