### ISSUE TITLE
Error in Notifications functionality on publish.

### ISSUE THREAD

**Issue by christineballisty** [blueriver/MuraCMS#1795]
FYI, I received this message from a Professional Services/Mura client today and @ronnieduke has validated.

*We were getting a 500 error when trying to send notifications from the Publishing tab in Site Manager on all pages after updating to version 6.2. The error was tracked to line 530 in /requirements/mura/content/contentUtility.cfc and stated “SITEID undefined in ARGUMENTS”. The argument list for the sendNotices function was indeed missing the siteid argument, so <cfargument name="siteid" required=”true” /> was added to the function arguments, the application was reloaded, and the issue was resolved. If it’s not already in there, you might want to have somebody add that and commit it to the repository for the next set of core updates.*

**Comment by stevewithington** [comment]
@christineballisty i just submitted a patch to fix (https://github.com/blueriver/MuraCMS/pull/1806). cheers!
