### ISSUE TITLE
`mura-async-object` implementation issues

### ISSUE THREAD

**Issue by al3x-edge** [blueriver/MuraCMS#1797]
Creating issue due to issues after recent upgrade. Usually I check all files that have been changed in the upgrade in absence of a change log. Mura returned that no files have been changed and I just ignored it. Now this morning we noticed that some of our acceptance tests were failing.  Some of our javascript has broken due to the implementation of ajax with the form-builder.

@mattlevine / @stevewithington Can you update on what this effects? Would we be opposed to a javascript event being fired after each process ([global.js#L1112](https://github.com/blueriver/MuraCMS/blob/c8574f2ac42b3cbaaa2471dad63bf8c137ebfef1/default/js/global.js#L1112))?

**Comment by mattlevine** [comment]
In 6.2 forms build using the form builder, login and edit profile forms are loaded asynchronously. This can be stopped by setting this.asyncObjects=false in your theme contentRenderer.cfc.  Announcing an jquery event seems like a very good idea. What do you think that event should be called?

**Comment by al3x-edge** [comment]
I'm not sure.  Maybe just `asyncObjectRendered`. Event handlers could then be bound at the element or higher looking at `event.target` to determine which one needs to be handled.  Probably the easiest that could be done for now.  An all encompassing event would require promises to be used/resolved.

**Comment by mattlevine** [comment]
Please consider this alpha, but If you update your site files you can now do this:

The first example is registering an object based event handler with function that represent event to listen for.

```
<script>               
       mura.addEventHandler(
			{
				asyncObjectRendered:function(){
					alert($(this).html());
				}
			}
		);
</script
```

Or this:

You can simply register a single anonymous function to handle a specific event
```
<script>
		mura.addEventHandler('asyncObjectRendered',
			function(){
				alert($(this).html());
			}
		);
</script>
```

This opens it up for in the future have events that target on specific form Type/Subtype combinations perhaps 'asyncFormWidgetRenderered' of something like that.   We can also add a event object that can contain more mura specific details about what kind of object is being rendered or action is happening.

 I'm truly sorry for any head that the update caused.

**Comment by al3x-edge** [comment]
@mattlevine Looks good to me. Thanks for adding this in. Definitely can see potential to where it is going. All in all, we could probably leverage the new JSON api more and then remove the requirement to have forms in the DOM and moving them.  Didn't realize it existed actually until hunting down async objects.

No need to take fault. Mura for us is a bit of an enigma.  One of the few things we aren't able to explicitly version control and lock to a number.  I totally understand why that is though.  Just something we need to get better handling the risk of.
