### ISSUE TITLE
Gallery: Quick Upload Error when Blank Title

### ISSUE THREAD

**Issue by cameroncf** [blueriver/MuraCMS#1798]
Steps to reproduce:

1) Create Gallery
2) Use Quick Upload to add image to Gallery
3) Delete the content of the Title field (leave it blank)
4) Click "Start Upload"

At this point the edit form(s) go away and are replaced by blank white boxes. I have confirmed that this still exists on a fairly recent (2 weeks old?) version of 6.2 from GitHub. 

I suspect the upload is failing due to an empty title but the uploader isn't handling the error properly. I don't have time to track this down right now and wanted to make sure it was logged for later review.

![error screencap](https://cloud.githubusercontent.com/assets/789760/6488332/d29afdd2-c264-11e4-9bfa-8bb4704b7ac7.png)
![version info](https://cloud.githubusercontent.com/assets/789760/6488336/d52f8a18-c264-11e4-82a2-b12e800ead4a.png)

**Comment by PeterBowater** [comment]
Looks like your Mura version hasn't updated properly, you should have the minor-version of the release after the '6.2'.

Suggest you delete the version.cfm from /config and from each site folder and re-update, this was the only way I could ensure that the files were ACTUALLY updated properly, should be about 4500 of them.

**Comment by cameroncf** [comment]
For the codebase this snapshot is from is a direct pull/merge from GitHub, I don't use the updater for this particular local copy of the codebase on my machine. This is so that I can actually contribute back to the GitHub project from it. If I use the updater I cannot do this since it causes the Git history to be all borked up. In the case that you pull directly from GitHub the minor version is not reported.

Having said that @PeterBowater, if you are saying that you have a totally up to date version and do not see this bug in your copy let me know. That would valuable input.
