### ISSUE TITLE
Possibly incorrect form field label/input IDs

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#1819]
Hi chaps,

Been doing some accessibility work recently, and when using a Mura-generated form we get this output:

```html
<div class="mura-form-textfield req form-group  col-sm-6">
    <label for="name">
        Name <ins>Required</ins>
    </label>
    <input type="text" name="name" value="" data-required="true" class="feedbackName col-sm-6 form-control" data-message="Please enter your name">			
</div>
```

Most accessibility checkers are moaning that there is an orphan label, i.e. there is no field associated with the label (or the other way around). Looking at the guidelines, the 'for=""' attribute should point at the ID of the field, currently Mura is pointing it at the 'name' attribute, which screen readers won't be looking for.

I suggest we may need to add the 'id="name" to the input, that should bring it into compliance pretty simply.

Apologies if I have this wrong, but it appears to be quite common for accessibility checkers to pick up on this.

Cheers,

Peter

**Comment by stevewithington** [comment]
@PeterBowater thanks for the info. I believe we used to have both the "id" and "name" attributes the same on our form fields, so not sure what happened along the way, but we'll take a look.

**Comment by PeterBowater** [comment]
Thanks very much Steve!

Also just came across this, when required = true, the data-required attribute is applied with no space:

```html
<input type="text" name="name" value=""data-required="true" class="feedbackName form-control" data-message="Please provide your name"  />
```

**Comment by stevewithington** [comment]
I've just submitted a fix for this issue. Thanks!

**Comment by PeterBowater** [comment]
Awesome, thanks very much Steve :+1:
