### ISSUE TITLE
Issue with editing site on CF after last commit (extendData.cfc change)

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#1828]
Hi chaps,

Just updated a dev site to 6.2, and finding I get a problem when trying to change site settings via 'Edit site', I'm pretty sure this is because of the most recent commit:

https://github.com/blueriver/MuraCMS/commit/4e095c5c87ee38e31671a415b6b6d0f72c42ed72

This works fine on Railo, but on CF9, it bombs with a 500 error:

![screen shot 2015-03-13 at 12 28 46](https://cloud.githubusercontent.com/assets/807991/6638396/8f35ce26-c97d-11e4-8baa-dba131169162.png)

If I manually revert the file, it all works as it used to.

There is a note on the Adobe site about listqualify, that it requires the 'elements' var to be passed:

http://help.adobe.com/livedocs/coldfusion/8/htmldocs/help.html?content=functions_l_17.html

If you include this in the bit of SQL, it appears to work as it should:

```ColdFusion
and attributeID not in (#ListQualify(ValueList(rsExtended.attributeid), "'", ",", "char")#)
```

All it is doing is passing the default value to ListQualify() for CF, for the delimiter, and setting the 'element' to 'char', as this apparently needs passing for CF.

Hope that helps!

Pete.

**Comment by stevewithington** [comment]
These pesky little differences between engines and versions are silly sometimes. Oh well. Thanks for catching that. A patch has been submitted.

**Comment by PeterBowater** [comment]
No problem, very much appreciated Steve :)
