### ISSUE TITLE
Dynamic settings broken in 6.2

### ISSUE THREAD

**Issue by nsollecito** [blueriver/MuraCMS#1832]
Referencing a [function from cfapplication.cfm in settings.ini.cfm](http://www.getmura.com/forum/messages.cfm?threadid=74161FAD-8053-4DA2-9E5DBB2B5C442CC0#6) is no longer working after an update from 6.1 to the latest

**Comment by nsollecito** [comment]
I'm guessing from [this commit](https://github.com/blueriver/MuraCMS/commit/70f7a7985bb263267b5d1e1141c5c8efae3831ed#diff-96d9135465e87f200ef838f02364e5eb) where evalSettings() refs were all removed

**Comment by nsollecito** [comment]
:+1:

**Comment by Miguel-F** [comment]
This is still not working for me on version 6.2.6458. When I define a function in the config\cfapplication.cfm file and then call that function within the settings.ini.cfm file I get this error - "Variable XXXXXXX is undefined".  This seems to make sense based on the order of operations that I am seeing.  It looks like the ini file values are being evaluated before the cfapplication.cfm file is being included.  Right?

The following ini values are being evaluated:
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L114
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L130
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L191
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L205
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L207
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L216
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L218
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L220
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L226

Before the cfapplication.cfm file which defines the function is being included here:
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L231

How would this work?

**Comment by mattlevine** [comment]
We'll look to fix this, however is it possible for you to use single expressions instead of custom methods?

```
mode=${iif(cgi.server_name eq 'localhost','development','production')}

**Comment by Miguel-F** [comment]
Yes I'm sure we could come up with something that would work. Are the expressions limited to cgi scope variables?  What about the onGlobalConfig file?  I see that in the code but I cannot find any documentation or examples of it.
