### ISSUE TITLE
6.2 Update Error : string	key [contentGatewayLucee] doesn't exist

### ISSUE THREAD

**Issue by al3x-edge** [blueriver/MuraCMS#1844]
https://gist.github.com/al3x-edge/f0e5e6f37342ebb0f34b

Versions:
![image](https://cloud.githubusercontent.com/assets/62131/6824794/a1221192-d2cb-11e4-8e56-0889c3a3388c.png)

**Comment by stevewithington** [comment]
@al3x-edge, are you able to update to the latest version?

**Comment by stevewithington** [comment]
@al3x-edge if anything, you should be able to manually add this file and your error should go away:
https://github.com/blueriver/MuraCMS/blob/d7bd36e51bf4b86ad3d48ee68df505b2a59b9221/requirements/mura/content/contentGatewayLucee.cfc

**Comment by al3x-edge** [comment]
@stevewithington Sorry -- hadn't gotten a chance so far yet to test it.  The problem is that I don't know what version the updater is updating to so I can't look up a tag and pull down the appropriate file. Did think about trying that.  Idea as to why that file isn't coming down with the updates?

**Comment by stevewithington** [comment]
Not really ... but you could try deleting your /config/version.cfm file and updating again as well. However, first I would suggest manually adding the file I suggested, and even manually update the autoUpdater.cfc file (https://github.com/blueriver/MuraCMS/blob/d7bd36e51bf4b86ad3d48ee68df505b2a59b9221/requirements/mura/autoUpdater/autoUpdater.cfc), reload, then try to update again.
