### ISSUE TITLE
6.2.6236 vs 6.2.6235

### ISSUE THREAD

**Issue by gknight593** [blueriver/MuraCMS#1856]
Updated the core to 6.2.6236 with no issue. Tired to update a site to this version, but it stays 6.2.6235.

Tried to add a page after updating to 6.2.6236 and the basic editor is gone!
Any Ideas?

![mura-content-page](https://cloud.githubusercontent.com/assets/847284/6967708/070e650a-d92f-11e4-959c-7ddcc0258760.png)

**Comment by jzuijlek** [comment]
Try removing the config/version.cfm and.or siteid/version.cfm and update again.

**Comment by gknight593** [comment]
Thank worked to restore the editor, but still doesn't update the site to the current version. Thanks for the tip.
