### ISSUE TITLE
Why are pull requests ignored?

### ISSUE THREAD

**Issue by jzuijlek** [blueriver/MuraCMS#1869]
Some of these are really simple fixes which can be looked at in 15 minutes.

Isn't collaboration the whole point of open source?

**Comment by jzuijlek** [comment]
As is this post apparently.

**Comment by al3x-edge** [comment]
@jzuijlek I think there is a small team of people who can approve commits. Biggest suggestion is to ping every week or two.  I'm sure they're busy with things and may not have the bandwidth for the CMS all of the time.

**Comment by mattlevine** [comment]
What pull request were you referring to?  @al3x-edge is pretty much correct.  One thing that is also important is to send us a signed contributor agreement. 

https://github.com/blueriver/MuraCMS/blob/develop/Mura_CMS_contribution_agreement.pdf

Sorry, for the delay,
-Matt

**Comment by al3x-edge** [comment]
Not me Matt. I understand his issue, but I was just trying to highlight part of the deal with a popular open source project with a small team. @jzuijlek might have an actual commit in mind though.

**Comment by jzuijlek** [comment]
Some of my pull request took a long time. But I understand you are a small
team. I'd like to help out. Where do I send the agreement?

**Comment by stevewithington** [comment]
@jzuijlek you can send it to either matt@blueriver.com or steve@blueriver.com ... thank you!
