### ISSUE TITLE
File type error for class extension import when uploading XML

### ISSUE THREAD

**Issue by JeffreyBouva** [blueriver/MuraCMS#1876]
Hi Mura,

I have some problems with uploading a XML file for the extension import.
When uploading a XML file for the extension import, the system will give a popup back saying "Please choose a valid import file." while the file uploading is a XML file.

**Comment by gowestweb** [comment]
I have confirmed the issue and see the potential solution. We should have a fix for this shortly.

**Comment by gowestweb** [comment]
A fix has been added, update your core files to get the change - see commit link above for details.

**Comment by JeffreyBouva** [comment]
@gowestweb very nice! ty
