### ISSUE TITLE
duplicate previewid in version history/audit trail v6.2.6270

### ISSUE THREAD

**Issue by encipherdesign** [blueriver/MuraCMS#1885]
in the admin, under version history or audit trail to the 'Preview' link is duplicating the previewid. the second '?' gets encoded in the browser '%3F'. when that's appended to the querystring the preview fails to render the version expected and pulls in the most recent contenthistID version.

onclick="return preview('http://[domain-url]/?previewid=30201CE7-C09C-6C9E-030B11DE5818B089?previewid=30201CE7-C09C-6C9E-030B11DE5818B089','');"

running this on CF9/mssql & CF11/mysql. mura version: 6.2.6270

i can't quite pinpoint why this var is being duplicated in the query string, & hoping someone may have an idea / fix.

thanks!

**Comment by mattlevine** [comment]
I can't seem to reproduce this issue.  Do happen to have a custom createHREF function in you site's contentRenderer.cfc?

**Comment by encipherdesign** [comment]
Yes… there's a rereplace of the href variable based on an added cfargument passing subtype. 

I had commented that out of the theme contentrenderer but didn't have a different result… so was thinking there might be something else involved?

I've got another install of the latest version ( for another client ) that hasn't presented this same issue…
