### ISSUE TITLE
Tag group with space in name gives 500 error

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#1886]
Hi chaps,

I specified some tag groups, one of which had a space, unfortunatly this gave me a 500 error. The tag groups were defined as:

Documents^News articles^Editorial

Then when going to Site Manager I get the following error:

![screen shot 2015-05-13 at 12 24 27](https://cloud.githubusercontent.com/assets/807991/7609484/2f21b55e-f96b-11e4-93af-6e566db8a8ab.png)

Looks like it is trying to define a CF var with a space, which is of course a no-no. If a space is not going to be allowed, that's fine, but need a note and some validation on submit to ensure the error doesn't happen.

Cheers,

Peter.

**Comment by mattlevine** [comment]
This should be fixed now in Mura 7
