### ISSUE TITLE
Select Associated Image to Upload using "Select Existing Image"

### ISSUE THREAD

**Issue by rdiveley** [blueriver/MuraCMS#1888]
When trying to associate an image to a page using "Select Existing Image" with the latest Mura core/site, the image never get's associated.  The spinning icon just hangs on the screen and nothing happens.

Core Version: 6.2.6299
Site Version: 6.2.6293

Can anyone help me with this issue?
Thank you,

**Comment by rdiveley** [comment]
Anyone else having this issue?  Any recommendations?

**Comment by ArmandoNZ** [comment]
Yes I experience the same. 
Core Version: 6.2.6318
Cheers
Armando

**Comment by rdiveley** [comment]
There is still no updates on a fix to this issue.  I have the same issue on other clients I work with.  Where do I go to get this addressed?  Is this the wrong forum?

**Comment by stevewithington** [comment]
@rdiveley this is the right place to inform us of any issues related to Mura CMS. Please keep in mind that this is an open source project, and we do our best to address bugs/issues as they arise. Thank you.

**Comment by rdiveley** [comment]
Thank you Steve, I appreciate the follow up

**Comment by pauaware** [comment]
Just to confirm I'm seeing this issue too. Searching and selecting a radio button for an existing image in the associated image field never completes. Lucee/CF8/Railo and latest Mura core on all.

**Comment by stevewithington** [comment]
@pauaware thanks for the info, however I would double check that you actually tested on CF8 since Mura now requires a minimum of CF9.0.1+

**Comment by rdiveley** [comment]
Yes, this is happening on CF11
