### ISSUE TITLE
[BUG] Intercept User creation onBeforeUserCreate

### ISSUE THREAD

**Issue by demeee** [blueriver/MuraCMS#1890]
Hi All,

Running Mura v6.2.6298 and can't seem to intercept the user creation function from my eventshandler.cfc anymore. Been trying to intercept as usual to set 'username' but it attempts to save without new values and throws and error  "The username '{1}' that you entered is being used by another user." due to username not being set.

Not sure if this is a bug, any input would be appreciated.

Regards,
Edd

**Comment by mattlevine** [comment]
Would you mind adding a dump/abort in your handler method to just see it it's firing at all?

Is the the eventHandler located at /[siteid]/includes/eventHandler.cfc or  /[siteid]/includes/themes/[theme]/eventHandler.cfc?

Keep in mind that the theme eventHandler is loaded when the application is loaded and is persisted until the next reload.  Then one in in the includes directory is never persisted and each request gets a new instance.  This can be important to know if you expect the new code to run in your theme eventHandler without reloading as you can do in the other.

**Comment by mattlevine** [comment]
I think the problem may be that the userBean has already bean validated by the time the onBeforeUserCreate event is fired.  So there error related to not having a username is already in the errors struct.

So in your event method do something like this:

```
function onBeforeUserCreate($){
    var user=$.event('userBean');
    structClear(user.getErrors());
    
    // start stuff

   // end stuff
  
   user.validate();
}
````

**Comment by demeee** [comment]
Thanks for your reply mattlevine that seems to have done the trick, still getting an empty error box but can be fixed. 

Would this be for every onBefore event...?

**Comment by mattlevine** [comment]
The onBefore events fire after the bean has been validated.  It provides a space where you can then add your own custom validation or handle any errors found in the bean.getErrors() struct.  Then if the bean has errors there is an error box shown to the use that loops through error struct showing each value as an validation message.

In above example, after the user.validate() can you add this:

```
writeDump(var=structIsEmpty(user.getErrors()));
writeDump(var=user.getErrors());
abort;
```

**Comment by demeee** [comment]
Sorry for late rep this I believe is just the wrong class being appended to the confirmation message on edit profile page.
```html
<div class="#this.alertDangerClass#">
<p class="#this.editProfileSuccessMessageClass#">#variables.$.rbKey('user.thankyouinactive')#</p>
</div>
```
Here are the writeDumps:
**writeDump(var=structIsEmpty(user.getErrors()));**
<table title="C:\inetpub\wwwroot\aws\test\default\includes\eventHandler.cfc:120" class="table-dump dump-simple"><tbody><tr class=""><td class="border labelr bgd-simple pointer">boolean</td><td class="border labelr bgl-simple">true</td><td style="display:none" class="border labelr bgl-simple"></td></tr></tbody></table>
**writeDump(var=user.getErrors());**
<table title="C:\inetpub\wwwroot\aws\test\default\includes\eventHandler.cfc:121" class="table-dump dump-struct"><tbody><tr onclick="dump_toggle(this, false)" class="base-header"><td colspan="1" class="border bold bgd-struct pointer"><span class="nowrap">Struct</span><span class="nobold"><span class="nowrap"></span></span></td></tr></tbody></table>
