### ISSUE TITLE
getImageURL: issue with first use of function

### ISSUE THREAD

**Issue by MNU-497** [blueriver/MuraCMS#1895]
includes/themes/ContentRenderer.cfm - ImageCarousel

```
...
<cffunction name="dspCarouselByFeedName" output="false">
...<cfloop condition="local.iterator.hasNext()">...
       <img src="#local.item.getImageURL(argumentCollection=local.imageArgs)#" alt="#HTMLEditFormat(local.item.getTitle())#">
...</cfloop>...
</cffunction>
...
```

This is how it outputs in the first loop:

```
<img src="/index.cfm/tasks/sites/TracyVisits/cache/file/6E7FD6FC-1E67-48F6-B2545D2637AC36C9_carouselimage.jpg"  alt="Mission Statement">
```

But in the second loop it has: 

```
<img src="/tasks/sites/TracyVisits/cache/file/7A6D0B2E-1E67-48F6-B25BC660E6EB78D8_carouselimage.jpg" alt="Meeting / Scheduling / Follow-up">
```

**Why is index.cfm being inserted into the first output of the tag?**

**It produces a broken image so the image does not load, however, the second loop is correct and does load.**

**Comment by MNU-497** [comment]
On this same site contact forms won't display, and I get this issue:

http://mura.welikeit.net/index.cfm/_api/json/v1/?method=processAsyncObject&siteid=default&contentid=6AE348EE-BFAB-4131-A9EFBBE27D590A1A&contenthistid=51C36563-56C7-4861-B19066BF0497F20A&nocache=0&objectparams=%257B%257D&responsechart=0&objectid=46844BA3-72A7-4D3C-B7DEA2F0DC125C25&object=form

This url appears as a request during loading of a page with a form on it. ... the request return a 500 error.

Check it out for yourself on this url (6/1/2015 note, links won't exist forever.)
http://mura.welikeit.net/contact/

I am concerned that If I update any more of my sites they too will break. I gotta fix this soon, please help.

Both core and site version: 6.2.6303
assetdir=D:\Inetpub\ilikeit.net\!Mura\tasks\sites
assetpath=/tasks/sites

**Comment by MNU-497** [comment]
Very old index.cfm file in root of site. ... Been with mura when it was still sava. Updated it with the file found here and everything went back to awesome:

https://github.com/blueriver/MuraCMS/blob/master/index.cfm

**Comment by MNU-497** [comment]
This is **NOT WORKING** correctly yet. I though it was fixed but it is not.

Example of bug: 

the result should be the same for each output of the path but instead the output is: 


Any Suggestions????

Thank you!

**Comment by whortonda** [comment]
I have this exact same issue after updating from 6.1 to 6.2. It only affects the first instance of a Mura image on the page; subsequent image URLs are fine.

Were you able to come up with a fix for this problem?  Thanks for any help you can provide.

**Comment by whortonda** [comment]
I gave up trying to find this in the Mura soruce.  Instead I wrote a jQuery snippet to correct these URLs.  This finds all img tags whose src attribute begins with /index.cfm/tasks/sites (your asset path may be different) and removes the /index.cfm part:

```javascript
$(function() {
	$("img[src^='/index.cfm/tasks/sites']").each(function() {
		$(this).attr("src",$(this).attr("src").substring(10));
	});
});
```

**Comment by ronnieduke** [comment]
@whortonda - is your site caching turned on?

**Comment by whortonda** [comment]
@ronnieduke - Yes site caching was on.  I just turned it off and refreshed, no effect.

**Comment by whortonda** [comment]
It may be worth noting that in my specific case, the original URL of the image is actually being rewritten somewhere.  

I'm seeing this issue on pieces of content which have "hard-coded" URLs.  I checked the HTML source in the Mura site manager, and I even checked the content body directly in the database, so I know the first img tag has the correct URL (/tasks/sites/...) but when loading the page and viewing the HTML source as sent by the server, "/index.cfm" has been prepended to the first img tag only.  So, it's not just the getAssetPath method... there's a content rewrite happening somewhere.

**Comment by mattlevine** [comment]
So are these really old Mura instances that have been upgraded?  I noticed both instances have asset paths of /tasks/sites ?

Is it possible to get ftp access to one of these sites that are having this problem? You could just email me any info at matt.levine@blueriver.com

**Comment by MNU-497** [comment]
I just **worked around the issue** by placing:
&lt;!-- AssetPath=/tasks/sites DIDO AssetPath=/tasks/sites --&gt;
at the top of my header (html_head.cfm) so it would do it's buggy replace on it and nothing else.

**Yes this is a very VERY old MURA install.**
