### ISSUE TITLE
Switched Domain Now Internal pages are rendering 404.

### ISSUE THREAD

**Issue by rwatts3** [blueriver/MuraCMS#1898]
I switched my domain from wattsapplications.com to ryanwatts.io and now my internal pages render a 404. The home screen loads just fine. 

Here are the tasks already completed
- Disabled site caching
- Reloaded Mura Application. 
- Updated Mura Application. 

Screencast : http://screencast.com/t/P89rFBtW

**Comment by JonnyHayes** [comment]
did you add the new domain to the domain alias/primary domain in site
settings?

**Comment by rwatts3** [comment]
I added the new domain as the primary domain name and the old one as the
alias was that wrong to do ?

**Comment by stevewithington** [comment]
@rwatts3 I just watched your video, and the 404 error is not a "Mura" error per se, as it appears to be an issue with your setup in Apache? The error is pointing to your "ErrorDocument" setting, so I would check there.

**Comment by rwatts3** [comment]
Thank you Steve

**Comment by stevewithington** [comment]
@rwatts3 no problem. this link may help you too: http://stackoverflow.com/questions/12760351/getting-404-not-found-error-while-trying-to-use-errordocument
