### ISSUE TITLE
Possibly typo in the contentManager.cfc file?

### ISSUE THREAD

**Issue by Spiderwoman** [blueriver/MuraCMS#1911]
In the contentManager.cfc file on line 1876, is this correct?

< cfset rs = variables.contentGateway.geCategorySummary(arguments.siteID) >

instead of 

< cfset rs = variables.contentGateway.getCategorySummary(arguments.siteID)>

The whole function is 
<cffunction name="getCategorySummary" returntype="query" access="public" output="false">
	<cfargument name="siteID" type="string" required="true" />
	<cfset var rs = ''>
	<cfset rs = variables.contentGateway.geCategorySummary(arguments.siteID)>
	<cfreturn rs />
</cffunction>

**Comment by mattlevine** [comment]
Yes that's a typo.  Thanks for pointing it out.
