### ISSUE TITLE
Accessing custom Event Scopes (eventhandler.cfc) from Remote folder

### ISSUE THREAD

**Issue by demeee** [blueriver/MuraCMS#1912]
Hi all,
I'm trying to call some preset event scopes [ $.event('MYVARIABLE') etc ] from my site eventhandler.cfc which, are to be used on a page I've set up in "default/include/remote/[myfile.cfm]". This however returns an empty string.

The page layout contains a call to setup the muraScope as such along with the display I'm trying to pull via ajax onto my layout:

``` script
<cfscript>
$ = StructKeyExists(session, 'siteid') 
    ? application.settingsManager.getBean('$').init(session.siteid)
    : application.settingsManager.getBean('$').init('default');
</cfscript>
```

I suppose my question is I'm I missing anything? Do I have to initialize anything else to get my event scope or is this a bug?

Regards,
Edd

**Comment by mattlevine** [comment]
Is the 'myvariable' being passed to the remote/myfile.cfm as a url parameter in a ajax call?

Requests that happen outside of a normal mura front end rendering request like ajax calls to a remote.cfc or remote.cfm are not a part of the normal site bound event cycle.  So the eventhandler does not fire.

But any variables that are provided to the remote file via the ajax request should be available through the Mura scope.  Also I would just supply the site value to the ajax request and instantiate the mura scope like this:

param name="url.siteid" default=session.siteid;
$=application.serviceFactory.getBean('$').init(url.siteid);

**Comment by demeee** [comment]
'myvariable' is not being passed to 'remote/myfile.cfm', was wondering if there was any way of making the scope available or I have to push all (10+ ) variables to the remote calls?

**Comment by mattlevine** [comment]
Sorry for missing your last response, please re-open if this is still an issue
