### ISSUE TITLE
FE Editing Component w/Image Ext. Attr. 404

### ISSUE THREAD

**Issue by beamerweb** [blueriver/MuraCMS#1919]
Here's a weird one for you guys -- Just did a core update to make sure it wasn't already fixed and it still persists.

Editing a component on the front-end with an image extended attribute results in a 404 after hitting publish. It seems to be redirecting to the component's filename instead of the page that component is placed on. It works fine in the admin, though.

Prerequisites:
1. A component with at least one File extended attribute
2. A page with an instance of that component placed on it (i do this in the admin)

Steps to reproduce:
1. Login on the front end
2. Navigate to the page with the instance of the component placed on it
3. Click the pencil for that component to bring up front-end editing
4. Upload a new file (i used a jpg)
5. Get the cropping options prompt
6. Return to the component editing
7. Click "Publish"
-- This is where the 404 happens.

I have seen this in two different projects - one CF9, the other Railo 4. One has siteids/index.cfm enabled and one does not. Both are on IIS. It doesn't seem to happen unless you get taken to the image cropping screen, then work your way back - like it loses the URL it should be reloading when you publish.

Thanks guys!

**Comment by christineballisty** [comment]
Bump @stevewithington @ronnieduke - would it be possible to take a look at this? I have a site going in to UAT with this issue. Ping me via Slack for more info. Thanks!

**Comment by stevewithington** [comment]
@christineballisty & @beamerweb, I've submitted a bug fix for this. Thanks!

**Comment by beamerweb** [comment]
Thank you, Steve!

 

Jason Beam

Blue River Interactive Group

 <http://www.blueriver.com> www.blueriver.com

 <http://www.getmura.com> www.getmura.com
