### ISSUE TITLE
Form Level "Force SSL" checkbox has no affect.

### ISSUE THREAD

**Issue by howellcc** [blueriver/MuraCMS#1921]
The "Force SSL" checkbox on the "Edit Form ->Advanced" tab is being ignored when viewing a page that contains that form. 

This was happening as of 6.2.6338.   We noticed this issue after upgrading from 6.0 to 6.2.

Reproduction steps:
1. Create a form and check the "force SSL" box on the Advanced tab. 
2. Place that form on a page. (Do not check the "force SSL" box on the page) 
3. Visit that page.  (you'll notice that you are not redirected to https when viewing the page)

Workaround:
1. Check the "force SSL" box on the page where the form is being displayed. 

The value is being updated in the database, its just being ignored when rendered.

**Comment by mattlevine** [comment]
Sorry for missing this one, please re-open if this is still an issue
