### ISSUE TITLE
Version history blank for component inserted using Mura tag

### ISSUE THREAD

**Issue by brimard** [blueriver/MuraCMS#1923]
When using the Mura tag to insert components within the main body of a page, version history is blank.  It is present if added via layout & objects and within the components module. core 6.2.6338, site 6.2.5025

**Comment by beamerweb** [comment]
Team Mura: This is a site in progress and I have a development environment if you need to see it in action.

Thanks!

**Comment by stevewithington** [comment]
@beamerweb, could you check to make sure you commented on the right issue?

@brimard, I don't understand what your issue is. Are you saying the version history of the page that you edit doesn't get updated when editing it? I'm thoroughly confused here.

**Comment by beamerweb** [comment]
Yep - this is for Ametsoc. We're working on a new site for them.

**Comment by stevewithington** [comment]
@beamerweb, then I'll ping you on Slack.

**Comment by beamerweb** [comment]
Hey @brimard - I just tried to reproduce the issue. I edited the Community page (just copying and pasting the existing mura tag to add two) and i see the changes in that page's version history. Could you offer the steps to reproduce the issue? Thanks!

**Comment by beamerweb** [comment]
Possibly useful info: When trying to look at version history for a component through the front end editing, it comes up blank for components placed on a page using the [mura] tag. But if it's placed in a display region via the layout & objects tab, the version history for that same component looks fine in the front end.

Brian, is this what you were referring to?

**Comment by beamerweb** [comment]
Just talked with Brian on the phone - it IS what i described above. The issue in this ticket is that looking at a component's version history from the front-end editing screen. If it's placed using layout & objects, the version history looks correct. If it's placed with a [mura] tag, the version history shows the headers but no rows of history.
