### ISSUE TITLE
Allow system users to reset their own passwords

### ISSUE THREAD

**Issue by tomchiverton** [blueriver/MuraCMS#1926]
Currently system users are 'special' in that they can't trigger the same password reset process as normal site users, and so have to find another admin if they forget their password.
This other admin then knows their password until/unless they change it.

It would be good for admins to be able to look after themselves in this regard.

**Comment by mattlevine** [comment]
You can allow all users to edit their passwords using placing ?display=editprofile on the frontend on in the admin under the top right "Edit Profile"

Please re-open if this is still an issue
