### ISSUE TITLE
german / spanish mix

### ISSUE THREAD

**Issue by tbrandenburger** [blueriver/MuraCMS#1936]
There are a lot of spanish phrases in the german resource file from the mura backend: 
MuraCMS/requirements/mura/resourceBundle/resources/de.properties

**Comment by MarcAckermann** [comment]
Yes, same problem here: the de.properties file is a mix of 50% german and 50% spanish translations.

**Comment by mattlevine** [comment]
This shouldn't still be happening.  Please reopen this ticket if it is.
