### ISSUE TITLE
Wrong OS Version on Windows 10

### ISSUE THREAD

**Issue by MarcAckermann** [blueriver/MuraCMS#1937]
I updated my notebook to Windows 10 but the OS Version in mura is still shown as Windows 8 (6.2.)
Well, this is not critical and I just wanted to let you.

![os_version](https://cloud.githubusercontent.com/assets/1645475/9132051/e7135834-3cf0-11e5-932a-688c323c1a70.jpg)

**Comment by mrunyon** [comment]
@MarcAckermann This information is reported by the application server (Lucee, Railo, OpenBD, Coldfusion Server, etc). It's likely that an update to Lucee will fix this.

**Comment by MarcAckermann** [comment]
Yes, this is not a mura issue, it's a Lucee problem: server.os.name in the server scope contains wrong information.

**Comment by MarcAckermann** [comment]
Finaly just wanted to add that the problem was caused by an old Java 7 version. I updatet the Java JDK to 8 and now it displays Windows 10.
