### ISSUE TITLE
Section import/export on File Extended Attributes

### ISSUE THREAD

**Issue by beamerweb** [blueriver/MuraCMS#1942]
Hey fellas,

So we just used the section import/export feature in earnest today and came upon a quirk that may not be too tough to resolve.

I have a page subtype with 6 extended attributes of type File. About 75 actual instances of this page have images uploaded to those attributes totalling roughly 250 images. I exported the section these pages live in, then imported them to another site (both on the latest cores as of this morning).

The main thing was that the file extended attributes weren't rendering - the files were in the cache/file directory with the tclassextenddata.attributeValue filenames but there were no records in tfiles where fileId = tclassextenddata.attributeValue for those. Essentially everything but the tfiles records appeared to get created. I verified this by looking at the source install's tfiles and was able to copy that data over into the destination install's tfiles to repair it. It took a little digging to figure that out, though!

Thanks!

**Comment by gowestweb** [comment]
Hi Jason, I had this email saved for a follow-up, was this addressed by Steve or Matt? 

 

thanks

 

 

--

Michael Evangelista

michael.evangelista@blueriver.com

**Comment by beamerweb** [comment]
Hey Michael,

 

I’ve not heard any movement – but I haven’t prodded for it, either.

 

Jason Beam

Blue River Interactive Group

 <http://www.blueriver.com> www.blueriver.com

 <http://www.getmura.com> www.getmura.com
