### ISSUE TITLE
Templates little mistake

### ISSUE THREAD

**Issue by ArmandoNZ** [blueriver/MuraCMS#1949]
Perhaps I am totally wrong but I think all the templates have this small mistake at the end of the code

				</aside>
			</div>
			<cfinclude template="inc/footer.cfm" />
		</div>
	<cfinclude template="inc/html_foot.cfm" />
</cfoutput>

The closing div should before the include footer.cfm and not after. At least that's what bootstrap is doing in there examples.
http://getbootstrap.com/examples/sticky-footer-navbar/

Cheers
Armando

**Comment by stevewithington** [comment]
@ArmandoNZ, 

Actually, the example we used as the basis for our theme is the one located at http://getbootstrap.com/examples/jumbotron/.

Keep in mind that you can modify the theme however you see fit. What we've provided is simply a starting off point.

Cheers,
Steve
