### ISSUE TITLE
500 Error caused by missing file after new site creation

### ISSUE THREAD

**Issue by mikechy** [blueriver/MuraCMS#1955]
Pulled the master version and installed from scratch.  After install, updated core to latest.  Created a new site in the admin. After new site is created and viewed from the front end a 500 error is generated complaining about a missing less file.

Could not find LESS global, 'D:/WEB/forestviewmarina.com/htdocs/forestviewmarina/includes/themes/MuraBootstrap3/css/less-globals/globals.less'

Code: null

Type: null

coldfusion.runtime.CustomException: Could not find LESS global, 'D:/WEB/forestviewmarina.com/htdocs/forestviewmarina/includes/themes/MuraBootstrap3/css/less-globals/globals.less'
	at coldfusion.tagext.lang.ThrowTag.doStartTag(ThrowTag.java:142)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:2991)
	at ......

**Comment by stevewithington** [comment]
Is the less file missing? If so, copy it from the 'default' site's css directory.

**Comment by mikechy** [comment]
That's the odd thing.  The default folder didn't have it either.  I have installed Mura about 20 times and usually the first thing that I do is create a new site, leaving the default site as is.  I killed everything, removed the database, installed from a fresh copy of 6.2 and did NOT perform any updates this time.  No issues.  I was able to reproduce the error with the current version 5 times.  

Env is Windows 2012 Server  CF11 Standard.

**Comment by stevewithington** [comment]
Where did you download Mura from? Did you get it from here on Github? Because it's there:
https://github.com/blueriver/MuraCMS/blob/develop/default/includes/themes/MuraBootstrap3/css/theme/theme.less

**Comment by mikechy** [comment]
Pulled it from github as I always do.  Could it have something to do with the latest update from 6.2?  I can try and re-create again.  

thanks for your quick reply to this, btw.

**Comment by mikechy** [comment]
I did look in the default folder after the error.  That folder you mention was not what it was looking for it was:

/forestviewmarina/includes/themes/MuraBootstrap3/css/less-globals/globals.less

**Comment by stevewithington** [comment]
The latest version of the theme no longer uses that file. Could you do a search through your theme files and find out where you have a call to globals.less at? I wonder if you somehow have an old version of the theme and somehow mixed it up with the latest version?

**Comment by stevewithington** [comment]
In fact, it sounds like you're still using some old layout templates. I would check your file located under /{SiteID}/includes/themes/MuraBoostrap3/templates/inc/html_head.cfm

The latest version is only calling theme.min.css:
https://github.com/blueriver/MuraCMS/blob/649f08e34f783b1440eeac7aa86b9bcf98454674/default/includes/themes/MuraBootstrap3/templates/inc/html_head.cfm#L25-L29

You'll see that the file is now pre-compiled and minified.

In 6.1, we used to use CFStatic:
https://github.com/blueriver/MuraCMS/blob/b414654d59368de4ab36bd4b432d077af373d2bf/default/includes/themes/MuraBootstrap3/templates/inc/html_head.cfm#L26-L30

If you have the 6.1 code, then you're not up to date. Also, keep in mind that Core and Site updates don't touch anything under the theme.

**Comment by mikechy** [comment]
It does appear that it was due to the existence of an older template.  Thanks, Steve  I will close.
