### ISSUE TITLE
Inconsistency between filename and urltitle when using the "clear SEO titles" button

### ISSUE THREAD

**Issue by JordiBeen** [blueriver/MuraCMS#1968]
The last part of the filename (after the last "/") will not be identical to the urltitle.

For example: 
- Before saving the filename is "locations/central-station" and the urltitle is "central-station".
- Change the title to "Central station square" and use the "clear SEO titles" button.
- After saving the filename is "locations/central-station" and the urltitle is "central-station-square".

However I would expect the filename to be "locations/central-station-square".

**Comment by mattlevine** [comment]
Sorry for missing this one, yes that seems strange?  please re-open if this is still an issue
