### ISSUE TITLE
SiteID of ALL Related Content Sets are overwriting on Copy site

### ISSUE THREAD

**Issue by JeffreyBouva** [blueriver/MuraCMS#1973]
We are working on two sites within one mura instance. We have a Dutch(siteid-NL) and a English(siteid-NL) version. When i copy the Dutch version to the English version it will copy all the content, but i will not copy the entries in the table 'tclassextendrcsets' instead it will rename all siteid's from 'siteid-NL' to 'siteid-EN' and not copy the entries!

**Comment by JonnyHayes** [comment]
This might help - Eddie B.@ blueriver knocked this up for me when I was
having a similar issue. Not exactly the same as what you are experiencing,
but might point you in the right direction. Good luck!
cheers

**Comment by JonnyHayes** [comment]
with the link this time?!
https://gist.github.com/JonnyHayes/c57fe18e24dfe886b6c4

**Comment by JeffreyBouva** [comment]
@JonnyHayes Thank you so much! I hope that @ blueriver will implement this in the copy script of mura.
