### ISSUE TITLE
onSiteLogin called on admin login

### ISSUE THREAD

**Issue by jzuijlek** [blueriver/MuraCMS#1985]
After a mura core update I noticed the onSiteLogin() function in my plugin was called on an admin login. This didn't happen in previous versions.

**Comment by mattlevine** [comment]
Basically, the onSiteLogin fires if a siteid is defined.  So it is weird that you would be seeing it fire in a normal admin login.

Sorry for missing this originally, please re-open the ticket if this is still causing a problem.
