### ISSUE TITLE
Edit Image Properties get not updated in DB after Submit "Save"

### ISSUE THREAD

**Issue by ArmandoNZ** [blueriver/MuraCMS#1986]
![upate-failure](https://cloud.githubusercontent.com/assets/11189033/10527689/5e2d7b32-73ee-11e5-9918-3e92649f21e8.jpg)

**Comment by mattlevine** [comment]
Just to set how it works when you upload a new image it places the meta data into tfiles.  When you edit file meta data it places that data into tcontentfilemetadata and only update tfiles again if you check "Set as default values?" at the bottom of the form.

**Comment by ArmandoNZ** [comment]
Thank you Matt
I tried to use "default values" at the bottom in version 6.2.6408. Sorry no difference. It get changed in the admin UI in the content but if I use this data in a carousel info-icon:

<cfset this = $.content().getContentID() />
<cfset item = $.getBean('content').loadBy(CONTENTID=this) />
<cfset itRelatedContent =  item.getRelatedContentIterator(name='Carousel')/>

<cfset myImage = $.getBean('fileMetaData').loadBy(fileid=item.getFileID())/>
#(myImage.getCaption())#
#(myImage.getCredits())#

I get the first initial data and not the updated data.

Is my code incorrect?

**Comment by ArmandoNZ** [comment]
Thank you Matt
I tried to use "default values" at the bottom in version 6.2.6408. Sorry no difference. It get changed in the admin UI in the content but if I use this data in a carousel info-icon:

< cfset this = $.content().getContentID() />
< cfset item = $.getBean('content').loadBy(CONTENTID=this) />
< cfset itRelatedContent = item.getRelatedContentIterator(name='Carousel') />


#(myImage.getCaption())#
#(myImage.getCredits())#

I get the first initial data and not the updated data.

Is my code incorrect?

Kind Regards

Armando

 

PS

I answered direct in github as well

**Comment by mattlevine** [comment]
Hm, in the above you do not actually set myImage.  However, there are two things that immediately jump out at me.

1. You're setting a variable named "this".  This is a reserved word that already represents the component in which the code is being executed.

2.  You don't need to load the content node of of the current request.  It's actually already there.  The $.content() method is just wrapping the $.event('contentBean') entity that is what the request is currently rendering.

Try this:

```
myImage=$.content().getFileMetaData();
```

That is the same as:
```
$.event('contentBean').getFileMetaData()
```

If you have an extended attribute that has an image you can get that meta data with 

```
$.content().getFileMetaData(property='varname');
contentBean.getFileMetaData(property='varname');
```

**Comment by ArmandoNZ** [comment]
Already Christmas in blueriver land - I am getting a free private lesson from Matt Levine - how good is that :-)

I could be so happy about that, if it would not be so frustrating to distract Matt with rubbish :-(

Matt I have nearly no idea about CF - just one off this person who does horrible things to your baby without really knowing what is going on. Your code works just fine!!!


< cfset myImage = $.getBean('fileMetaData').loadBy(fileid=item.getFileID()) />


< cfset myImage = item.getFileMetaData() />

But next to be embarrassed - Thank you for the present - Was nice to learn

Kind Regards
Armando
