### ISSUE TITLE
Custom Folder Output async bug?

### ISSUE THREAD

**Issue by jgibba** [blueriver/MuraCMS#1987]
I made a custom folder class extension and copied and renamed dsp_folder_<SubType>.cfm to custom/extensions directory which works every time as normal.

However, this time it wouldn't show the custom output and only render the default folder output file.

I resolved this by setting this.asyncObjects = false in content renderer which resolved the issue.

What would cause this issue to happen? I see the latest dsp_folder.cm has some async logic I'm wondering that affects this?

https://github.com/blueriver/MuraCMS/blob/develop/default/includes/display_objects/dsp_folder.cfm#L57

Running latest Mura 6.2.6395

Thanks,
Jon

**Comment by mattlevine** [comment]
Sorry for missing this one, please re-open if this is still an issue
