### ISSUE TITLE
MySQL 5.7 error in dbUpdates

### ISSUE THREAD

**Issue by fraxen** [blueriver/MuraCMS#1990]
Doing a fresh install off mura 6.2.6415 download. Windows host, using Apache and Tomcat 7 64-bit, with Lucee 4.5.1.024 and MySQL 5.7.8-rc

*SQL: CREATE TABLE IF NOT EXISTS `tuserstrikes` ( `username` varchar(100) default NULL, `strikes` int(10) default NULL, `lastAttempt` datetime default NULL, PRIMARY KEY (`username`) )
All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
requirements\mura\dbUpdates\5.2.0.cfm:373*

When I update the file to use 'default 0' instead, it proceeds.

**Comment by RedWombat** [comment]
Thank you for this post.  Your solution helped me finish my install of Mura.

I had the same issue installing Mura.  I'm running Windows Server 2012 and IIS 8.5.  Everything else is the same as Fraxen's post.
