### ISSUE TITLE
ERROR: '' is not a valid date/time format ./requirements/mura/extend/extendData.cfc : line 378

### ISSUE THREAD

**Issue by encipherdesign** [blueriver/MuraCMS#2005]
on AppStart/Reload: 

Expression Exception ./requirements/mura/extend/extendData.cfc : line 378
'' is not a valid date/time format 

v 6.2.6426

**Comment by mattlevine** [comment]
I added logic to prevent empty strings from being parsed, but it's strange that the error is not being trapped?

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/extend/extendData.cfc#L377-L380

What version of CF are you on?

-Matt

**Comment by nopjmp** [comment]
I've tested this on both CF11 and CF12 (prerelease). This is the new behavior on CF11+.

Code tested:
```
<cfdump var="#parseDateTime('')#">
```
