### ISSUE TITLE
Mura install error with MySQL

### ISSUE THREAD

**Issue by jgibba** [blueriver/MuraCMS#2012]
After installing latest Mura version 6.2.6448 with MySQL, receive attached error. 

MySQL doesn't seem to like this sql statement:
ALTER TABLE tsessiontracking ADD COLUMN fname varchar(50) default null 

I removed the contents of /requirements/mura/dbUpdates/6.1.1.cfm & reloaded and seemed to work fine

Thanks,
Jon
![mura_install_error](https://cloud.githubusercontent.com/assets/5321848/11345307/15051816-91e4-11e5-999a-e9087ada7162.png)

**Comment by mattlevine** [comment]
Please update your core and reload with applydbupdates in the url

?appreload&applydbupdates

**Comment by jgibba** [comment]
Hi Matt, updated core and ran that url but still seeing attached error - anything I'm missing on my end?
![mura_upgrade_error2](https://cloud.githubusercontent.com/assets/5321848/11346242/ace4fc28-91e9-11e5-8542-6a6168776e57.png)

**Comment by mattlevine** [comment]
I just saw something I missed the first time.  Can you open up the tsettings in a mysql client and tell me what the default for 'entered' is?

**Comment by jgibba** [comment]
@mattlevine , I'm not seeing a column for 'entered' in tsettings table - did you mean to say something else?

Jon

**Comment by mattlevine** [comment]
There may be something corrupted about it? Here's where it should have been created

https://github.com/blueriver/MuraCMS/blob/develop/config/setup/db/mysql.sql#L690

Can you try and add it manually and then re-try the ?appreload&applydbupdates  ?

**Comment by jgibba** [comment]
Ah my bad I was looking at tsettings table you mentioned above but the url points to tsessiontracking table, which I do see in the database with a NULL default value - does that help?

**Comment by mattlevine** [comment]
It's not supposed to be null:

https://github.com/blueriver/MuraCMS/blob/develop/config/setup/db/mysql.sql#L690

Could you try setting the default to '0000-00-00 00:00:00' ?

**Comment by jgibba** [comment]
Matt, I tried the following which resulted in invalid default value for the 'entered' datetime column:

ALTER TABLE tsessiontracking ALTER entered set DEFAULT '0000-00-00 00:00:00';

Oddly enough, the MySQL docs state the following:

MySQL does not accept TIMESTAMP values that include a zero in the day or month column or values that are not a valid date. The sole exception to this rule is the special “zero” value '0000-00-00 00:00:00'.
http://dev.mysql.com/doc/refman/5.7/en/datetime.html

Any other suggestions?

Thanks,
Jon

**Comment by mattlevine** [comment]
I'll have to upgrade mysql versions to see this error. This has been the schema for Mura since it was launched.  I would just set the default to a value that works like NOW()

**Comment by mattlevine** [comment]
I'll have to upgrade mysql versions to see this error. This has been the
schema for Mura since it was launched.  I would just set the default to a
value that works like NOW()
