### ISSUE TITLE
Mura Form adding undefined to action

### ISSUE THREAD

**Issue by Reyjay** [blueriver/MuraCMS#2014]
I updated to 6.2.6447 and have been getting an issue with mura forms where "undefined" is added to the action instead of "nocache=1" (on all forms).  This prevents the form from submitting and sends you to a 404 page, and looks like it's an issue with the dataCollectionManager.cfc.

EX: <form id="frm05A655E5E9C385F60000006924D66771" method="post" name="contact-us" action="undefined#frm05A655E5E9C385F60000006924D66771">

**Comment by mattlevine** [comment]
Please update your core once more and retest.

**Comment by Reyjay** [comment]
Your the man Matt.  Everything works perfect after the update.  Thanks!
