### ISSUE TITLE
Wrong root path - duplicate directory

### ISSUE THREAD

**Issue by steffenkoller** [blueriver/MuraCMS#2041]
Hi, 

I am new in Mura and set it up according docu.
Finally copied the files in a subdirectory of railo, get the setup page where I entered database config.
Finally I got the message "setup complete". 
Then I should be brought to the login page, but that does not happen. Localhost seem to hang.

Calling the page "//localhost:8888/tanzen" I got a page with "something" with content "Home"  but without any formatting.
Documents source was:
`
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="generator" content="Mura CMS 6.2">
<title>Home - Default</title>
<link rel="stylesheet" href="/tanzen/tanzen/default/css/mura.6.2.min.css">
.....
`
So looking at the last line, the directory "tanzen" was doubled and therefore the css file cannot be found there. This "double" is everwhere in the document, nut just for that css-file.
But I have no idea why this directory was twice in the path. 

I have treid to copy the stuff in another subdirectory "tanzen" to at first check satisfy the link, but then I just get some errors that the root cannot be detected or something....

Any ideas?
Thank you very much!

Steffen

**Comment by mattlevine** [comment]
I would check the your /config/settings.ini.cfm and make sure that your context and assetpath variables are the same as the sub directory you have Mura running in.  So in your case the should read 

context=/tanzen
assetpath=/tanzen

If you make any changes you'll need to reload Mura for the new attribute values to be seen by Mura.

-Matt

**Comment by steffenkoller** [comment]
Thank you for the hint. I have checked that settings file already and the two lines are exact as you stated and I had expected. 
Is there a way to debug the processing of the "handleRootRequest" that is the content of the index.cfm file.

**Comment by mattlevine** [comment]
Can you create a temp.cfm in your Mura root an then put this in it and run it?

<cfdump var="#application.configBean.getContext()#">

Is the /tanzen a java context or a sub directory?

**Comment by steffenkoller** [comment]
railo/webapps/tanzen is what I understand as my "muraCMS root" as I have put all muraCMS files in it like this index.cfm with the "handleRootRequest" call.
I have created a temp.cfm file with the content `<cfoutput>#application.contentServer.handleRootRequest()#</cfoutput>`
I tried "//localhost:8888/tanzen/temp.cfm" but get the same result. A "home" page without any formatting and redundant "tanzen" in the path of included css files.

(tanzen itself is a subdirectory under my railo/webapps directory to get it "included" from the railo framework. under localhost:8888/ I get the railo 4.2 "home page")

Thank you for your support!

**Comment by mattlevine** [comment]
I think the issue is that the context is supposed to be the first real
directory and not Java container context. Try setting the settings.ini.cfm
context and asset path values to empty strings and reload Mura.

**Comment by steffenkoller** [comment]
Yes that works.  My empty home page is now formatted properly. 
So I will now try to generate a homepage based upon a two column framework and hope configuring and maintaining a homepage in MuraCMS is as easy as I have read somewhere ;)

Thank you very much for your help, Matt!
