### ISSUE TITLE
Very slow performance - something seem to hang so possible a timeout occurs

### ISSUE THREAD

**Issue by steffenkoller** [blueriver/MuraCMS#2043]
Hi all,

I have succesfully installed MuraCMS based upon railo and local MySQL database.
It is so far ok to get the "login" page "localhost:8888/tanzen/admin"  (tanzen is my root for the MuraCMS) but the overall performance is bad. I can indeed login and change some settings e.g. enable the caching for that site, but it takes minutes in that ny browser is hanging and the system is not longer responsive.

Here now, I have by purpose entered an incorrect login in above mentioned page.
I have logged the http-headers using http-fox to demonstrate that it takes minutes to the final "there is no account" message - that is functionally correct, but I have no idea, what cause the tremendous delay.
My SQL database is local and it seem not to be a connection issue, but more a javasrcipt issue,
as is is the jquery.ui.base.css that takes long and I expect a timeout finally occurs.

I have chosen the wrong login try as it is easy to reproduce and does not create lots of action.
Please find the result in the attached file.

[MuraCMS_TimeLog.txt](https://github.com/blueriver/MuraCMS/files/75940/MuraCMS_TimeLog.txt)

My tries to enable TRACE as log level for everything in railo server and obtain other information about any problem does not provide any help.

What can I do to determine the root cause? - (And fix it)
Thank you

Steffen

**Comment by davidpanzarella** [comment]
Do you have debugging turned on? If so, this could easily be the issue. Also,
how much ram do you have allocated to Railo? Fusionreactor would make figuring what's slowing things down very easy as well.

On Fri, Jan 1, 2016 at 7:34 AM steffenkoller <notifications@github.com> wrote:
Hi all,

I have succesfully installed MuraCMS based upon railo and local MySQL database
It is so far ok to get the “login” page “localhost:8888/tanzen/admin” (tanzen is
my root for the MuraCMS) but the overall performance is bad I can indeed login
and change some settings eg enable the caching for that site, but it takes
minutes in that ny browser is hanging and the system is not longer responsive

Here now, I have by purpose entered an incorrect login in above mentioned page
I have logged the http-headers using http-fox to demonstrate that it takes
minutes to the final “there is no account” message - that is functionally
correct, but I have no idea, what cause the tremendous delay
My SQL database is local and it seem not to be a connection issue, but more a
javasrcipt issue,
as is is the jqueryuibasecss that takes long and I expect a timeout finally
occurs

I have chosen the wrong login try as it is easy to reproduce and does not create
lots of action
Please find the result in the attached file

MuraCMS_TimeLogtxt

My tries to enable TRACE as log level for everything in railo server and obtain
other information about any problem does not provide any help

What can I do to determine the root cause? - (And fix it)
Thank you

Steffen

**Comment by steffenkoller** [comment]
As far as I understand, debug is not enabled.  
First I have not activated it manually and a check brought some "debug activated start script" that does some more settings to call the java for muraCMS.
Second I have not found any log file or output that such a debug should generate.

I don't know about setting RAM for railo. 
As I am not firm with that environment I need some more detailed description.

**Comment by davidpanzarella** [comment]
Have you actually logged into the Railo admin to confirm? It will show it all
right there, including the amount of RAM used. My hunch is that you either have
debugging output on or are running on very little RAM. Its possible that your
MySQL is slow as well.
Have you tried installing a clean instance of Mura to test that something in the
installation didn't get messed up?
You can find all the logs btw, inside of your Railo logs directory.

On Sat, Jan 2, 2016 at 9:00 AM steffenkoller <notifications@github.com> wrote:
As far as I understand, debug is not enabled.

First I have not activated it manually and a check brought some "debug activated
start script" that does some more settings to call the java for muraCMS.
Second I have not found any log file or output that such a debug should
generate.

I don't know about setting RAM for railo.
As I am not firm with that environment I need some more detailed description.

**Comment by steffenkoller** [comment]
Hi David,

I'm back on my MuraCMS project. Thank you for your hints.

My MySQL server seems to be run fine, as with other applications I got the expected performance,
Also I have tried a complete new installation of MuraCMS and got the same situation.
I have tried to set all debug options to "verbose" and look at any log files I can find, but none of them  provide any content.

The RAM usage I could not find. - But lots of settings instead :)
It is a miracle....
What I found out: After waiting long to get the first page in the admin folder (using correct credentials)  selecting pages there (like "site configuration") seems to work with acceptable performance.

**Comment by steffenkoller** [comment]
Question: In the version tab i see the Java version  1.7.0_55.
That seems to be a very low number.

Maybe I should update that and use a new version of Java?

**Comment by davidpanzarella** [comment]
Oh, are you saying you have debugging turned on in the cf admin? If so,
that's your issue. Mura is just to heavy to dump all of its data on every
page via debug.  If you need to see what's run, you can always use the
stacktrace  param in the url.

Hope this helps

Sent from my iPhone

On Feb 2, 2016, at 3:20 AM, steffenkoller <notifications@github.com> wrote:

Hi David,

I'm back on my MuraCMS project. Thank you for your hints.

My MySQL server seems to be run fine, as with other applications I got the
expected performance,
Also I have tried a complete new installation of MuraCMS and got the same
situation.
I have tried to set all debug options to "verbose" and look at any log
files I can find, but none of them provide any content.

The RAM usage I could not find. - But lots of settings instead :)
It is a miracle....
What I found out: After waiting long to get the first page in the admin
folder (using correct credentials) selecting pages there (like "site
configuration") seems to work with acceptable performance.

—
Reply to this email directly or view it on GitHub
<https://github.com/blueriver/MuraCMS/issues/2043#issuecomment-178517570>.

**Comment by steffenkoller** [comment]
I have set all logs from TRACE to ERROR (and restart MudaCMS), but that makes it worse. Loggin in now takes several minutes instead dozends of seconds. Looks like the lock now is not intercepted by the tracing so my browser hangs completely in that time. 

Before that change I edited my homepage, added two sentences and clicked "store and preview" - this process then took lots of minutes and was then somehow terminated "script does not react" so I stopped it.

What I saw is that "nautilus" as process took significant CPU load that time. No Idea why, but maybe due to a kind of interlock....

Can you explain that "stacktrace parameter" and where to find the results?

**Comment by davidpanzarella** [comment]
So i'm still confused. In Railo you have debugging turned off right?

On Tue, Feb 2, 2016 at 4:38 AM steffenkoller <notifications@github.com> wrote:
I have set all logs from TRACE to ERROR (and restart MudaCMS), but that makes it
worse. Loggin in now takes several minutes instead dozends of seconds. Looks
like the lock now is not intercepted by the tracing so my browser hangs
completely in that time.

Before that change I edited my homepage, added two sentences and clicked "store
and preview" - this process then took lots of minutes and was then somehow
terminated "script does not react" so I stopped it.

What I saw is that "nautilus" as process took significant CPU load that time. No
Idea why, but maybe due to a kind of interlock....

Can you explain that "stacktrace parameter" and where to find the results?

**Comment by steffenkoller** [comment]
Yes, in the server settings under Debug I had "Railo logs debug information you have checked below." selected, now I turn it off.- Login in needs still again about 3min to see the site manager page,
Can it be a browser issue? I use firefox 44.0.   I have discoverd that when the indication is "waiting for localhost" I can stop the railo webservice but this does not terminate this "wait state",,,,

**Comment by davidpanzarella** [comment]
So firstly, completely turn off debugging in Railo. Be sure that both the server
and the web admin both have it turned off.
Secondly, does it take more than a few seconds for Railo admin to show up or is
it fast?
Last, you may want to restart Railo just for good measure. Also, are you using apache in the front, or just hitting the default railo port?

On Tue, Feb 2, 2016 at 11:37 AM steffenkoller <notifications@github.com> wrote:
Yes, in the server settings under Debug I had "Railo logs debug information you
have checked below." selected, now I turn it off.- Login in needs still again
about 3min to see the site manager page,
Can it be a browser issue? I use firefox 44.0. I have discoverd that when the
indication is "waiting for localhost" I can stop the railo webservice but this
does not terminate this "wait state",,,,

**Comment by steffenkoller** [comment]
Both server and web admin have it disabled. 
I just use the default setup.  Under localhost:8888  I get the railo page - in normal speed and performance.
localhost:8888/tanzen is my (just emtpy) homepage. I get that also in a few seconds.
Then I try localhost:8888/tanzen/admin to log in.  I have no plugin, nothing special.
As far I have understood, MursCMS use jetty that drives port 8888 and not apache.
cmd line is "jre/bin/java -DSTOP.PORT=8887 -DSTOP.KEY=railo -javaagent:lib/ext/railo-inst.jar -jar start.jar --module=http jetty.port=8888" to start it....

**Comment by steffenkoller** [comment]
hey good news - it seems that restarting firefox now finally leads to normal performance...?  I am checking that...

**Comment by steffenkoller** [comment]
selecting several pages of railo work normal, so I now can switch e.g. to file manager part or similar, but some places when I try to modify content or open a obviously existing edited content that still hangs.

**Comment by davidpanzarella** [comment]
Just to confirm:
localhost:8888/tanzen/admin --- is slow localhost:8888/ -- is normal?

On Tue, Feb 2, 2016 at 12:05 PM steffenkoller <notifications@github.com> wrote:
hey good news - it seems that restarting firefox now finally leads to normal
performance...? I am checking that...

**Comment by steffenkoller** [comment]
Yes, status of today after a reboot this morning.
localhost:8888/  shows railo and all pages of settings are normal in performance and immediately there. Also localhost:8888/tanzen shows the homepage and all I can see there is in normal performance: The search, the "sample modal window" - more is not there at the moment.

I have done reboot, test /tanzen/admin and login with wrong credentials:
After about 10min seeing "waiting for localhost" I killed firefox as it does not at all responding.
This behaviour is mystic.....
Normally I thought it is easy to identify what is hanging, but currently I have no ideas.

**Comment by davidpanzarella** [comment]
So it looks to me like might be an issue with your Railo setup. Did you use the
Mura Express Installer? Or did you use your own Railo setup?

On Wed, Feb 3, 2016 at 2:51 AM steffenkoller <notifications@github.com> wrote:
Yes, status of today after a reboot this morning.
localhost:8888/ shows railo and all pages of settings are normal in performance
and immediately there. Also localhost:8888/tanzen shows the homepage and all I
can see there is in normal performance: The search, the "sample modal window" -
more is not there at the moment.

I have done reboot, test /tanzen/admin and login with wrong credentials:
After about 10min seeing "waiting for localhost" I killed firefox as it does not
at all responding.
This behaviour is mystic.....
Normally I thought it is easy to identify what is hanging, but currently I have
no ideas.

**Comment by jsieber-aca** [comment]
Just chiming in from the peanut gallery, this could be due to way too little ram being dedicated to the jvm. The Mura docs suggest 512mb as a minimum, but I would consider 1gb to be the ideal minimum. More info here: http://docs.getmura.com/v6/installation-setup/performance-tips/

**Comment by steffenkoller** [comment]
I have changed the start cmd line to "jre/bin/java -Xms1024m -Xmx2048m -DSTOP.PORT=8887 -DSTOP.KEY=railo -javaagent:lib/ext/railo-inst.jar -jar start.jar --module=http jetty.port=8888"  (added the -Xms1024m -Xmx2048m.
Result: Seems to increase the performance, so I see "localhost read"  and got the message, that credentials are wrong after about 3 minutes.

Still not what I would define as "running"....

**Comment by jsieber-aca** [comment]
That should be plenty of memory. I with David, wondering if something is not right with your Railo setup.

**Comment by davidpanzarella** [comment]
Yeah if you allocated that much ram to railo, there is no doubt in my mind that
your set up is borked. I'd recommend installing again, and trying that.

On Thu, Feb 4, 2016 at 8:15 AM John Sieber <notifications@github.com> wrote:
That should be plenty of memory. I with David, wondering if something is not
right with your Railo setup.
