### ISSUE TITLE
Content Collections , folder do not show up when finding section for local index

### ISSUE THREAD

**Issue by 2species5618** [blueriver/MuraCMS#2044]
When you try to add a local index on contect page and you try to select what folders it should manage, you doe not get the folders selection. mura hangs on a loading symbol

![content](https://cloud.githubusercontent.com/assets/16597449/12177781/46dbb96e-b56e-11e5-9ea2-f0eb2567c6c5.jpg)

Anyone know how to solve this?

**Comment by mattlevine** [comment]
Can you refresh the page and then turn on your from debugger and look for any errors in the console?

**Comment by 2species5618** [comment]
Hi thank you for responding. I'm new to mura just so you know
The only error I can find so fast is this one:

![error1](https://cloud.githubusercontent.com/assets/16597449/12186382/5d0b0f26-b5a2-11e5-8fb1-18e9046b78f3.JPG)

 This is what is shown in the console:

![error2](https://cloud.githubusercontent.com/assets/16597449/12186424/f743d622-b5a2-11e5-89c6-08bcc2a07327.JPG)


I'm thinking it might me a accesright issue as I have some more small strange issues (like with getting a attribute when using side id's).

Anyway if you have any thought it would be welcome

**Comment by 2species5618** [comment]
This is a fresh install on:
- windows server 2008 (updated)
- railo (latest version)
- MySQL (latest version)
- IIS, using mura 6.2x code base
 
every thing seems to work fine.

**Comment by mattlevine** [comment]
If you click the body tab next to the headers tab where you added the
pointer I think you can see the actual error.

**Comment by 2species5618** [comment]
Hi, 
a, yes that a good one :)
 
The full  result is attached in a txt file. but this is what I allready could get out te be a issue:

'''
<h3>Unknown column &#x27;sortdate&#x27; in &#x27;order clause&#x27;<br /></h3>
'''

Thanks so far

[error.txt](https://github.com/blueriver/MuraCMS/files/82640/error.txt)

**Comment by mattlevine** [comment]
Could you please update your core and retest.  I believe that issue was recently fixed.

-Matt

**Comment by 2species5618** [comment]
Hi,

Ill do so tomorow currently cannot acces this site. 
Anyway thanks so far for you help. Ill let you know.

Regards,

**Comment by 2species5618** [comment]
Hi,

Mura update resulted in a error:

![capture-update](https://cloud.githubusercontent.com/assets/16597449/12216334/03d05e38-b6de-11e5-9110-91a4627b7744.JPG)

However, after this I am able to add the collection dir somehow, but its not working
When I try to add the index collection to the main body using the mura page (in my case the home)
It hangs again:

![concent-adding](https://cloud.githubusercontent.com/assets/16597449/12216395/e0ba5834-b6df-11e5-93d0-4cd527678b56.JPG)

I have added the error from the body tag.

[error-add.txt](https://github.com/blueriver/MuraCMS/files/83661/error-add.txt)

Is it possible something is wrong with the site install (mura/iis/railo)?

Note: this is a new install of a new site.

Any thought was going on? I can setup a other server using the mura express installer this time to see if its work better.

Regards,

**Comment by mattlevine** [comment]
The error in reference to the propertyValue was an random error that can
when auto updating.  We're working getting rid of those, but they are more
of an annoyance.  However, please update once more for the fix to the slide
show configurator issue.

-Matt

**Comment by 2species5618** [comment]
Hi,
There is improvement I can now indeed add a local index and display them using the main section option in mura and display it in my home.cfm using:

![Uploading index-aBlog-output-at-homedotCfm.JPG…]()

However this only works for:
- display local index slide show

And to add to it this
- display local index

has now stop function (it was working before the update)

I get the following error on the home page where previously the blog should have been:

![index-items](https://cloud.githubusercontent.com/assets/16597449/12217660/b29121c2-b707-11e5-81f3-5fbcde047e7f.JPG)

regards

**Comment by 2species5618** [comment]
For your info this how its configured:

config blog dir
![index-ablog](https://cloud.githubusercontent.com/assets/16597449/12217688/6d6b1cdc-b708-11e5-9e60-a57c71a80447.JPG)

added content to home:
![index-ablog-2](https://cloud.githubusercontent.com/assets/16597449/12217693/861ccd52-b708-11e5-8142-22920286e962.JPG)

and here is the blog:
![index-ablog-3](https://cloud.githubusercontent.com/assets/16597449/12217706/fdb6d0b0-b708-11e5-9dca-4cf82186853a.JPG)

regards

**Comment by mattlevine** [comment]
Yikes,  please update once more.

**Comment by mattlevine** [comment]
https://github.com/blueriver/MuraCMS/commit/1245566bb1f1fd1bc03476103c5250dbbef750b0

**Comment by 2species5618** [comment]
haha np,

How ever still no luck same error:


And a question:
If I make a list in context modules for my video collection like this:

![capture0](https://cloud.githubusercontent.com/assets/16597449/12218538/7db71126-b722-11e5-9576-d0377c23e75b.JPG)
And it only suppose to index pages in home/videos like here:

![capture](https://cloud.githubusercontent.com/assets/16597449/12218528/37718002-b722-11e5-981e-425e9e284729.JPG)

And I add it for now as:  "local contect index slide shows" wat seem to kinda work now:

![capture3](https://cloud.githubusercontent.com/assets/16597449/12218546/b2f353cc-b722-11e5-90b1-1c03c9cd611a.JPG)

which now should index this folder:

![capture2](https://cloud.githubusercontent.com/assets/16597449/12218548/ce140a52-b722-11e5-8694-577094c83b76.JPG)

Why, does is show all my files? it will not limit the index just to the video folder.
This is the video content, but its also showing my guild page:

![capture4](https://cloud.githubusercontent.com/assets/16597449/12218549/eba0939c-b722-11e5-9fa8-8d358ed8a574.JPG)

even do its located not in the video folder but here:

![capture5](https://cloud.githubusercontent.com/assets/16597449/12218560/1ff941f2-b723-11e5-9f9f-45c58e0f7922.JPG)

Now either I'm  misunderstand how this suppose to work or is there something wrong to?
I mean.. it should only show the pages in the video folder?? really at a los here.

regards

**Comment by mattlevine** [comment]
You would need to remove the current display object assignment and add it back once more.

**Comment by 2species5618** [comment]
hi,

this for the "standard Local Content Indexes" you are referring?
Than I already done this and i just did it again, its not helping:

![this](https://cloud.githubusercontent.com/assets/16597449/12219391/5fcc7538-b741-11e5-85cc-5fa435530bff.JPG)

Just to be sure I also created a new collection and added that to the homepage. its unfortionally also not working.

It only kinda works if I make it a slideshow type, but then the directory filter is not working and it will show all items in all directories (like I showed in the prev message), I just tested that  again to, same results.

the only extra error I could find is this:
![error-new](https://cloud.githubusercontent.com/assets/16597449/12219436/798fd6a2-b743-11e5-8e63-f4e7122d5d7d.JPG)


regards,

**Comment by mattlevine** [comment]
I'm not sure why that's happening.  I can't reproduce this issue locally.  What happens when you click the rss link for the collection in the admin?

Are you able to provide me with access to see this first hand?  You could send info to matt.levine@blueriver.com

**Comment by 2species5618** [comment]
Hi,
Ok that strange, maybe the issue is in my site or setup.
Ill contact you tomorow because its very late here now. Remote contact might be possible by using teamviewer as vpn on the cisco router is currently disabled.
Ill test your request tomorow and post the results. Ill also do some other test myself.
Untill tomorow.
Regards,



Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Matt Levine <notifications@github.com>
Datum: 10-01-2016  03:17  (GMT+01:00)
Aan: blueriver/MuraCMS <MuraCMS@noreply.github.com>
Cc: 2species5618 <im_weasel1@hotmail.com>
Onderwerp: Re: [MuraCMS] Content Collections , folder do not show up when finding section for local index (#2044)

I'm not sure why that's happening.  I can't reproduce this issue locally.  What happens when you click the rss link for the collection in the admin?

Are you able to provide me with access to see this first hand?  You could send info to matt.levine@blueriver.com

---

**Comment by 2species5618** [comment]
HI the rss feed seems tobe working.


![rss-feed](https://cloud.githubusercontent.com/assets/16597449/12223349/cd629116-b7d4-11e5-9ed0-afa5cc67d94f.JPG)

Ill send rdp connection info to you.
let me know when you connect so I can view along and assist you.

**Comment by mattlevine** [comment]
Please reopen it still an issue.
