### ISSUE TITLE
Wrong dsp_category_summary.cfm file used 

### ISSUE THREAD

**Issue by damienbkx** [blueriver/MuraCMS#2050]
Hi, 
I have a `dsp_category_summary.cfm` file situated in the `/{sited}/includes/themes/display_objects/` folder, but the file situated in the default `/{sited}/disaplay_objects` folder is used instead.

This only occurs with that file (I also have other .cfm files in my `/{sited}/includes/themes/display_objects/` that work just fine) and I have double / triple /quadruple check the spelling of the file name which is OK.

Also, when logged in as administrator in the front end, the `dsp_category_summary.cfm` is shown as an editable block (with a pencil in the bottom right corner) as tough it shouldn't (because it is not editable...)

Can't put my head around that one...  Anyone?

**Comment by howellcc** [comment]
Just a point of clarification, is your dsp_category_summary.cfm located in /{sited}/includes/themes/display_objects/ as you've stated, or in /{sited}/includes/themes/{theme}/display_objects/ as it should be?

**Comment by damienbkx** [comment]
`/{sited}/includes/themes/{theme}/display_objects/` Where it should be (sorry for the confusion).
The funny thing is that it used to work fine, but I found out yesterday that it is not working anymore. (you can see for yourself on the following page http://en.didaxo.be/news/ where the Categories block is supposed to have the same formatting as the Archive block below).

Thanks

**Comment by mattlevine** [comment]
So just to clarify, you added a display object override in your theme and it's not bing found?  Can you reload your Mura instance and see if the the file is found in the new location?

**Comment by damienbkx** [comment]
Yes Matt, That's exactly it.

Reloading the Mura instance did not change anything. 
Actually, when troubleshooting this issue, I've installed a new Mura instance on my local computer (a brand new iMac) and made sure to use the same version as on my production site (latest version - 6.2.6502 for both core and site). I then created a site bundle from my production site aredeploy it on my local instance with the same effect. The `/{sited}/includes/themes/{theme}/display_objects/dsp_category_summary.cfm`is not picked up and the system uses the default `/{sited}/display_objects/dsp_category_summary.cfm` instead.

The weird thing is that the other overrides all work fine.

**Comment by mattlevine** [comment]
You have this file with theme same content?

https://github.com/blueriver/MuraCMS/blob/develop/admin/core/views/carch/objectclass/category_summary/config.xml.cfm

**Comment by damienbkx** [comment]
Yes, the file is present with that very content on both local and production instance in /admin/core/views/carch/objectclass/category_summary/config.xml.cfm.  Should it be elewhere also?

**Comment by mattlevine** [comment]
Please update your core and retest.

**Comment by damienbkx** [comment]
It works Thanks.
Good day to you!
