### ISSUE TITLE
missing template call in dsp_search_results.cfm on line 139

### ISSUE THREAD

**Issue by scottkroyer** [blueriver/MuraCMS#2081]
Hello!

\www\adminHelp\includes\display_objects\custom\dsp_search_results.cfm
has an incorrectly referenced template path on line 139:
The code is currently
&lang;cfmodule template="nav/dsp_tag_line.cfm" ...&rang;
but should be changed to
&lang;cfmodule template="**../**nav/dsp_tag_line.cfm" ...&rang;

nav/dsp_tag_line.cfm is at a higher level of the hierarchy than the calling template. It's not a child folder as the path would imply.

Sorry, I don't know what causes that version of dsp_search_results.cfm to be used so I can't provide instructions on reproducing the problem. Luckily the syntax problem is easily identifiable and verifiable. Hopefully that is enough.
Thanks!

**Comment by mattlevine** [comment]
Thanks for point that out.  The call to cf_module is no longer a part of Mura's dso_search_results.cfm, but it's good know that the issue previously existed in case others run into it.
