### ISSUE TITLE
getImageURL() bug when using undefined image size

### ISSUE THREAD

**Issue by petrichor8** [blueriver/MuraCMS#2114]
When using the calls

`$.content().getImageURL(size='large')`
`$.content().getImageURL(size='small')`

I get the following return strings:

`/default/cache/file/57D40284-DED6-7F92-04AA43D141B302BF.jpg`
`/default/cache/file/57D40284-DED6-7F92-04AA43D141B302BF_small.jpg`

However, when I use the call with an **undefined ** custom size, I get a url that is invalid & contains a complete file path within it:

`$.content().getImageURL(size='iamnotarealboy')`

returns:

`/default/cache/file/C:\path\to\file\on\server/default/cache/file/57D40284-DED6-7F92-04AA43D141B302BF_small.jpg`

Mura is version 

> site 6.2.6457
> core 6.2.6464

Is this a bug that's been fixed/looked at?
I think it's in `/requirements/mura/content/file/fileManager.cfc :: 795`
or possibly in `/requirements/mura/content/file/processImgCfimage.cfc :: 92`

**Comment by andrew-dixon** [comment]
@petrichor8 - I've seen this before as well and I thought I had raised it with BlueRiver via the professional support but I can't see the ticket, so I'm not sure I ever actually did, but it is definitely a bug.

**Comment by mattlevine** [comment]
What would you guys want to happen when an undefined image is called?  Should throw an error?  Return an empty string?

**Comment by petrichor8** [comment]
Well, in my case, I'm checking to see if the call returns a string with len(), and depending, process different paths, so I would say 'empty string', since I'm explicitly calling for an image size, and if it's not defined, I would want to know, not just have it filled in with something, which would be hard to check if it's actually the image I wanted, and not a default one that's filled in because I didn't define the custom image size.

Ultimately, no matter what is returned, it shouldn't have the path to the webroot in it.

**Comment by petrichor8** [comment]
`$.getImageURL(size='iamnotarealfilesize')`

still returns 

`'/default/cache/file/'`

This fixes the call so that it truly returns an empty string

https://github.com/blueriver/MuraCMS/pull/2126

**Comment by mattlevine** [comment]
Thanks, would you mind signing a contributor agreement?

https://github.com/blueriver/MuraCMS/blob/develop/Mura_CMS_contribution_agreement.pdf

**Comment by mattlevine** [comment]
I manually added the fix.  Thanks!

**Comment by petrichor8** [comment]
just saw this, i'm running by legal as a cya.  what should I do with it after signing?
