### ISSUE TITLE
Status of Email Broadcaster

### ISSUE THREAD

**Issue by rwatts3** [blueriver/MuraCMS#2169]
Greetings,

I believe it was mentioned whether or not the Email Broadcaster would be deprecated in Mura 7.
Was their a final decision as to it's deprecation? Also if the Email Broadcaster is to be deprecated,
will it be released as a plugin, and if not could you point me in the right direction as to how I would convert it into a plugin. 

Thank you, 

Ryan.

**Comment by mattlevine** [comment]
The current thinking is that we're going to still include it in Mura 7 as a deprecated module to give us and the community time to figure out how to approach this issue.  But honestly if there were a group of developers to rally around the module it could probably remain in the core.  We (blue river) don't really use it that much.  But everyone once in a while it's nice to have.

-Matt

**Comment by rwatts3** [comment]
Thank you , that makes perfect sense to me.

**Comment by CatherineMortali** [comment]
Great. About 80% of my sites do use it (and frequently). Thanks!

**Comment by rwatts3** [comment]
Is it safe to assume that the approach for building plugins is still the same as described in the Mura Backend Developers book? And with 6.2 or has this process changed with 7.0

**Comment by dnordyke** [comment]
If I've updated to v7, how do I get to the Email Broadcaster?  I'm not finding that module anymore.  Thank you.

**Comment by rwatts3** [comment]
Hi, @dnordyke 

I was able to enable it by following these steps : 

- In your settings.ini.cfm file set `emailbroadcaster=true`
- Then reinit application
- Next navigate to site settings and enable email broadcaster option.

**Comment by dnordyke** [comment]
Thank you @rwatts3 .  That worked!

**Comment by damienbkx** [comment]
Very sad to see Mailing list manager and eMail broadcaster deprecated, even though I certainly understand the thinking behind it. 
Nevertheless, I'm adding my voice for it to remain in the core.  I'm one of those users that make heavy use of it. It perfectly fit the current needs of my startup!
Thanks
