### ISSUE TITLE
JSON api error when saving a new entity.

### ISSUE THREAD

**Issue by rwatts3** [blueriver/MuraCMS#2191]
Greetings, 

I am attempting to follow the new pattern with the JSON Api, and mura.js. 
When I attempt to save an entity , generally testing through the console. For some reason I am receiving a 400 bad request error. When I review the network logs, I can see how the save method fails, but their are two additional requests in the network panel 1 for ?new and another for ?generateCSRSToken . The token is generated after the attempt to save fails. I'm not sure if I am approaching this wrong but any insight on syntax would be greatly appreciated. 

P.S. The method I used was in the mura.js file, where the tests are commented out. I tried each of those with no success "each as in saving entities".

Thank you,

**Comment by mattlevine** [comment]
Did you enable the JSON api in site settings?  I also recently made a tweak in Mura 7 that if the layout manager is enabled the JSON api is automatically enabled.

Can you post the script that you are using?

-Matt

**Comment by rwatts3** [comment]
Hi Matt, 

Yes I enabled the settings , note the option is only available in edit site upon creating a new site.
Afterwords if I go back and attempt to change or ensure the setting is enabled for the same site or an existing site, I do not see the option. 

Here is the script I am using, I used majority of it's structure from `mura.js` in the `src` directory. 

```js
mura.getEntity('content').set({
	parentid: '00000000000000000000000000000000001',
	approved:1,
	title: 'test 5'
}).save().then(function (item) {
	console.log(item.get('title'));
});
```

Thank you in advance.

**Comment by mattlevine** [comment]
Please update and retest.

**Comment by rwatts3** [comment]
Thank you !

**Comment by rwatts3** [comment]
Thanks Matt, that did the trick.
