### ISSUE TITLE
When is it safe to use Update Core in Mura 7

### ISSUE THREAD

**Issue by rwatts3** [blueriver/MuraCMS#2226]
Greetings,

I just want to check and see when or if it is currently safe to update Mura Core via the Dashboard, without mistakenly rolling back the site to 6.2. I have a client that will be launching soon on Mura 7 as a beta, and I just want to know when I can give them the go ahead to update Mura Core via the Dashboard , vs. Me updating via git pull on the server. 

thank you, 

Ryan

**Comment by nsollecito** [comment]
I believe if you have `autoupdatemode=preview` in your settings.ini then when it makes it to the develop branch it will be safe to use the updater
