### ISSUE TITLE
<li> elements on Gallery pages fail to have height set.

### ISSUE THREAD

**Issue by bradmarshall** [blueriver/MuraCMS#2255]
The gallery's display object has a javascript file (`gallery.js/gallery.min.js`) that attempts to read `mura.jslib` and for some reason that variable is not set in the mura object. The variable should determine whether the framework is using "jquery" or "prototype" so if it's not set, the gallery assumes prototype is in use and tries to read the height of all `<li>` elements using prototype's `getHeight()`. If one is using jquery, this fails and the li's don't get a height set.

Is mura.jslib still a thing? Or has that been deprecated?

**Comment by mattlevine** [comment]
Try manually updating these files:

https://github.com/blueriver/MuraCMS/tree/6.2/default/includes/display_objects/gallery/js

That was an old check for whether to use jquery or prototype.js.  I just removed it to always use jquery.

-Matt

**Comment by bradmarshall** [comment]
Ah, figured that might have been what happened. Replacing those two files resolves the issue for me. Thanks!
