### ISSUE TITLE
BACKGROUND COLOR SHADE is not a valid color - Mura 7

### ISSUE THREAD

**Issue by webdpro** [blueriver/MuraCMS#2265]
When trying to update the site setting in mura 7 I get an alert saying 'BACKGROUND COLOR SHADE is not a valid color." but I have no idea where this is or what it mean.

**Comment by webdpro** [comment]
So, I found the problem area.. It appears to be a bug of sorts with the mura player plugin. There is an option for 

MuraPlayer Lights Out Options

This defaults to a Hex value of #000000 but the system appears to want an RGB value, once navigating to this section it automatically updated it.

**Comment by aldoquispe** [comment]
Hello...
I have the same problem , please could you tell me that file is and how I make the change ?
Thank you...

**Comment by aldoquispe** [comment]
Hello...
I have the same problem , please could you tell me that file is and how I make the change ?
Thank you...

**Comment by rjovo** [comment]
You'll find the Background Color Shade setting In Site Settings, under Extended Attributes, MuraPlayer Lights Out Options.
