### ISSUE TITLE
Mura 7 - Cant find forms manager?

### ISSUE THREAD

**Issue by webdpro** [blueriver/MuraCMS#2266]
I  don't see any area where the forms manager might be,  have checked each drop down and validated its turned on in 'modules' but it does not display in the admin side.  ( this led me to find the forms manager bug with the alert ) when I tried to disable and re-enable it

**Comment by JonasEriksson** [comment]
Hi, you might have found it by now, but in case others stumble across this - it's located in the Content Manager - in a rather elegant menu (Site Tree - Compontents - Forms).

**Comment by mattlevine** [comment]
Thanks for pointing that out.  We'll ponder how to better communicate that.
