### ISSUE TITLE
Google sitemap plugin Mura - Exception in onRequest

### ISSUE THREAD

**Issue by webdpro** [blueriver/MuraCMS#2268]
The action process:main.default failed.

can't cast [useMuraDefault] to date value

(expression)

Exception
Struct
additional	
Struct
Detail	
string	
ErrNumber	
number	0
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	can't cast [useMuraDefault] to date value

**Comment by mattlevine** [comment]
Can't reproduce, may be a bug in the google sitemap plugin.
