### ISSUE TITLE
argument requirement bug in contentBean.cfc

### ISSUE THREAD

**Issue by mikechy** [blueriver/MuraCMS#2271]
This morning while attempting to import some language translations using the Translation plugin, we were getting an error when importing. After thwarting the error catching we discovered that it was "The PROPERTY parameter to the set function is required but was not passed in. " to the content bean setter.

The code in question was in the contentUtility.cfc line 1574:

```
`<cfset newContentBean = getBean('content') />
<cfset sArgs = duplicate(contentBean.getAllValues()) />
<cfset rsRelated = contentBean.getRelatedContentQuery() />

<cfset StructDelete(sArgs,"ContentHistID")/>
<cfset StructDelete(sArgs,"ContentID")/>
<cfset StructDelete(sArgs,"ParentID")/>
<cfset StructDelete(sArgs,"SiteID")/>
<cfset newContentBean.set( content=sArgs ) />`
```

You can see that it's calling the setter passing in content as an argument collection.  However, the setter it's calling on line 269 inside of contentBean.cfc looked like this:

```

<cffunction name="set" returnType="any" output="false" access="public">
    <cfargument name="property" required="true">
    <cfargument name="propertyValue" required="false">

    <cfif not isDefined('arguments.content')>
        <cfif isSimpleValue(arguments.property)>
            <cfreturn setValue(argumentCollection=arguments)>
        </cfif>

        <cfset arguments.content=arguments.property>
    </cfif>
```

The problem obviously is that it was _requiring_ the property argument.  We changed it to this:

```
<cffunction name="set" returnType="any" output="false" access="public">
    <cfargument name="property" required="false">
    <cfargument name="propertyValue" required="false">
    <cfargument name="content" required="false">
```

and it fixed the issue.  Also, I believe it's possible to toggle a setting in CF that required all arguments be defined in functions. 

Thanks

Mike Chytracek
mike@ignitesolutions.com

**Comment by mattlevine** [comment]
Try changing 

```
<cfset newContentBean.set( content=sArgs ) />`
```

to 

```
<cfset newContentBean.set( sArgs ) />`
```

and retest.

**Comment by mikechy** [comment]
Isn't the problem that "Property" is required in the "set" function and not being passed?

**Comment by mattlevine** [comment]
Just a s test please try what I posted.

**Comment by mikechy** [comment]
Ah, right.  "Property" actually gets pulled in from the bean.  Give me 5 minutes.

**Comment by mikechy** [comment]
Yes.  this works.  Thanks!

`<cfset newContentBean.set( sArgs ) />`
