### ISSUE TITLE
Mura 7.0.6728 - Bug Error Clearing Trash Bin

### ISSUE THREAD

**Issue by dbudde** [blueriver/MuraCMS#2272]
I am getting a transaction error when trying to delete content in the trash bin.  The error is attached.

Specs
Mura: 7.0.6575
OS:  Server 2008 R2
App:  Adobe CF11
DB:  PostgreSQL 9.4.4
[error.zip](https://github.com/blueriver/MuraCMS/files/271512/error.zip)

**Comment by dbudde** [comment]
I was finally able to figure out the problem with clearing out the trash bin.  There are currently deletes still present for the tables (tadplacements, tadplacementdetails, tadplacementcategoryassign, tadstats), which are not present in my install of Mura 7.  The delete statements are wrapped in try/catch statements, but since they still cause a DB error inside of the `<cftransaction>`, this causes the transaction to stop all execution after the error.  This is the behavior I am seeing with PostgreSQL, so I am not sure if other DBs have this problem or not.

So, proposed fixes would be:
1. Remove the delete statements if they are no longer needed.
2. Add table detection statements to verify the tables exist before executing deletes.

Additionally, I noticed the entire delete section of the empty() method in the trashManager.cfc is wrapped in a `<cftransaction>`.  I ran into a problem with this because I had an excessively large trash and without extending the timeout to a very large number I could never complete emptying the trash.  I would suggest changing the <cftransaction> location so that you can complete single item deletes and then if there is a failure due to a large amount of data being cleared, then the individual items will still remain removed and not rollback.

**Comment by dbudde** [comment]
Additional idea, you could use the 'dbUtility' to determine if the tables exist and then not perform the deletes if they do not, which means you won't have the try/catch and the transaction breaking.

**Comment by mattlevine** [comment]
Please update and retest. I just comment out the ad manager code since it's not been supported for about two years.

**Comment by dbudde** [comment]
That has fixed the issue.  I am also going to put in a request that you move the location of the <cftransaction> so it transacts on a per object removal if at all possible.  We have made a couple sites where we import a lot of content objects from another datasource and replace them on a regular basis.  This can make the trash bin get fairly large quickly and when the entire process is in a <cftransaction> it tends to timeout and not let us remove the old content.
