### ISSUE TITLE
Mura 7.0.6579 admin tries to load a non-existing css file 

### ISSUE THREAD

**Issue by JonasEriksson** [blueriver/MuraCMS#2274]
In admin/assets/css/admin.min.css it attempts to include _admin.min-blessed1.css?z=1443033573377_

![screenshot 2016-05-19 12 46 07](https://cloud.githubusercontent.com/assets/701938/15391135/ca0680b2-1dbf-11e6-9a3e-7ccf5cde77dd.png)

**Comment by JonasEriksson** [comment]
Interestingly even a fresh admin.min.css uploaded which does not have this reference at all, gets it injected. Where and why is this happening?

**Comment by mattlevine** [comment]
Are you making the  request to the Mura root?

**Comment by mattlevine** [comment]
Can you manually update this file and retest?

https://github.com/blueriver/MuraCMS/blob/develop/admin/assets/css/admin.min.css

What this auto updated or from a download?

-Matt

**Comment by JonasEriksson** [comment]
Thanks Matt, resolved now. To answer your question, it was a "fresh" downlaod (onto a Win2012 VPS/IIS/CF Enterprise 10) - I am not sure had happened there, but I ended up removing the site altogether from the Hostek WCP and re-added it, downloaded Mura 7.0.6579 from getmura.com/downloads/download-mura.cms again and then it ran without issues.
