### ISSUE TITLE
View Note not working

### ISSUE THREAD

**Issue by Oranuf** [blueriver/MuraCMS#2279]
Saved several drafts of a page; the version history page shows "view note" under the Notes column, but hovering or clicking does nothing.  When returning to a version that has a note, the notes do not appear in the field on the publishing tab as expected.  essentially, it appears that once Notes are added to a page object, they are stored but never to be seen again. =)

Have not checked for notes functionality on any other entities.

**Comment by gowestweb** [comment]
Thanks, I'll check this out. Feel free to add any add'l info.

**Comment by Oranuf** [comment]
It is my hope to become more and more involved as I get familiar with the Mura Way™, and help out with filing AND fixing bugs.  If you need ANY info, please don't hesitate to let me know.

**Comment by gowestweb** [comment]
This should be fixed (notes showing on hover) in the next update
