### ISSUE TITLE
Deploying site bundle end up in default account

### ISSUE THREAD

**Issue by Oranuf** [blueriver/MuraCMS#2289]
Scenario: 
Site under development locally, never been live.
Set up new Mura server
Created bundle on dev box.
Deployed to live box
Ended up with the bundle overwriting DEFAULT, instead of an account being created for it.

Didn't realize one must create the associated account first, before importing/deploying a site bundle.  HIGHLY recommend building in a restriction that simply won't allow deployment to the default site, since the best practice in the docs suggests that default might always be left alone (and since default is the core template from which new accounts are created).

**Comment by mattlevine** [comment]
We'll consider that for the future.
