### ISSUE TITLE
Element BEANNAME is undefined in ARGUMENTS. 

### ISSUE THREAD

**Issue by wiredmonkey** [blueriver/MuraCMS#2291]
Hi

I'm running into an issue on 6.2.6543 where I get the following error when I try to save a userbean:

Element BEANNAME is undefined in ARGUMENTS. 

Here is an example of my code:

`var userBean=arguments.rc.$.getBean('user').loadBy(userId=rc.uni_c_id);
userBean.setValue('fname',rc.fname);
userBean.setValue('lname',rc.lname);
userBean.setValue('email',rc.email);
userBean.setValue('mobilephone',rc.mobile);
userBean.setValue('uni_c_phone',rc.phone);
userBean.setValue('username',rc.email);
results=userBean.save();`

It was working before I updated. Any help or advice appreciated!

Cheers

Shaun

**Comment by mattlevine** [comment]
Can you provide the full stack trace?  You can enable robust error exceptions in the cf admin or I think the exceptions log may have more info.

-Matt

**Comment by wiredmonkey** [comment]
![error](https://cloud.githubusercontent.com/assets/950788/15709319/f9022768-27fb-11e6-9beb-35ad61fe8fc4.gif)

**Comment by wiredmonkey** [comment]
Let me know if you need more info. Thanks.

Shaun

**Comment by mattlevine** [comment]
I'm a little stumped.  I would do a manual core update.

1. Back everything up.
2. Download the latest Mura Standard or the 6.2 branch on github.
3. Unzip the downloaded Mura zip and copy the following directories into your Mura root

/admin/
/config/
/requirements/
/index.cfm
/Application.cfc

Copy the /config/settings.ini.cfm from you back up and place it into your updated /config/ directory

In the browser make a call to you Mura root with you appreload key in the url.  Normally it's ?appreload.

At that point it the problem still exists I may need access to get an idea about what's going on.

-Matt

**Comment by wiredmonkey** [comment]
Thanks Matt. That seems to have done the trick. I was stumped myself.

Thanks again.

Shaun
