### ISSUE TITLE
FEATURE REQUEST:  Show only content for which user has permission

### ISSUE THREAD

**Issue by Oranuf** [blueriver/MuraCMS#2292]
Just wondering how difficult it would be to allow a user to see in the Content Manager tree/flat view only that content they are permitted to author or edit.  Would save for some confusion and allow for an uncluttered workspace for those responsible for just one node or set of pages.

**Comment by mattlevine** [comment]
If the content is under a password protected section of the site the site manager will hide content that you do not have access to read.
