### ISSUE TITLE
Critical:  Tabs no longer available

### ISSUE THREAD

**Issue by Oranuf** [blueriver/MuraCMS#2297]
After a recent core update, when editing any object, admin tabs that end up hidden due to browser width restrictions are no longer available in the drop-down button that appears.

OS X El Cap, Apache/MySQL/Lucee, Mura 7.

**Comment by mattlevine** [comment]
Do you not see the arrow at the end of the tab list?  It's a drop down to access the other tabs.

**Comment by Oranuf** [comment]
Yes, the arrow is there, and used to work. Now clicking it does not reveal 
the hidden tabs. When I view source i cannot even see the LI tags/elements 
that would be hidden, it's like they are removed from the DOM altogether. 

Sent from my Android phone using Symantec TouchDown (www.symantec.com)

-----Original Message-----

**Comment by mattlevine** [comment]
Please update your core and retest.

-Matt

**Comment by Oranuf** [comment]
Looks like it’s working now – good work

 

Marc Funaro

 <http://www.advantex.net/> Advantex LLC

607-336-6895

**Comment by Oranuf** [comment]
Since I (might) have your eyeballs for a second… I’m still having trouble with the choices I’m making on the List Display Options tab not being reflected in the actual listing.  Not using any custom / extended classes of any kind for the folder; only one extended attribute for the items within the folder, but even when I remove that from the list of Selected Fields the result is the same – just the default listing format (Date, Title, Summary if available).  Let me know if there’s someplace I should poke around… but as it stands now, I put a CFDUMP of objectParams in the default {siteId}\includes\display_objects\collection\includes\index.cfm file, and the values are not what are selected for the folder in the UI…. Chose maximum of 3, but maxitems=4; the displaylist variable is not the same as the items I chose in the UI, etc.

 

If I can troubleshoot further in any way, let me know of course.

 

Marc Funaro

 <http://www.advantex.net/> Advantex LLC

607-336-6895

**Comment by mattlevine** [comment]
I have not been able to reproduce that issue yet.  I'm going to pull down and test with the foundation them later today.  If you can give me ftp and Mura super user access to where it's happening it would be great.

Also, please don't cross post on github tickets.

Thanks,
-Matt

**Comment by Oranuf** [comment]
sorry, new to github and didn't realize my replied via email were ending up here.  I can create a new ticket if you like.

**Comment by Oranuf** [comment]
Turns out after either last night or this morning’s update, the tabbed dialog boxes now look like this – not sure if related to the issue that was fixed under this ticket, but likely.

 

 



 

Marc Funaro

 <http://www.advantex.net/> Advantex LLC

607-336-6895
