### ISSUE TITLE
UX:  Canceling dialog loses work

### ISSUE THREAD

**Issue by Oranuf** [blueriver/MuraCMS#2299]
Just started using Layout Manager again. When editing a page, if user makes a change and then clicks on something that would cause the page to reload or change, they are (rightfully) prompted with a dialog box asking if they wish to save their changes as a draft ( [cancel] [ok] ).  

The user might expect "cancel" to cause the original action - whatever caused the page to reload/change - to be canceled.  Instead, it cancels out of the prompt only, and redirects the page, causing the user to lose any work they had done.

If not possible to intercept whatever was causing the page to change, the dialog box could add text that indicated that hitting cancel WILL cause all work to be lost, and or a second alert asking "are you sure?" could be thrown.

**Comment by mattlevine** [comment]
I added a second prompt to double check.
