### ISSUE TITLE
M7 - Ability to 'cancel' save draft dialog

### ISSUE THREAD

**Issue by ronnieduke** [blueriver/MuraCMS#2319]
When you make edits to a page, then navigate away, you are prompted with a save draft dialog. It would be good to have a way to "cancel" that dialog and return to editing the page, instead of just "yes or no". 

The use case would be anytime you accidentally navigate away, you could simply exit the dialog and continue editing rather than have to save a draft, and return to that page from the site manager.

![image](https://cloud.githubusercontent.com/assets/742579/16238606/df3c2dde-3795-11e6-8346-41460bb488cb.png)

**Comment by mattlevine** [comment]
It's still there, it's just not visible.  It should be fixed soon

**Comment by ronnieduke** [comment]
Ah, yeah I see it in the markup now. Thanks!
