### ISSUE TITLE
7.0.6623 - Site Settings - IMAGES - Add Custom Image Size : new size is not saved (in FF and Chrome)

### ISSUE THREAD

**Issue by JonasEriksson** [blueriver/MuraCMS#2328]
![screenshot 2016-06-23 21 43 29](https://cloud.githubusercontent.com/assets/701938/16317465/8ce9280a-398b-11e6-9018-e36c1f1b4c34.png)
![screenshot 2016-06-23 21 43 34](https://cloud.githubusercontent.com/assets/701938/16317469/90f2d388-398b-11e6-9044-c31e3baaf47e.png)

**Comment by mattlevine** [comment]
I put up a fix for the functional aspect, but the UI will be cleaned up soon as well.

**Comment by JonasEriksson** [comment]
Thank you Matt! Confirming it now works fine in 7.0.6625 (using Chrome browser, M7 on Lucee 4.5 server w MySQL 5.7).
