### ISSUE TITLE
[Mura 7] Edit Site Tab Display Issues

### ISSUE THREAD

**Issue by brucebailey** [blueriver/MuraCMS#2330]
OSX and Firefox Display Issue

![screen shot 2016-06-24 at 9 55 28 am](https://cloud.githubusercontent.com/assets/913250/16339877/0bfba6d8-39f3-11e6-96a5-fb5da7d282d6.png)

**Comment by gowestweb** [comment]
We fixed this yesterday, thanks. It will be in the next update to Mura 7. (Was a simple CSS float issue)

**Comment by Oranuf** [comment]
can i just say a big thank you for fixing this! =D  I reported it quite some time ago but it took some time to realize it was browser specific.
