### ISSUE TITLE
Mura 7 - Bug in frontend (touch event) in mura.js

### ISSUE THREAD

**Issue by neoplay** [blueriver/MuraCMS#2338]
There seems to be a small but significant bug in the javascript of the frontend.

Everytime i **touch** a link (f.ex. in the navigation) on the **iPhone** screen and **try to scroll** down, the link will be clicked and i am not able to scroll down the page.

This is triggered by dispatching a new mouse event on every link i touch on the page.

I think this has to be limited to a class or attribute of the specific links where this is needed.

Located at:
js/dist/mura.js, Line 540

`function touchstart(evt) {
    var el = evt.target;
    do {
      if (el.draggable === true) {
        // If draggable isn't explicitly set for anchors, then simulate a click event.
        // Otherwise plain old vanilla links will stop working.
        // https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events#Handling_clicks
        if (!el.hasAttribute("draggable") && el.tagName.toLowerCase() == "a") {
          var clickEvt = document.createEvent("MouseEvents");
          clickEvt.initMouseEvent("click", true, true, el.ownerDocument.defaultView, 1,
            evt.screenX, evt.screenY, evt.clientX, evt.clientY,
            evt.ctrlKey, evt.altKey, evt.shiftKey, evt.metaKey, 0, null);
          el.dispatchEvent(clickEvt);
          log("Simulating click to anchor");
        }
        evt.preventDefault();
        new DragDrop(evt,el);
      }
    } while((el = el.parentNode) && el !== doc.body);
  }`

Here is a demo (default template):
[mura7demo.nextron.net](http://mura7demo.nextron.net/)

**Comment by mattlevine** [comment]
This should be fixed now. The IOS drag and drop shim is no longer in the base mura.js.  It gets loaded when clicking to use the front end layout manager.  In addition I tweaked the logic to only allow the  default event to fire for links if it was not dragged.
