### ISSUE TITLE
Use SSL Sitewide doesn't apply to admin

### ISSUE THREAD

**Issue by Squeebly-Joe** [blueriver/MuraCMS#2342]
Selecting Use SSL Sitewide in the site settings does not apply to the admin. You can still access the admin over standard http instead of being redirected to a secure URL.

**Comment by nsollecito** [comment]
The site config setting is only for front-end. 

To force HTTPS for the admin, use adminssl=1 in your settings.ini.cfm

**Comment by mattlevine** [comment]
Nick is correct.  

thanks,
-Matt
