### ISSUE TITLE
Mura 7 ?display=editprofile not showing validation errors

### ISSUE THREAD

**Issue by robrohan** [blueriver/MuraCMS#2356]
Mura 7.0.6646
**issue**
When using 'the front end' version of the default edit profile screen, validation rules prevent the form from saving data as they should, but the validation error messages don't display / don't exist.  However, the backend version of edit user profile behaves as expected.

**recreate**
To recreate, enable strong passwords or setup something like:

```coldfusion
<cffunction name="onBeforeUserSave" access="public" output="false">
		<cfargument name="$">
		<cfargument name="event">
		<cfset local.user = arguments.event.getValue('userbean')>
		<cfset local.user.getErrors()['herp'] = 'derp'>			
</cffunction>
```

Then go to http://localhost/?display=editprofile, make the input invalid, and submit.

**expected**
Validation failure reasons available in: `request.userBean.getErrors()` 

**actual**
The form refreshes with values unsaved and no errors are displayed.

**cause**
What I think is happening: it looks as though all the validation is working correctly and the error values are being set correctly on the userBean see and dump here https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/Handler/standardEventsHandler.cfc#L549 

However, it looks as though the front end editprofile form uses an ajax form and I think what is happening is after the form validation happens, the request is redirected to a new URL and therefore a new userBean is being loaded from the database to display the form again.  This, in effect, removes the errors as I assume the error key isn't persisted to the database.

I do not know enough about mura to offer a patch or fix.

For anyone else hitting this bug, as horrible work around we've put the error's text into the session and used that to display on the invalid editprofile page.  It would be better not to need to do that obviously.

**Comment by mattlevine** [comment]
I forgot to tag this ticket but the fix is in this commit

https://github.com/blueriver/MuraCMS/commit/064426174c685b8ae365474623a922f8860e0d5d

**Comment by robrohan** [comment]
Legend!
