### ISSUE TITLE
Add SVG to list of allowed file types in CKFinder

### ISSUE THREAD

**Issue by bradmarshall** [blueriver/MuraCMS#2359]
My team uses SVG extensively in our Mura sites - it would awesome if we could upload SVG files to the CKFinder. This would let us embed them in HTML `img` elements in content nodes, components, etc without having to use bitmap graphics, which often look blurry on mobile.

**Comment by nsollecito** [comment]
FYI, you can override the default allowed file extensions by adding the key fmAllowedExtensions and desired values to your config/settings.ini.cfm file

`fmAllowedExtensions=7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,ppsx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,xml,zip,m4v,less,html,json,js,css,eot,svg,ttf,woff,otf`

**Comment by bradmarshall** [comment]
Hmm.. I tried that and it didn't work for some reason. I just tried it again and setting fmAllowedExtensions seems to allow SVG's in the CKFinder if you launch it via Modules -> File Manager. But what I was trying was adding an image to the _CKEditor_ and then choosing Browse Server and uploading my image from there. Uploading an SVG still fails in that scenario, even with the custom setting. I'm not sure why that is.

Thanks for the tip - this gets me closer but it still would be nice if Mura supported SVG's without any additional config.

**Comment by bradmarshall** [comment]
Ah just saw Matt's commit - great turnaround time! Thanks a ton! 👍

**Comment by nsollecito** [comment]
Hmm, yah.. this had worked for us in Finder but maybe CKEditor is using different settings. 
  
SVG should probably be a default file ext anyway as they seem to be getting more and more common. Glad it's sorted!

**Comment by bradmarshall** [comment]
I just added `svg` to my `config.defaultAlledExtensions` just like in Matt's commit and now I can upload to both places just fine. I actually tried this earlier too so I don't know why I couldn't see it take effect then. Maybe I hit a caching issue or didn't app reload correctly. Anyways, this is fantastic. Thanks again!

**Comment by bradmarshall** [comment]
Actually I was mistaken once more. However I was able to add `svg` to `config.resourceType[2].allowedExtensions` in requirements/ckfinder/config.cfm. Not sure if that's the most appropriate change or not but it did allow uploading SVG via the CKEditor.
