### ISSUE TITLE
Improvement: 'View' option in content manager

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2361]
In the new content manager, the 'view' button is hidden away under the pop up menu.

Given that we have the revised method of adding content objects to the pages via the front end,  this can make the process of getting from the admin to the front end pretty frustratingly slow.

So... I suggest (and I know you want to keep it uncluttered) adding a 'View' button alongside the 'Objects' icon.

Thanks!

Peter.

**Comment by mattlevine** [comment]
Thanks for the feedback.   There are still a few refinements coming. However, I think the site manager may get a bigger overhaul in 7.1 to address these kind of issues.

-Matt
