### ISSUE TITLE
Mura 7 Error on Fresh install : Creates /var/www folder inside directory

### ISSUE THREAD

**Issue by rwatts3** [blueriver/MuraCMS#2372]
Using a fresh git clone mura throws a 500 error and never completes the install process ..

```
Page /muraWRM/config/appcfc/onApplicationStart_include.cfm [/var/www/var/www/muraWRM/config/appcfc/onApplicationStart_include.cfm] not found 
```

**Comment by mattlevine** [comment]
Can you comment out this line and retest

https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm#L129

**Comment by rwatts3** [comment]
Thanks for the fast reply.
I commented out that line and received the same error.

**Comment by mattlevine** [comment]
Please manually update this file and retest

https://github.com/blueriver/MuraCMS/commit/707eb36a2e265d7fcc27f262cfd9c255793734da

**Comment by mattlevine** [comment]
Please update this file as well
https://github.com/blueriver/MuraCMS/blob/develop/config/applicationSettings.cfm

**Comment by rwatts3** [comment]
Thank you , 

working on the second one now

**Comment by mattlevine** [comment]
How did it go?

**Comment by rwatts3** [comment]
Hi Matt that worked ,

Thank you.

Ill try to add another site brand new to be sure but those corrections
seemed to do the trick
