### ISSUE TITLE
BUG:  Featuring content in category breaks publishing

### ISSUE THREAD

**Issue by Oranuf** [blueriver/MuraCMS#2374]
To reproduce:
1. create one or more categories
2. create a page to place in a category
3. on category tab, place the page in a category
4. on that same category, click "featured" and choose yes
5. click publish.

On my system, the clicking of Publish simply stalls, with a "please wait" spinner.  When observing these steps in Firebug Network Panel, it appears that when clicking publish, no call is ever made to the server at all.

Client: Mac OS X El Capitan, Mozilla FIrefox 47.0.1
Server OS Version Linux (2.6.32-642.el6.x86_64)
Java Version 1.8.0_92
App Server Lucee (5.0.0.252)
DB Server MySQL (5.5.5-10.1.16-MariaDB)
Mura Core Version 7.0. 6703
Mura Site Version 7.0. 6703

**Comment by shawna-mura** [comment]
This issue has been resolved.
