### ISSUE TITLE
[Mura 7] Forms built with form builder no longer show up

### ISSUE THREAD

**Issue by Tigerlady** [blueriver/MuraCMS#2377]
I just updated my core and site files to 7.0.6704 and none of the forms build with the form builder are showing up on the pages.  Here is proof that the form should be there. but it doesen't show up with viewing the site.  All other forms built manually are showing up. 

![displaypage-soundoff](https://cloud.githubusercontent.com/assets/1850313/17121321/8062336c-5298-11e6-8acf-a4dd2826e3d7.jpg)
![sound-off-page-edit](https://cloud.githubusercontent.com/assets/1850313/17121322/806cafae-5298-11e6-8703-badba3d7e761.jpg)
![soundoff-form-builder](https://cloud.githubusercontent.com/assets/1850313/17121323/807966e0-5298-11e6-9fef-301d19a5f4b0.jpg)

**Comment by chid** [comment]
Sounds like this issue https://github.com/blueriver/MuraCMS/issues/2366#issuecomment-233835739

**Comment by Tigerlady** [comment]
I do not think so.  I checked our server web.xml file and those lines do exist.  Also I have other sites running an older version of 7 on the same instance of Lucee and it's forms are working. 

Here is the version that the forms are working 

![2016-08-01_08-25-47-working](https://cloud.githubusercontent.com/assets/1850313/17295466/de65bd16-57c1-11e6-9a25-dfa8885cdcb4.jpg)

And here is the version that isn't working.  

![2016-08-01_08-26-11-not-working](https://cloud.githubusercontent.com/assets/1850313/17295476/ec8bd740-57c1-11e6-9d48-676cdc32ee99.jpg)

They both run on the same instance of Lucee.

**Comment by Tigerlady** [comment]
I also just updated the site that wasn't working the core and the site and it still is not working. 

![2016-08-01_08-31-27-still-not-working](https://cloud.githubusercontent.com/assets/1850313/17295591/7a85c8f8-57c2-11e6-8409-12f9db54fffc.jpg)
