### ISSUE TITLE
Copy/Paste broken

### ISSUE THREAD

**Issue by Oranuf** [blueriver/MuraCMS#2379]
Client: Mac OS X El Capitan, Mozilla FIrefox 47.0.1
Server OS Version Linux (2.6.32-642.el6.x86_64)
Java Version 1.8.0_92
App Server Lucee (5.0.0.252)
DB Server MySQL (5.5.5-10.1.16-MariaDB)
Mura Core Version 7.0. 6707
Mura Site Version 7.0. 6707

In admin > Content

I am under a folder, and want to copy an object and paste it in the same folder as a copy to be modified.  I choose "copy" from the object's menu, then go to the folder's menu and choose "paste" - and get nothing but the Please Wait spinner forever.

It is possible i'm misusing the feature, but the copy/paste paradigm would dictate that this would be a normal thing to do.

**Comment by mattlevine** [comment]
It's working in my tests.  Can you enable your Chrome debugger and post any 500 error you are getting under the debugger's network tab.  As well as any console errors.

**Comment by Oranuf** [comment]
well, i feel like an a$$.  My plugin had a misspelled method name being called during the onBeforeContentSave() event.  My sincere apologies for wasting your time.  =(
