### ISSUE TITLE
[BUG] - [Mura 7] - Additional Titles

### ISSUE THREAD

**Issue by Zandoh** [blueriver/MuraCMS#2386]
When publishing a page all of the titles in 'Additional Titles' become 'title, title' instead of just 'title'. This is for all 3 of the additional titles which causes a database error where the title becomes too long
![mura_title_bug](https://cloud.githubusercontent.com/assets/15444867/17295490/5f72bb72-57ca-11e6-8986-f21c668382df.png)

**Comment by gowestweb** [comment]
Thanks for reporting this, we'll check into it.

**Comment by gowestweb** [comment]
Zach, are you still having this issue? (If so, in what browser/platform? Also , was this a new installation or a 6.2 --> 7 upgrade? )    I am unable to reproduce it locally.

**Comment by Zandoh** [comment]
Deleted version file, updated site and core. Fixed the issue

**Comment by gowestweb** [comment]
Great thanks for the update.
