### ISSUE TITLE
UI: Does not remain zoomed after adding content

### ISSUE THREAD

**Issue by Oranuf** [blueriver/MuraCMS#2389]
To reproduce:

Load Mura backend admin
Zoom a content folder/object
Click the menu to the left of the object and choose Add Content
Add a content item
Upon saving, the content folder you zoomed is no longer zoomed.

Results in multiple steps in the user experience to then zoom back into the folder if manually sorting items in that folder.  Repetitive and time consuming when adding many content items.  Zoom should remain zoomed until cleared by another zoom or a click on the top level folder.

Client: Mac OS X El Capitan, Mozilla FIrefox 47.0.1
Server OS Version Linux (2.6.32-642.el6.x86_64)
Java Version 1.8.0_92
App Server Lucee (5.0.0.252)
DB Server MySQL (5.5.5-10.1.16-MariaDB)
Mura Core Version 7.0. 6707
Mura Site Version 7.0. 6707

**Comment by gowestweb** [comment]
I can reproduce this in Firefox but not in Chrome. We'll see what's going on , thanks for reporting it.

**Comment by mattlevine** [comment]
When you say that content folder is no longer zoomed, do you mean it has zoomed all the way back out to the home page?

**Comment by Oranuf** [comment]
Would have to test, but I believe it was zooming all the way out to the top level directory.  If not, it was definitely at least one directory up.

 

Marc Funaro

 <http://www.advantex.net/> Advantex LLC

607-336-6895
