### ISSUE TITLE
Long list of pages crops off menu at bottom

### ISSUE THREAD

**Issue by Tigerlady** [blueriver/MuraCMS#2390]
Ok so this is a bit difficult to explain so a picture is worth a thousand words.  If you look at the image below the delete option is hidden by the footer copyright.  I am scrolled all the way down I want to delete the item but the option to do so is hidden.  

Thanks. 

![bottom-menu-missing](https://cloud.githubusercontent.com/assets/1850313/17493181/d1c177ea-5d74-11e6-8329-0da3f9fa2bc3.jpg)

**Comment by gowestweb** [comment]
This should have been patched in one of the most recent updates. Try updating core files and shift+refresh to force the browser to see the new admin CSS.

**Comment by Tigerlady** [comment]
This is fixed thanks.
