### ISSUE TITLE
Mura 7.0.6719 Bug feedGateway

### ISSUE THREAD

**Issue by dbudde** [blueriver/MuraCMS#2399]
We noticed a couple days ago that our category based searches that were using more than 1 category started breaking.  I tracked the bug to line 739 in the feedGateway.cfc.  The code currently looks like:

`<cfif c lt categoryLen> or </cfif>`

And it looks like it should be:

`<cfif c lt paramCatLen> or </cfif>`

Hope this helps,

Daniel

**Comment by mattlevine** [comment]
I missed this ticket, but here's the commit.  Will be pushing through to master in a bit

https://github.com/blueriver/MuraCMS/commit/5412cbc566bf76c6a28cc3a50e9bb06b9e184645

Thanks for the help.
