### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by RejaurRahman** [blueriver/MuraCMS#2407]
Hi on version 7 how do I get the usage report for the contact form builder to be linked on a page. Not really clear on the videos or the documentation. Can you guide me, please?

Rejaur

**Comment by RejaurRahman** [comment]
Hi I updated the two files but that still not fix the problem of linking the page to the form on the usage report. How do I get it showing on the usgae report that the page is linked to the contact form. Rejaur

**Comment by mattlevine** [comment]
Did you drag the form onto a display region or onto the main content body?

**Comment by RejaurRahman** [comment]
If you mean adding the form in inline edit. I've tried that and it works, but I want to add it as an object on the page. 

With the theme came the information request form. i tried to create the contact form 'form'. 

![screen shot 2016-09-07 at 15 11 58](https://cloud.githubusercontent.com/assets/17392425/18315363/9d981148-750e-11e6-880d-dd5c4efc7e7b.png)

On Information Request form under Usage Report Tab it says it is displaying on the contact us page.

![screen shot 2016-09-07 at 15 12 24](https://cloud.githubusercontent.com/assets/17392425/18315407/d175530e-750e-11e6-9439-ee8236299fe6.png)

On the form I created which I named 'Contact Form', how do I get a page linked on Usage Report tab.

![screen shot 2016-09-07 at 15 12 49](https://cloud.githubusercontent.com/assets/17392425/18315436/eba0e7ac-750e-11e6-82a9-44844385d762.png)

Can you please guide here what to do?

Rejaur

**Comment by RejaurRahman** [comment]
I got this working by using the following code in the template - #$.dspObject('form' ,'Contact Form')#
