### ISSUE TITLE
[m7] v7.0.6730 mura.bean.beanRemotePointer.cfc  li 10 missing semicolon

### ISSUE THREAD

**Issue by encipherdesign** [blueriver/MuraCMS#2408]
after the last update, i'm getting the following errors: 
mura.bean.beanRemotePointer.cfc  li 10 missing semicolon;

20:16:09.009 - Template Exception - in /Users/Shared/_www/bp.dev/requirements/mura/bean/ioc.cfc : line 366
Invalid CFML construct found on line 11 at column 9.
20:16:09.009 - Application Exception - in mura.bean.beanRemotePointer) because: Invalid CFML construct found on line 11 at column 9. (ColdFusion was looking at the following text:
localObject.loadBy

The CFML compiler was processing : line -1

Unable to getComponentMetadata(mura.bean.beanRemotePointer) because: Invalid CFML construct found on line 11 at column 9. (ColdFusion was looking at the following text:
localObject.loadBy

The CFML compiler was processing:

A script statement beginning with var on line 10, column 9.
A script statement beginning with function on line 8, column 5.
)

**Comment by mattlevine** [comment]
This should no longer be an issue. Please reopen if it's still causing you a problem.
