### ISSUE TITLE
[m7] 7.0.6730 bug: /requirements/mura/dbUtility.cfc : line 524

### ISSUE THREAD

**Issue by encipherdesign** [blueriver/MuraCMS#2409]
after updating to the v 7.0.6730 & get this error:

```
20:31:55.055 - Database Exception - in ../requirements/mura/dbUtility.cfc : line 524
Error Executing Database Query.
```

i'm running:
CF 11,0,10,300066
Apache/2.4.18 (Unix) PHP/5.6.5 LibreSSL/2.2.7 mod_jk/1.2.41
mysql 5.7.10 

i've tried the url var 'dbapplyupdates' on appreload but still get the error.

**Comment by mattlevine** [comment]
Sorry for missing this one.  The url variable is not dbapplyupdates, it applydbupdates.  Is this still an issue for you?

**Comment by encipherdesign** [comment]
no worries. i've since updated to 7.0.6817 & don't see the error anymore… thanks
