### ISSUE TITLE
Mura 7.0.6733 - Bug Minor Visual Issue in Admin

### ISSUE THREAD

**Issue by dbudde** [blueriver/MuraCMS#2410]
I discovered a minor visual bug in the Mura admin.  I wrote up a description and attached images here.

[https://groups.google.com/forum/#!topic/mura-cms-developers/8cQy4AY8pjU](https://groups.google.com/forum/#!topic/mura-cms-developers/8cQy4AY8pjU)

**Comment by mattlevine** [comment]
I believe that this is fixed.  I can't reproduce the issue.  Please reopen if it's still happening for you.
