### ISSUE TITLE
Feature Request - Context Menu Screen Aware Position

### ISSUE THREAD

**Issue by dbudde** [blueriver/MuraCMS#2411]
The context menu for the admin content area does not appear to be screen position aware.  When it is near the bottom of the screen it goes off screen.  It would be nice if it stays on screen.  I have attached an example image demonstrating what is happening.

![bottom screen](https://cloud.githubusercontent.com/assets/6145877/18392183/75c0fc5c-7676-11e6-8d70-2da6227bfce2.png)

**Comment by gowestweb** [comment]
Are you updated to the latest version? This does need to be made position-aware, but I think we had a workaround in place as of a recent update. Thanks.

**Comment by dbudde** [comment]
Yes, I am on the latest build as of this morning.  I double checked just now and I still have this problem.  I am on the Mac OS 10.11.6 and I am using Google Chrome 52.0.2743.116.  Hope this is helpful.

**Comment by gowestweb** [comment]
In the current version (from before this issue was posted) there should be css in place to force a scrollbar when the new content menu drops below the bottom of the screen. 
![mura-overflow](https://cloud.githubusercontent.com/assets/1242989/18646768/14053a2e-7e81-11e6-8e98-235d89d6d799.jpg)

**Comment by dbudde** [comment]
It does force a scrollbar, but wouldn't be better to just position the menu so it does not go outside the viewport?
