### ISSUE TITLE
[mura 7] inline editor does not work over SSL with FireFox

### ISSUE THREAD

**Issue by tomchiverton** [blueriver/MuraCMS#2418]
There is a mixed content warning when dropping a component on a page in the inline editor that prevents it  working in FireFox.

**Comment by tomchiverton** [comment]
Mailing list thread with more details : https://groups.google.com/forum/#!topic/mura-cms-developers/834hGKJEGuE

**Comment by mattlevine** [comment]
Can you set your settings.ini.cfm admindomain property to the domain that your admin is using and adminssl to 1

admindomain=youradmindomain.com
adminssl=1

And reload and retest.

**Comment by tomchiverton** [comment]
Some effect, no solution. 
Even after restarting Lucee it looks like these settings really confuse things. FireFox dev tools logs a request for https://.../admin?muraAction=carch.frontendconfigurator but the request does not succeed. Trying directly shows a 'not redirecting correctly' message. The sequence of requests is all https now though :

/admin?muraAction=carch.frontendconfigurator&siteid=W&preloadOnly=true&layoutmanager=true&compactDisplay=true&cacheid=9EDD7DE7-CB92-4A3D-907B1259E195CEF7
 (301 perm redirect to)
/admin/?muraAction=carch.frontendconfigurator&siteid=W&preloadOnly=true&layoutmanager=true&compactDisplay=true&cacheid=9EDD7DE7-CB92-4A3D-907B1259E195CEF7
 (302 found redirect to)
k/admin/index.cfm?muraAction=carch.frontendconfigurator&siteid=W&preloadOnly=true&layoutmanager=true&compactDisplay=true&cacheid=9EDD7DE7-CB92-4A3D-907B1259E195CEF7
 (loops)

**Comment by tomchiverton** [comment]
"  Use SSL (Sitewide) "
Was off in the admin for this site. I turned it on, hit ?reloadApp and now nothing loads e.g. requesting a page alias like '/index.cfm/page-twooooo/' get's 302'd to '/page-twooooo' (good, right) ? But that just loops then 302'ing to itself. Just like the admin config request did.
I am using the default htaccess.txt, with indexfileinurls and siteidinurls both set to 0 (so it should just use host name).

**Comment by tomchiverton** [comment]
Seems I can force Mura to do the right thing by leaving out the options you suggested, leaving SSL off in the site settings but adding "RequestHeader set X-Forwarded-Proto "https" " to the Apache virtual host.

So this bug is really about why the SSL setting is forcing a redirection, I think.

**Comment by mattlevine** [comment]
It would be forcing a redirection if adminSSL is set to 1 and it doesn't
see the request coming as ssl.

Here's where that logic lives:
https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/utility.cfc#L351-L376

Do you see a logic issue there?

**Comment by tomchiverton** [comment]
Why does the frontend file generate a FQDN rather than just using '/admin/...'? 
-- 
Tom

**Comment by mattlevine** [comment]
Did you test it the ssl and the admindomain set as well as  X-Forwarded-Proto set to "https"?

And for the admin domain it's important to only set the domain and not the protocol.

adminssl=1
admindomain=admin.yourdoman.com

**Comment by tomchiverton** [comment]
No I didn't test that combination. 

I'm reluctant to set the admin domain because then customerA.com and customerB.com both step outside their skin to admin.another.com (and/or it requires a manual step after adding a new site to Mura). 
-- 
Tom

**Comment by mattlevine** [comment]
Then try setting forceAdminSSL=0 in the settings.ini.cfm reload.

**Comment by tomchiverton** [comment]
Can you explain why /admin/assets/js/frontendtools.js.cfm even trys to construct a full URL on line 30 ?

**Comment by mattlevine** [comment]
Will your site always use SSL or just the admin?

**Comment by mattlevine** [comment]
Please update your core and retest.

**Comment by tomchiverton** [comment]
Some combination of the above settings and the updated core has sorted it.
