### ISSUE TITLE
[Mura 7] Spelling error in menu

### ISSUE THREAD

**Issue by brucebailey** [blueriver/MuraCMS#2424]
In the admin, when you click the 3 dots to the left of content, the word "Paste" is misspelled "Past"

![screen shot 2016-10-03 at 11 05 45 am](https://cloud.githubusercontent.com/assets/913250/19042441/185fc1be-895a-11e6-8dd8-41f72c9c055b.png)

**Comment by gowestweb** [comment]
Good catch. This will be fixed in the next core update.
Changed here for reference: https://github.com/gowestweb/MuraCMS/blob/develop/requirements/mura/resourceBundle/resources/en.properties#L1659
