### ISSUE TITLE
Mura 7 - Trash Behavior Change Request

### ISSUE THREAD

**Issue by dbudde** [blueriver/MuraCMS#2426]
In the 'trashManager' in the 'empty' method, it would be nice if the `<cftransaction>` only wrapped removal of single objects.  The problem I am having is if there is a lot of items to be removed, if the page times out the `<cftransaction>` then prevents anything from being deleted.

**Comment by mattlevine** [comment]
Seems like a decent idea.  Thanks!

https://github.com/blueriver/MuraCMS/commit/dd34b27402b2144878dc75baef43d190cd0ffc45
