### ISSUE TITLE
Requested Page Cannot Be Found!!!

### ISSUE THREAD

**Issue by rawadtan** [blueriver/MuraCMS#2435]
I added a couple of pages from the administrator side with some content in each one, the **Home** page is perfectly appearing in the front end, but the children pages are not displaying, instead of the content I am getting **Requested Page Cannot Be Found** & I noticed that the top admin bar is disappearing when navigating from **Home** to other pages.
Any help about this issue ?!

**Comment by rawadtan** [comment]
I checked the console & I am getting this message **Failed to load resource: the server responded with a status of 404 () - http://127.0.0.1:8888/getgroup/about-us/**; like if the folder or content is not created!!!

**Comment by JonasEriksson** [comment]
Obviously very difficult to offer any help if you are on a local machine where no one else can see the errors etc. as opposed to a live testing server reachable by others. But it sounds like you might not have URL rewriting active on your local machine (which I have no idea on about how to do on your machine sorry, please read up on http://www.getmura.com/blog/removing-the-siteid-from-urls-in-mura/ or https://gist.github.com/stevewithington/5060589). You may see some progress by inserting  index.cfm in your url 127.0.0.1:8888/index.cfm/getgroup/about-us/  

Generally your raised issue is not really an issue with faulty code, but rather an installation/setup/expectation error and might be better sorted out over in the Mura CMS Google forums than here on GitHub. Please also keep in mind that providing a generous amount of information about your setup, server software, web server, versions of Mura and database servers etc etc are more useful to gather a helpful response than the number of exclamation marks in a request for free help. :-) Good luck!

**Comment by mattlevine** [comment]
Please re-open if this is still an issue
