### ISSUE TITLE
can't load content bean in a CFOUTPUT if the query has a column called 'cachable'

### ISSUE THREAD

**Issue by tomchiverton** [blueriver/MuraCMS#2443]
In #somesiteid#/includes/themes/#sometheme#/remote/index.cfml this works as expected, accessed as https://some.site.name/somesiteid/includes/themes/sometheme/remote/index.cfml

```
<cfset $ = application.serviceFactory.getBean('$').init(siteid)/>

<cfset artsTest=queryNew('Xcachable')/>
<cfset queryAddRow(artsTest)/>
<cfset querySetCell(artsTest,'Xcachable','1')/>
<cfoutput query="#artsTest#">
	<cfset  $.getBean('content') />
</cfoutput>
```

but this (changed the column name)

```
<cfset $ = application.serviceFactory.getBean('$').init(siteid)/>
<cftry>
	<cfset artsTest=queryNew('cachable')/>
	<cfset queryAddRow(artsTest)/>
	<cfset querySetCell(artsTest,'cachable','1')/>
	<cfoutput query="#artsTest#">
	    <cfset  $.getBean('content') />
	</cfoutput>

	<cfcatch type="any">
		error
		<cfdump var="#cfcatch#"/>
	</cfcatch>

</cftry>
```

throws "No matching function [CACHABLE] found"

Stack
lucee.runtime.exp.ExpressionException: No matching function [CACHABLE] found at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:752) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1570) at bean.ioc_cfc$cf.udfCall4(/my/web/root/mura-dev/requirements/mura/bean/ioc.cfc:701) at bean.ioc_cfc$cf.udfCall(/my/web/root/mura-dev/requirements/mura/bean/ioc.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224) at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:770) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:752) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1570) at bean.ioc_cfc$cf.udfCall4(/my/web/root/mura-dev/requirements/mura/bean/ioc.cfc:620) at bean.ioc_cfc$cf.udfCall(/my/web/root/mura-dev/requirements/mura/bean/ioc.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224) at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:770) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:752) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1570) at bean.ioc_cfc$cf.udfCall1(/my/web/root/mura-dev/requirements/mura/bean/ioc.cfc:132) at bean.ioc_cfc$cf.udfCall(/my/web/root/mura-dev/requirements/mura/bean/ioc.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580) at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1902) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:752) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1570) at cfobject_cfc$cf.udfCall2(/my/web/root/mura-dev/requirements/mura/cfobject.cfc:121) at cfobject_cfc$cf.udfCall(/my/web/root/mura-dev/requirements/mura/cfobject.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:588) at lucee.runtime.SuperComponent.call(SuperComponent.java:82) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:752) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1570) at murascope_cfc$cf.udfCall2(/my/web/root/mura-dev/requirements/mura/MuraScope.cfc:385) at murascope_cfc$cf.udfCall(/my/web/root/mura-dev/requirements/mura/MuraScope.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580) at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1902) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:752) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1570) at wellcome.includes.themes.wellcome.remote._import.everyone_cfm$cf.call(/my/web/root/mura-dev/my-site-id/includes/themes/my-theme-id/remote/import/everyone.cfm:109) at

**Comment by tomchiverton** [comment]
```
<cfset $ = application.serviceFactory.getBean('$').init(siteid)/>
```

**Comment by tomchiverton** [comment]
Core Version 7.0.6798
Site Version 7.0.6798
App Server Lucee (5.0.0.254)
Java Version 1.8.0_101
OS Amazon Linux 64bit

**Comment by stevewithington** [comment]
@tomchiverton i'm not sure what you're attempting to do exactly, but i would suggest using a different name. `cachable` is a function inside of Di1, and so you may be running into some issue/s there: https://github.com/framework-one/di1/blob/8e06e47347b483121629867034c914248dcf08b8/ioc.cfc#L276

**Comment by stevewithington** [comment]
@tomchiverton in fact, after re-reading your post, that's exactly what's causing your issue. use a different name.

**Comment by tomchiverton** [comment]
Eh? If I'm looping around a table of stuff, *that's what it is called *. Happens to be a table in a totally different db to Mura,for some other app. 

I just used querynew() for the test case. 

In Slack, appears Mura is missing a 'this' from the call at the top of the stack? 
-- 
Tom

**Comment by tomchiverton** [comment]
Should be fixed with : https://luceeserver.atlassian.net/browse/LDEV-1059
