### ISSUE TITLE
CkFinder update to resolve Last Folder issue

### ISSUE THREAD

**Issue by jsieber-aca** [blueriver/MuraCMS#2444]
The current version of CkFinder that is included with Mura has a bug that prevents that Last Folder from being saved or any of the user settings for sorting or display settings from functioning. Upgrading ckFinder to version 2.6.2.1 resolves the issue.

**Comment by mattlevine** [comment]
Done
https://github.com/blueriver/MuraCMS/commit/c435660425711972f2ccb209fc002145022ed997
