### ISSUE TITLE
Error 500 in Mailing list manager

### ISSUE THREAD

**Issue by damienbkx** [blueriver/MuraCMS#2451]
I now Mailing lists and eMail broadcaster are not anymore supported in Mura 7, but these are still there and can be activated, which I did.

When trying to access the management of a mailing list, I had an Error 500. 
Turned out to be a missing </cfif> on line 87 (just before the </ul>) of the /admin/core/views/cmailinglist/dsp_tab_usage.cfm file.

Even if this feature is not supported, can we still hope for that tiny correction in the next Mura update?

Thks...

**Comment by mattlevine** [comment]
We'll get this fixed.

**Comment by mattlevine** [comment]
Please update your core and retest.

**Comment by damienbkx** [comment]
Already done! 
It works like a charm.

The issue can be closed! 
Thanks and good day to you.

Damien
