### ISSUE TITLE
Paths with dot in them do not return 404

### ISSUE THREAD

**Issue by fraxen** [blueriver/MuraCMS#2452]
Mura 6.2 - it seems like links with a dot in them do not return a 404, but rather returns the front page:
http://mysite.com/asdf/ -> returns a 404
http://mysite.com/asdf.asdf/ -> returns a 200, with the front page

Possible related to #1028

**Comment by Tropicalista** [comment]
Same error here. 

Do you have found a fix?

**Comment by fraxen** [comment]
My problem was that I could see spammers trying links like that - it did show up in Google Analytics. I created rules in my web server (Apache) to make sure those returned 404 - those specific URLs that the spammers used.

**Comment by Tropicalista** [comment]
Yes i understand. I have same problem and cannot create the rules each time I found those links.

I think problem are on this line

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/content/contentServer.cfc#L243

but I'm new to mura, so I'm not sure.

**Comment by fraxen** [comment]
See https://groups.google.com/forum/#!searchin/mura-cms-developers/dot$20404%7Csort:relevance/mura-cms-developers/ZqMYLuO3b08/E9GtQccgAAAJ and http://stackoverflow.com/questions/32103979/how-do-you-handle-404-errors-with-mura-and-your-web-server

**Comment by Tropicalista** [comment]
Many thanks
