### ISSUE TITLE
Getting error after creating component in version 7.0.6817

### ISSUE THREAD

**Issue by Reyjay** [blueriver/MuraCMS#2455]
When i created a folder under components I started getting the attached error.  Now every time I go and click on the components tab it won't load due to the attached error.  I updated and reloaded the site and the issue persisted.

Version 7.0.6817

![etr ten24web com admin muraaction carch loadsitemanager siteid default topid moduleid 00000000000000000000000000000000003 sortby sortdirection ptype component startrow 1 cacheid 0 6041269756498511](https://cloud.githubusercontent.com/assets/1654250/20331755/4ea9de48-ab5c-11e6-9465-a322021e74e5.jpeg)

**Comment by mattlevine** [comment]
My guess is that this error will go away if you logout and back in again.   But thanks for the stacktrace, I'll try and see if I can repoduce it.

**Comment by Reyjay** [comment]
Hi Matt,

Logging in did resolve the issue and I was able to see the components again.

Thanks,
Reyjay

**Comment by mattlevine** [comment]
I'm going to close this, but if it happens again please let me know
