### ISSUE TITLE
Cannot Create / update / delete a malinglist

### ISSUE THREAD

**Issue by damienbkx** [blueriver/MuraCMS#2457]
In mura 7, creating, updatigng and deleting a mailinglist does not work.

Providing that eMail broadcaster and mailinglists are activated in settings.ini.cfm

CREATING
1) go to mailinglist list
2) click on Add mailing list
3) fill the form and hit submit
=> Result You end up on the mailing list member page and a mlid is correctly generated in the URL BUT the mailing list is NOT saved in the tmailinglist database table. => When returning to the list of mailing list, the new mailing list does not appear.

UPDATING
1) go to mailinglist list
2) open an existing mailing list
3) change properties (for example, make it public) 
3) submit the changes
=> Result You end up on the mailing list member page, but the changes are not saved in the tmailinglist database table. => When returning to the list of mailing list, the updates do not show.

Conclusions
It seems that everything works fine inside of Mura and the problem is on the database access layer. I suspect some changes made to the ORM has not been impacted in the Mailing list manager due to the depreciation of this module.

I understand mailing lists and eMail broadcaster are not anymore supported, but this is important for my business that it works.

Any hint on how to fix it?

thanks

**Comment by damienbkx** [comment]
Nailed it! 
Issue is due to bas <div> tag imbrication in /admin/core/views/cmailinglist/edit.cfm The result is

- Tabs not working
- Form buttons end up outside of the form => this is what causes the issue as "action" and "mlid" fields are not transmitted to processing script because buttons are outside of the form.

Solution : 
Add 
```
<div class="block block-bordered">						
				<div class="block-content">
```
after line 75 of /admin/core/views/cmailinglist/edit.cfm

End code is
```
<div id="tabBasic" class="tab-pane active">
		<!--DBR-->
		<div class="block block-bordered">						
				<div class="block-content">
		<!--End DBR-->
			<div class="mura-control-group">
```

**Comment by mattlevine** [comment]
That's for the help, we'll get that fix in the core soon!

**Comment by AlHolden** [comment]
@mattlevine - has this one been applied yet? 
Core 7.0.6957 does not seem to be fixed for us.

**Comment by mattlevine** [comment]
@AlHolden Can you describe your error?

**Comment by AlHolden** [comment]
@mattlevine - the error is as described by damienbkx when he created this issue 2457 on Nov 19, 2016
When you create a mailing list (and import), the mlid is correctly generated in the URL BUT the mailing list record is NOT saved in the tmailinglist database table. 
Any imported member records DO exist in the tmailinglistmembers table (bearing the new mlid), but the parent tmailinglist record's not there.
damienbkx suggests a found solution, but I don't know if that's accurate to the file version any more.

**Comment by mattlevine** [comment]
@AlHolden Please manually update this file from the develop branch

https://github.com/blueriver/MuraCMS/blob/develop/admin/core/views/cmailinglist/edit.cfm

It will be in the next build as well.

thanks
-Matt

**Comment by AlHolden** [comment]
This version appears to resolve the problem. Thanks!
Al
