### ISSUE TITLE
Unable to insert remote feed via inline editing

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2458]
Hi Chaps,

Been trying to add a remote feed to a page, however when doing so I just get the message 'This object has not been configured"  o matter what I do to insert it -the same holds true if I try to use the legacy objects version.

Feed is atom, other than that, can't see anything else that could be going wrong?

MTIA,

Peter.

**Comment by mattlevine** [comment]
If you enable your JS debugger are you seeing an error in the network tab?

**Comment by mattlevine** [comment]
Looks like we never implemented atom feeds.  Are you able to get it in rss?

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/content/feed/feedUtility.cfc#L183-L189

**Comment by PeterBowater** [comment]
Thanks Matt,

That is weird, I have this working in 6.2.6517, pulling the same atom feed.

No error in console, if I add labels, view all links they all work OK, but the text remains 'This object has not been configured'.

**Comment by PeterBowater** [comment]
This is the feed: https://www.gov.uk/government/announcements.atom , no RSS option unfortunately.

I also just looked at the code on the server where I have it running successfully on 6.2 and it appears to be commented out as per your link above... weirder ! :)

**Comment by PeterBowater** [comment]
This contains stuff to do with atom: 

https://github.com/blueriver/MuraCMS/blob/develop/default/includes/display_objects/feed/index.cfm

**Comment by mattlevine** [comment]
I noticed that you provided a sample feed, so I tested locally and it worked?

Are you on a fresh Mura 7 install?

**Comment by PeterBowater** [comment]
Just tried with a new download of Mura, and updated to latest version, same things happening.

Configured as so:

![screen shot 2016-11-30 at 11 29 45](https://cloud.githubusercontent.com/assets/807991/20750761/64fe42de-b6f0-11e6-933b-1ab606da3e7a.jpg)
![screen shot 2016-11-30 at 11 29 17](https://cloud.githubusercontent.com/assets/807991/20750762/65004dc2-b6f0-11e6-98ea-561c699ff222.jpg)

Same result with the 'legacy' method.

**Comment by mattlevine** [comment]
If you enable the chrome debugger are there any errors in the console or network tabs?

**Comment by PeterBowater** [comment]
No errors, just the normal AJAX calls for the front end editor.

I've weirdly just successfully inserted this locally, on the fresh installation.

Still broken on other instances though, will do some more prodding.

**Comment by PeterBowater** [comment]
No errors logged, only the normal logging of AJAX calls.

I have, this morning, been able to insert one successfully locally on the new test bed I have, weirdly.

Still unable to on development server or other instances locally.

The calls back to Mura to get the feed are all pretty much identical, nothing showing as errors, URLs are well-formed, in both instances.

Seems like something in apiUtility is bombing to me, at least.
