### ISSUE TITLE
Mura Core 7.0.6829 - Events Don't Appear in Calendar or Collections

### ISSUE THREAD

**Issue by tbugler** [blueriver/MuraCMS#2461]
After updating the core, my events are no longer appearing in my calendar or within any local content indexes generated from the calendar.

No errors, but the page(s) exist as I can hit them with a direct URL.

I have tried recreating the calendar and pages to no avail.

**Comment by tbugler** [comment]
It appears if the event is a single day or spans 4 days or more it appears. If the event is two or three days it doesn't show up in the calendar.

**Comment by mattlevine** [comment]
Please update and retest.  You may need to update the content schedule info once more as well.
