### ISSUE TITLE
Syntax Error in the apiUtility.cfc

### ISSUE THREAD

**Issue by szabolcsnagy** [blueriver/MuraCMS#2463]
I think I found a syntax error here.
https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/client/api/json/v1/apiUtility.cfc#L1655

'"content' should be just 'content'

**Comment by mattlevine** [comment]
What is the symptom or issue that you are having?  The default "feed" is for content so I don't "think" what you are pointing as is an issue?

**Comment by szabolcsnagy** [comment]
No, there is no particular issue here. As I just went through the code I spotted an extra double quote in the if statement. This is the line. See after == the string is '"content'.
} else if(arguments.entityName=='"content' && len($.event('feedname'))){

**Comment by mattlevine** [comment]
Ahh, thanks for pointing that out.
