### ISSUE TITLE
dspPrimaryNav() and Bootstrap 4

### ISSUE THREAD

**Issue by damienbkx** [blueriver/MuraCMS#2468]
Currently creating a theme using the alpha 5 version of Bootstrap 4

There has been a change in the _navbar_ Bootstrap component in Bootstrap 4. Now a `class="navbar-item"` must be provided for all `<li>` elements of the menu.  (see [https://v4-alpha.getbootstrap.com/components/navbar/](url) for info)

Unfortunately, the current implementation of `dspPrimaryNav()` does not allow for such class to be added to the first `<li>` (the first link of the nav bar) when `displayHome` is set to `always` or to `conditional`  (and maybe other scenarios, did not test)

To fix this, I have added `<cfif len(arguments.liClass)> #arguments.liClass#</cfif>` at line 1804 of `/requirements/mura/content/contentRenderer.cfc`. 

This line of code now looks like 
`<li class="first<cfif variables.event.getValue('contentBean').getcontentid() eq arguments.contentid> #arguments.liCurrentClass#</cfif><cfif len(arguments.liClass)> #arguments.liClass#</cfif>" id="navHome"<cfif len(arguments.liCurrentAttributes)> #arguments.liCurrentAttributes#</cfif>><a href="#homeLink#"<cfif len(arguments.aCurrentClass) and $.content('contentID') eq '00000000000000000000000000000000001'> class="#arguments.aCurrentClass#"<cfelseif len(arguments.aNotCurrentClass)> class="#arguments.aNotCurrentClass#"</cfif><cfif len(arguments.aCurrentAttributes)> #arguments.aCurrentAttributes#</cfif>>#HTMLEditFormat(rsHome.menuTitle)#</a></li>`

Now the class specified in the `liClass` option of `dspPrimaryNav()` is added to the first generated `<li>` element of the navigation list as well.

Please confirm this is the right way to do and eventually integrate this fix in next core update. 

Thanks

**Comment by mattlevine** [comment]
Thanks for pointing that out. While we look into this I would copy your customized method into your theme's contentRenderer.cfc and reload so you don't need to worry about it being overridden.

**Comment by mattlevine** [comment]
Looking into it further, that's definitely a bug.
