### ISSUE TITLE
Calendar event end time is automatically replaced with current time

### ISSUE THREAD

**Issue by didgiman** [blueriver/MuraCMS#2474]
Whenever I add a new item to a calendar, and set the end time for the event, after publishing the end time is replaced with the current time.

**Comment by mattlevine** [comment]
Can you update your core and retest?

**Comment by mattlevine** [comment]
Nevermind, it was able to see it happen

**Comment by mattlevine** [comment]
Please update and retest.

**Comment by didgiman** [comment]
Yes, it works now. Thanks!
