### ISSUE TITLE
Installation Bug - mysql.sql not executed

### ISSUE THREAD

**Issue by raeberli** [blueriver/MuraCMS#2477]
When Installing Mura on a ColdFusion 11/MySQL server I got the error message unexpected character near INSERT INTO `tmailinglist`. I checked the mysql.sql file and found that there is a cfoutput for a createUUID function. 

As of ColdFusion 11 only files with allowed extensions will be executed when including, files where the extension is not allowed only the unexecuted content of the file will be included. 

I would suggest to set compileextforinclude in the application settings to avoid the error.

**Comment by mattlevine** [comment]
Can you post what your OS, CF and Mysql versions are?  That code has been there for years?

Thanks
-Matt

**Comment by raeberli** [comment]
Dear Matt, 

Windows 2012R2, CF11 Upd 10 and MySQL 5.6.19. 

If you look at the documentation of cfinclude [1] you should see what I mean. Could be that default installations have the administrator setting on * (for everything) but on locked down servers or shared hosting servers this value should be empty or will perhaps not include sql.

Don't know how Lucee reacts on unknown applications settings, but if lucee just ignores it it would be a small fix. Perhaps the following in config\applicationSettings.cfm on line 103

<cfset this.compileextforinclude = "sql">

[1] https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-i/cfinclude.html

Thanks,
Reto
