### ISSUE TITLE
?fields param doesn't appear to work properly in json api.

### ISSUE THREAD

**Issue by rwatts3** [blueriver/MuraCMS#2481]
Greetings, 

I am trying to use the json api and I have added the `fields` param as described in the docs.
Unfortunately no matter what values I add to the fields param, all fields are returned in the results.

Please advise. 

-V/R

Ryan

**Comment by mattlevine** [comment]
Can you show what your call looks like? As a side note, it will always return siteid, id and links

Try this http://mysql.mura.dev:53644/index.cfm/_api/json/v1/default/content?fields=title

**Comment by rwatts3** [comment]
Thank you I will give that a try.

**Comment by rwatts3** [comment]
Hi Matt, 

Unfortunately that didn't work. 

http://www.ryanwatts.me/index.cfm/_api/json/v1/mbrw/content?fields=title

**Comment by mattlevine** [comment]
Please update and retest

**Comment by rwatts3** [comment]
Thank you will do.

**Comment by rwatts3** [comment]
Flawless !
