### ISSUE TITLE
Feature request : Form generator buttons translation

### ISSUE THREAD

**Issue by Tristanimve** [blueriver/MuraCMS#2482]
Is there a way to change button labels made by form generator ? It seems that whatever locale i use in site config, the paging buttons and submit always look like the same : "Next" "Back" and "Submit". I would like to be abble to modify it  but it seems that labels are hard coded in mura.js. 

Thanks for help

Tristan

**Comment by mattlevine** [comment]
I agree, that's an issue.  There's already an rb object within the form display object but it's not used i those buttons.  Ping back here if it's not fixed later this week.
