### ISSUE TITLE
Minor bug in admin core

### ISSUE THREAD

**Issue by szabolcsnagy** [blueriver/MuraCMS#2487]
In the following file the REReplace function is missing the 'substring' parameter.
Currently it is `url.view=ReReplace(url.view, '[^a-zA-Z0-9_\.\\/]','all');`
I believe the 3rd parameter should be an empty string before the 'all'

https://github.com/blueriver/MuraCMS/blob/master/admin/core/views/carch/displayobjectmodal.cfm#L21

Szabolcs

**Comment by mattlevine** [comment]
Thanks for pointing that out!
