### ISSUE TITLE
Database error when loading a User Bean with mura.js

### ISSUE THREAD

**Issue by damienbkx** [blueriver/MuraCMS#2489]
Hi, 

Currently building a user form for a plugin. I need to load a user's details using Mura.js, so I wrote this in my Javascript
`Mura.getEntity('user').loadBy('userId', userId)`

When running this line. I have the following error in the console
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tusers.userId = 'FD18C68B-3327-4' at line 225"`

I have isolated the SQL query from the error message and found out that there is a missing `and` between the 2 parameters passed to the Query. Here is the problematic part of the generated query

`and ( tusers.siteid = 'ddx_mediacenter' tusers.userId = 'FD18C68B-3327-439E-90D681154F858A67')`

This should read
`and ( tusers.siteid = 'ddx_mediacenter' AND tusers.userId = 'FD18C68B-3327-439E-90D681154F858A67')`

I've pinpoint the problem to line 302 of the `mura/user/userGateway.cfc` component. It is the bit of code that is responsible to add the correct relationship between the parameters of the query.

The line is 

`<cfelseif not openGrouping>
	#param.getRelationship()#
</cfif>`

When I change it to 

`<cfelseif started OR not openGrouping>
	#param.getRelationship()#
</cfif>`

...everything works fine in my application. 
I suspect this is a bug, but I may have broken something else by modifying the code of userGateway.cfc.
Could you have a look and confirm the fix?

Thanks and good day to you guys...

Damien

**Comment by mattlevine** [comment]
Please update and retest.

Thanks,
-Matt

**Comment by damienbkx** [comment]
Works like a charm! 
Thanks Matt.

Issue is closed!
