### ISSUE TITLE
Permission bug when loading users with mura.js

### ISSUE THREAD

**Issue by damienbkx** [blueriver/MuraCMS#2490]
Hi, 

For the plugin I am developing, I have created 2 groups  : Admin and users. These are the admins and the users of the plugin. As far as mura is concerned, these 2 groups are both member groups. 

My plugin admins should be able to manage users only in the plugin admins and user groups (remember, both Member groups for Mura). 

I have set the permissions accordingly, and I could verify that my plugin admins do have access to the users and group management on the backend. 

BUT, When loading a user with Ajax and mura.js
`Mura.getEntity('user').loadBy('userId', userId)`

I have the following error : `message:"Insufficient Account Permissions"`

Looks like the permissions are not well applied when using Mura.js to load users.

Do I do something wrong? or is this a bug?

Thanks

**Comment by mattlevine** [comment]
Please update your core and retest. 

Thanks,
-Matt

**Comment by damienbkx** [comment]
It now works as expected. 
Thanks Mat!! 

Issue is closed.
