### ISSUE TITLE
Issues with form and async objects

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2494]
Hi Chaps (again, sorry),

CF9, win2K3 (I know, sorry, really hope this isn't related this time)

Been having some difficulty adding a form to a page, when viewing the page I get an error from the async request, as so:

{"error":{"stacktrace":{"Suppressed":[],"Locale":null,"Type":"Expression","objectType":{},"RootCause":null,"element":"METHOD","Resolvedname":"PARAMS","StackTrace":[{"FileName":"CfJspPage.java","NativeMethod":false,"ClassName":"coldfusion.runtime.CfJspPage","LineNumber":1724,"MethodName":"resolveCanonicalName"},{"FileName":"CfJspPage.java","NativeMethod":false,"ClassName":"coldfusion.runtime.CfJspPage","LineNumber":1620,"MethodName":"_resolve"},{"FileName":"CfJspPage.java","NativeMethod":false,"ClassName":"coldfusion.runtime.CfJspPage","LineNumber":1794,"MethodName":"_resolveAndAutoscalarize"},{"FileName":"CfJspPage.java","NativeMethod":false,"ClassName":"coldfusion.runtime.CfJspPage","LineNumber":1787,"MethodName":"_resolveAndAutoscalarize"},{"FileName":"E:\\Websites\\SPLARGE\\requirements\\mura\\client\\api\\json\\v1\\apiUtility.cfc","NativeMethod":false,"ClassName":"cfapiUtility2ecfc1289097593$funcPROCESSREQUEST","LineNumber":757,"MethodName":"runFunction"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod","LineNumber":472,"MethodName":"invoke"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod$ArgumentCollectionFilter","LineNumber":368,"MethodName":"invoke"},{"FileName":"FunctionAccessFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.FunctionAccessFilter","LineNumber":55,"MethodName":"invoke"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod","LineNumber":321,"MethodName":"runFilterChain"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod","LineNumber":220,"MethodName":"invoke"},{"FileName":"TemplateProxy.java","NativeMethod":false,"ClassName":"coldfusion.runtime.TemplateProxy","LineNumber":491,"MethodName":"invoke"},{"FileName":"TemplateProxy.java","NativeMethod":false,"ClassName":"coldfusion.runtime.TemplateProxy","LineNumber":337,"MethodName":"invoke"},{"FileName":"CfJspPage.java","NativeMethod":false,"ClassName":"coldfusion.runtime.CfJspPage","LineNumber":2360,"MethodName":"_invoke"},{"FileName":"E:\\Websites\\SPLARGE\\requirements\\mura\\content\\contentServer.cfc","NativeMethod":false,"ClassName":"cfcontentServer2ecfc91385982$funcHANDLEAPIREQUEST","LineNumber":523,"MethodName":"runFunction"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod","LineNumber":472,"MethodName":"invoke"},{"FileName":"SilentFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.SilentFilter","LineNumber":47,"MethodName":"invoke"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod$ArgumentCollectionFilter","LineNumber":368,"MethodName":"invoke"},{"FileName":"FunctionAccessFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.FunctionAccessFilter","LineNumber":55,"MethodName":"invoke"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod","LineNumber":321,"MethodName":"runFilterChain"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod","LineNumber":220,"MethodName":"invoke"},{"FileName":"CfJspPage.java","NativeMethod":false,"ClassName":"coldfusion.runtime.CfJspPage","LineNumber":2582,"MethodName":"_invokeUDF"},{"FileName":"E:\\Websites\\SPLARGE\\requirements\\mura\\content\\contentServer.cfc","NativeMethod":false,"ClassName":"cfcontentServer2ecfc91385982$funcHANDLEROOTREQUEST","LineNumber":662,"MethodName":"runFunction"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod","LineNumber":472,"MethodName":"invoke"},{"FileName":"SilentFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.SilentFilter","LineNumber":47,"MethodName":"invoke"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod$ArgumentCollectionFilter","LineNumber":368,"MethodName":"invoke"},{"FileName":"FunctionAccessFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.FunctionAccessFilter","LineNumber":55,"MethodName":"invoke"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod","LineNumber":321,"MethodName":"runFilterChain"},{"FileName":"UDFMethod.java","NativeMethod":false,"ClassName":"coldfusion.runtime.UDFMethod","LineNumber":220,"MethodName":"invoke"},{"FileName":"TemplateProxy.java","NativeMethod":false,"ClassName":"coldfusion.runtime.TemplateProxy","LineNumber":491,"MethodName":"invoke"},{"FileName":"TemplateProxy.java","NativeMethod":false,"ClassName":"coldfusion.runtime.TemplateProxy","LineNumber":337,"MethodName":"invoke"},{"FileName":"CfJspPage.java","NativeMethod":false,"ClassName":"coldfusion.runtime.CfJspPage","LineNumber":2360,"MethodName":"_invoke"},{"FileName":"E:\\Websites\\SPLARGE\\index.cfm","NativeMethod":false,"ClassName":"cfindex2ecfm777267770","LineNumber":46,"MethodName":"runPage"},{"FileName":"CfJspPage.java","NativeMethod":false,"ClassName":"coldfusion.runtime.CfJspPage","LineNumber":231,"MethodName":"invoke"},{"FileName":"IncludeTag.java","NativeMethod":false,"ClassName":"coldfusion.tagext.lang.IncludeTag","LineNumber":416,"MethodName":"doStartTag"},{"FileName":"CfincludeFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.CfincludeFilter","LineNumber":65,"MethodName":"invoke"},{"FileName":"ApplicationFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.ApplicationFilter","LineNumber":378,"MethodName":"invoke"},{"FileName":"MonitoringFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.MonitoringFilter","LineNumber":40,"MethodName":"invoke"},{"FileName":"PathFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.PathFilter","LineNumber":94,"MethodName":"invoke"},{"FileName":"ExceptionFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.ExceptionFilter","LineNumber":70,"MethodName":"invoke"},{"FileName":"ClientScopePersistenceFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.ClientScopePersistenceFilter","LineNumber":28,"MethodName":"invoke"},{"FileName":"BrowserFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.BrowserFilter","LineNumber":38,"MethodName":"invoke"},{"FileName":"NoCacheFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.NoCacheFilter","LineNumber":46,"MethodName":"invoke"},{"FileName":"GlobalsFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.GlobalsFilter","LineNumber":38,"MethodName":"invoke"},{"FileName":"DatasourceFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.DatasourceFilter","LineNumber":22,"MethodName":"invoke"},{"FileName":"CachingFilter.java","NativeMethod":false,"ClassName":"coldfusion.filter.CachingFilter","LineNumber":62,"MethodName":"invoke"},{"FileName":"CfmServlet.java","NativeMethod":false,"ClassName":"coldfusion.CfmServlet","LineNumber":201,"MethodName":"service"},{"FileName":"BootstrapServlet.java","NativeMethod":false,"ClassName":"coldfusion.bootstrap.BootstrapServlet","LineNumber":89,"MethodName":"service"},{"FileName":"FilterChain.java","NativeMethod":false,"ClassName":"jrun.servlet.FilterChain","LineNumber":86,"MethodName":"doFilter"},{"FileName":"FusionReactorFilter.java","NativeMethod":false,"ClassName":"com.intergral.fusionreactor.filter.FusionReactorFilter","LineNumber":376,"MethodName":"b"},{"FileName":"FusionReactorFilter.java","NativeMethod":false,"ClassName":"com.intergral.fusionreactor.filter.FusionReactorFilter","LineNumber":254,"MethodName":"c"},{"FileName":"FusionReactorFilter.java","NativeMethod":false,"ClassName":"com.intergral.fusionreactor.filter.FusionReactorFilter","LineNumber":164,"MethodName":"doFilter"},{"FileName":"FilterChain.java","NativeMethod":false,"ClassName":"jrun.servlet.FilterChain","LineNumber":94,"MethodName":"doFilter"},{"FileName":"MonitoringServletFilter.java","NativeMethod":false,"ClassName":"coldfusion.monitor.event.MonitoringServletFilter","LineNumber":42,"MethodName":"doFilter"},{"FileName":"BootstrapFilter.java","NativeMethod":false,"ClassName":"coldfusion.bootstrap.BootstrapFilter","LineNumber":46,"MethodName":"doFilter"},{"FileName":"FilterChain.java","NativeMethod":false,"ClassName":"jrun.servlet.FilterChain","LineNumber":94,"MethodName":"doFilter"},{"FileName":"FilterChain.java","NativeMethod":false,"ClassName":"jrun.servlet.FilterChain","LineNumber":101,"MethodName":"service"},{"FileName":"ServletInvoker.java","NativeMethod":false,"ClassName":"jrun.servlet.ServletInvoker","LineNumber":106,"MethodName":"invoke"},{"FileName":"JRunInvokerChain.java","NativeMethod":false,"ClassName":"jrun.servlet.JRunInvokerChain","LineNumber":42,"MethodName":"invokeNext"},{"FileName":"JRunRequestDispatcher.java","NativeMethod":false,"ClassName":"jrun.servlet.JRunRequestDispatcher","LineNumber":286,"MethodName":"invoke"},{"FileName":"ServletEngineService.java","NativeMethod":false,"ClassName":"jrun.servlet.ServletEngineService","LineNumber":543,"MethodName":"dispatch"},{"FileName":"JRunProxyService.java","NativeMethod":false,"ClassName":"jrun.servlet.jrpp.JRunProxyService","LineNumber":203,"MethodName":"invokeRunnable"},{"FileName":"ThreadPool.java","NativeMethod":false,"ClassName":"jrunx.scheduler.ThreadPool$DownstreamMetrics","LineNumber":320,"MethodName":"invokeRunnable"},{"FileName":"ThreadPool.java","NativeMethod":false,"ClassName":"jrunx.scheduler.ThreadPool$ThreadThrottle","LineNumber":428,"MethodName":"invokeRunnable"},{"FileName":"ThreadPool.java","NativeMethod":false,"ClassName":"jrunx.scheduler.ThreadPool$UpstreamMetrics","LineNumber":266,"MethodName":"invokeRunnable"},{"FileName":"WorkerThread.java","NativeMethod":false,"ClassName":"jrunx.scheduler.WorkerThread","LineNumber":66,"MethodName":"run"}],"Detail":"","ErrNumber":0,"Message":"Element METHOD is undefined in PARAMS.","LocalizedMessage":"Element METHOD is undefined in PARAMS.","Cause":null},"message":"Unhandled Exception","code":"server_error"},"method":"undefined","apiversion":"v1","params":{}}

the call to the API is:

http://splarge.org/index.cfm/_api/json/v1/splarge/?method=processAsyncObject&object=form&objectid=F1129DC5-5056-A318-A8F151AE68487B86&instanceid=F28D123A-5056-A318-A825AE7A545D06E9&css=&render=client&=&view=form&label=&async=true&_p=1&objecticonclass=mi-toggle-on&objectname=Form&perm=author&isconfigurator=false&siteid=splarge&contentid=2C0B4EAC-5056-A318-A8ABE1EE33D47898&contenthistid=F11EAB40-5056-A318-A8245CF899652157

Any ideas?

Many thanks,

Peter.

**Comment by didgiman** [comment]
I have the same issue. Also on CF9 btw...

**Comment by PeterBowater** [comment]
Possibly(!)

I had to change the mura core a touch, needless to say this is not a long term fix, but it at least allowed me to process forms.

Go to line 757 of this file:

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/client/api/json/v1/apiUtility.cfc

And change it to :

return;

No idea why this fixes it, but causes no problems for me either. Forms get results get returned, and the proper events get fired -I use this to fire an email out to people after form submit, and then redirect them to a decent thank you page, rather than the default action of showing the thank you message you configure in the form.

For completeness, this is the following function:

```coldfusion
public any function onAfterFormSubmitSave($){
			try{
				var msg = '';
				var formBean = $.event().getValue('formBean');
				var formResultBean = $.event().getValue('formDataBean');
				var formResultStruct = $.event().getValue('formDataBean').getValue('formResult');					
				savecontent variable="emailCopy" { 
					WriteOutput("<p>Field label: #formResultBean.getValue('formfieldname')#</p>");};
 			$.getBean('mailer').sendHTML(
								html=emailCopy,
								sendto='#EmailAddress#',
								from='test@test.com',
								subject='Request for more information ',
								siteid=$.event('siteid'),
								replyTo='test@test.com');				
			} catch(any e) {
				FileWrite('formData.txt', e.message);
			}
			return;
		}

```

Note I have edited that to anonify it, so not tested/valid code :) 

I do not really recommend this as a fix, but as we are stuck on CF9, with little to no chance of upgrade in near future, needs must. Obviously can't use autoupdater after this, in fact this is broken in CF9 anyways(!).

Hope that helps you get over a small hurdle.

**Comment by didgiman** [comment]
The fix solved the issue Peter. Thanks a lot!

**Comment by mattlevine** [comment]
I updated the core so that you should not need to tweak the Mura core apiUtility.cfc.
