### ISSUE TITLE
on after form submit isn't working in 7.0.6854 or 7.0.6879

### ISSUE THREAD

**Issue by Tigerlady** [blueriver/MuraCMS#2500]
I posted this issue in the Google Groups here https://groups.google.com/forum/#!topic/mura-cms-developers/YWzB38r6zpI

Basically I have been using this code for a long time to send a "pretty" email when a form is submitted.  The last version of Mura 7 on a site that actually is working is site and core 7.0.6645  This site uses the exact same code for sending emails after a form submit and works great.  I am just wondering if something has changed with recent updates? 

Here is the code that I have been using for every site. 

`<cffunction name="onAfterFormSubmitSave" output="false">
   <cfargument name="$">
    <cfset receipt = $.event('formDataBean').getFormResult() />
       
  
  <cfset record = receipt />
    <cfif $.content('title') eq "Contact/RFQ">
        <cfmail to="me@domain.com"
        cc="#form.email#"
        replyto="#form.email#"
          from="#form.email#"
          subject="Contact / RFQ"
          type="html">
          
          <cfinclude template="/default/includes/display_objects/custom/contact.cfm">
          
        </cfmail>
   
        </cfif>
</cffunction>`

I use this in the site eventhandler.cfc

I have also just tried putting the contents of the contact.cfm file in the eventhandler.cfc file but that doesn't work either. 

 I have the mail settings set up on Lucee and in the Mura Admin.  I am also getting the plain ugly text email that comes from the form filling in Mura.  What I am not receiving is the mail from the on After form submit.  I did set it to just send a plain text message and that still didin't work.  I have been using the same type of code on about 20 different sites that are built on different versions of Mura and they all work but this one. I also just tried sending another email from another site that is also on Mura 7 and it didn't come through either. Again I get the email from the form fill the plain one but not one from the onAfterFormSubmit.  

This is really a problem as the client is really wanting this pretty email.

**Comment by mattlevine** [comment]
Is this for a CKEditor based form or one using the form builder?

This works for me, but I'm on the latest code.  Can you update both your core then site files and retest?

-Matt

**Comment by Tigerlady** [comment]
It is done with the form builder.  The site that is working has both types of forms and they all work. 

I just updated the dev site core files first to Core Version 7.0.6882.  I got this error message

500 Error
component [mura.plugin.pluginManager] has no function with name [isLoggedIn] 
Code: 0 
Type: expression 
component [mura.plugin.pluginManager] has no  function with name [isLoggedIn]
	at lucee.runtime.type.util.ComponentUtil.notFunction(ComponentUtil.java:660):660
	at lucee.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:567):567
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:526):526
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1596):1596
	at admin.common.layouts.template_cfm$cf.call(/muraWRM/admin/common/layouts/template.cfm:252):252

I did a refresh and it said 0 files had been updated.  however, when i do a compare to what is on the server it seems to have updated several files. 

Having said that I tried sending the form email again and still doesn't work.  I get the plain text version sent from the form but it doesn't seem to trigger the event handler.  

Also just to be sure the cfif $.content('title')  the Title is the title of the page where the form is placed not the title of the form itself.  However, I have both versions in the event handler and neither of them are working.  Would you like to see a copy of the event handler file?

**Comment by mattlevine** [comment]
I'm pretty sure that error is just an issue with the autoupdate process and not with the code that was updated.  It happened after the code was updated.  It's very tricky because the request starts with on codebase and ends with another.  If you get it again let me know.

You also may want to re-apply the display object to the page so it's a "Form" (Mura 7) object and not a "datacollection" object.  

And I would double check if you have customized you form or datacollection display objects in your theme?

**Comment by Tigerlady** [comment]
Matt,  not sure what you mean by this.  "You also may want to re-apply the display object to the page so it's a "Form" (Mura 7) object and not a "datacollection" object."  When I go to put the form on the page all I see is the Data Collector option.  

![image](https://cloud.githubusercontent.com/assets/1850313/22437038/04074a08-e6ec-11e6-89ef-81fd20b3f6d5.png)

After doing some searching on the Google Groups I added the this.layoutmanager=true; and this.legacyobjects=false; to the content render file and restarted the application.  Then i removed the old version and added the FORM version.  It still doesn't send the email.  I also did check in the theme and there are no form objects.

**Comment by mattlevine** [comment]
If you have the layout manager on you shouldn't even see that tab in the admin anymore.

It's strange because the form submit method has the both end of the logic

Then formDataBean is set here:
https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/content/dataCollection/dataCollectionBean.cfc#L323

and the event is fired here:
https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/content/dataCollection/dataCollectionBean.cfc#L334

I would triple check that you don't have old/customized form/datacollection code in your theme or site.

You  may need to manually update your core by:

1. Back everything up, especially your config/settings.ini.cfm

2. Download the latest Mura standard and unzip it to your desktop

3. Copy everything by the "default" directory and paste it over your Mura root

4. If not on windows get your backed up config/settings.ini.cfm and restore it.

5. Make a request to your Mura root in the browser with your appreloadkey and applydbupdates in the url.  By default it would be http://domain.com/?appreload&applydbupdates

**Comment by Tigerlady** [comment]
Matt,  thanks for all the suggestions but it still isn't working.  Again i get the simple form fill email but not the custom email.  I did download the latest version and did an overwrite of the site and did an appreload and db update.  

I have also checked the files in the default and theme folders and do not see any obvious email filters.  I am a bit stuck at this point.

**Comment by mattlevine** [comment]
I you can provide me with ftp access to where this is happening I will take
a look.  You can just email me directly at matt.levine@blueriver.com

**Comment by mattlevine** [comment]
Please update both site and core and retest.  Makes sure to clear you browser cache as well.

-Matt

**Comment by Tigerlady** [comment]
Matt,  I just did an update of core and site.  The core updated a few files but the site didn't have any updated files.  When I fill in the form and hit submit it doesn't submit and if I hit submit again I get this. There was a problem verifying your form submission. Please contact the Site Administrator if the problem persists.  However, I did notice there is a cfabort in the event handler.  Should I remove this?

**Comment by mattlevine** [comment]
Yes, remove the abort from the eventHandler and retest. And double to clear your browser cache.

I'm not sure why you didn't get any site files updates.

Perhaps manually update this directory
https://github.com/blueriver/MuraCMS/tree/develop/default
/js/dist

**Comment by Tigerlady** [comment]
ok so i downloaded these files and then cleared cache.  I am still only getting the plain text email and not the one in the event handler.  This is just so strange.

**Comment by Tigerlady** [comment]
wait i take that back i just got the nice one.  now to cleaning it up.  but finally i got one.

**Comment by Tigerlady** [comment]
Thank you so much for fixing this.  I will have to wait till the weekend to update the live site but it is working now.
