### ISSUE TITLE
Mura 7 Boolean Support in Mura ORM

### ISSUE THREAD

**Issue by dbudde** [blueriver/MuraCMS#2534]
Creating a simple object, I came across a problem using data type 'boolean' with PostgreSQL.  The problems occurred during table creation and saving the bean to the DB.  As I tracked down each issue, I was able to figure out that alterations to 'dbUtility' in 'transformColumnMetaData' and 'transformDataType' as well as changes to 'beanORM' in 'getQueryParamType' would allow me to work with booleans correctly.

I have attached a small example of the bean I was using during my testing.
[survey.cfc.zip](https://github.com/blueriver/MuraCMS/files/815318/survey.cfc.zip)

The changes I propose making are:

1. The DB table creation error I was receiving was due to 'boolean' being unhandled in 'transformDataType' in the 'dbUtility.cfc' for a PostgreSQL DB.  Simply adding:

`<cfcase value="boolean">
	<cfreturn "boolean">
</cfcase>`

under the 'postgresql' case statement will make it so the column can be created without getting the default error message at the end of the function.

2. The second change I would propose is altering the 'transformColumnMetaData' method inside of 'dbUtility.cfc', since it is reading the table back into memory and is incorrectly identifying the boolean column as a varchar column.  The change I would suggest making is:

`<cfcase value="boolean">
	<cfset columnArgs.datatype="boolean">
</cfcase>`

This appears to correctly identify the column once it is read back into memory from the table.

3. The last change I would make would be to the 'getQueryParamType` method in the 'beanORM' component.  'boolean' is not a valid cfsqltype in ColdFusion, but 'bit' is.  Since ColdFusion represents booleans in a cfqueryparam by using bit, the I think it would be safe to translate a 'dataType' argument that is set to 'boolean' to 'bit'.   So, my suggested change in this case would be to alter 'getQueryParamType'

`private function getQueryParamType(datatype){
	if(arguments.datatype=='int'){
		return "cf_sql_integer";
	} else if (arguments.datatype=='boolean'){
		return "cf_sql_bit";
	} else {
		return "cf_sql_" & arguments.datatype;
	}
}`

Please let me know if you need me to supply any more detail.  I would be glad to.

Daniel

**Comment by mattlevine** [comment]
I had actually already put the first to in, but hadn't gotten around to testing.

https://github.com/blueriver/MuraCMS/commit/1d6b4095411f0fae0eb0468fa5875250ab70d514

**Comment by dbudde** [comment]
You are awesome!

**Comment by dbudde** [comment]
This seems to be working now when I update Mura.
