### ISSUE TITLE
Jquery Recursion & Mura 7 Layout

### ISSUE THREAD

**Issue by Tigerlady** [blueriver/MuraCMS#2545]
I posted this on the [Mura Google Group]([url](https://groups.google.com/forum/#!topic/mura-cms-developers/aIpg6pcpsYw)) but thought it should be raised as an issue here as well. 

When the Layout manager is turned on it wraps components in special code which causes issues with custom code. 

When I turn off the layout manager the code works as intended.  The thing is though I have already started developing other pieces using the layout manager and when it is turned off I no longer can edit the page content. 
```<div id="jssor_1" style="position: relative; margin: 0px auto; top: 0px; left: 0px; width: 1200px; height: 100px; overflow: hidden; visibility: visible;" jssor-slider="true">
<!-- Loading Screen -->


<div style="position: absolute; top: 0px; left: 0px; width: 1200px; height: 100px; transform-origin: 0px 0px 0px; transform: scale(1);"><div class="" style="position: relative; margin: 0px auto; top: 0px; left: 0px; width: 1200px; height: 100px; overflow: visible; visibility: visible; display: block;"><div data-u="loading" style="position: absolute; top: 0px; left: 0px; background-color: rgba(0, 0, 0, 0.7); width: 240px; height: 100px; display: none;">
<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
<div style="position:absolute;display:block;background:url('/default/assets/Image/Scroller-Img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
</div><div data-u="slides" style="cursor: default; position: absolute; top: 0px; left: 0px; width: 1200px; height: 100px; overflow: hidden; z-index: 0;"><div style="position: absolute; z-index: 0; pointer-events: none;"></div></div><div data-u="slides" style="cursor: default; position: absolute; top: 0px; left: 0px; width: 1200px; height: 100px; overflow: hidden; z-index: 0;"><div style="top: 0px; left: 0px; width: 240px; height: 100px; position: absolute; background-color: rgb(0, 0, 0); opacity: 0;"></div>
<div class="mura-object mura-async-object" data-object="component" data-objectid="Scroller Images" data-instanceid="4B4010D6-E565-453B-8B1D3B6BFF9537EA" data-render="server" data-async="false" data-objecticonclass="mi-clone" data-objectname="" style="z-index: 1; top: 0px; left: 0px; width: 240px; height: 100px; position: absolute; overflow: hidden;"><div class="mura-object-content" style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);">
<div style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"><a href="http://www.salientsys.com/" target="_blank" style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"><img alt="Salient Systems" data-u="image" src="/default/assets/Image/Scroller-Img/Salient-Systems.png" style="width: 330px; height: 76px; z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"></a></div>
<div style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"><img alt="Hirsch" data-u="image" src="/default/assets/Image/Scroller-Img/BBB7736C-B1F2-4E74-BE657370EBC039AA_medium.jpg" style="width: 200px; height: 200px; z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"></div>
<div style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"><img data-u="image" src="/default/assets/Image/Scroller-Img/bitly.jpg" style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"></div>
<div style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"><img data-u="image" src="/default/assets/Image/Scroller-Img/blogger.jpg" style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"></div>

<div style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"><img data-u="image" src="/default/assets/Image/Scroller-Img/youtube.jpg" style="z-index: 1; margin-top: 0px; margin-left: 0px; transform: translate3d(0px, 0px, 0px);"></div></div><div data-u="loading" style="position: absolute; top: 0px; left: 0px; background-color: rgba(0, 0, 0, 0.7); width: 240px; height: 100px; z-index: 1000; display: none;">
<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
<div style="position:absolute;display:block;background:url('/default/assets/Image/Scroller-Img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
</div></div>

</div></div></div></div>`

Here is the code that generates the above in the template.

`
<div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:1200px;height:100px;overflow:hidden;visibility:hidden;">
        <!-- Loading Screen -->
	        <div data-u="loading" style="position:absolute;top:0px;left:0px;background-color:rgba(0,0,0,0.7);">
	            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
	            <div style="position:absolute;display:block;background:url('/default/assets/Image/Scroller-Img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
	        </div>
        	<div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:1200px;height:100px;overflow:hidden;">
           		 #$.dspObject('component','Scroller Images')#
            
	        </div>
	    	</div>  
			</div>
			</div>  `

The above works but only if the layout manager is turned off.

**Comment by mattlevine** [comment]
It there any data in the chrome debugging console when the error happens?

**Comment by Tigerlady** [comment]
If I turn the layout manager off I do not see this. 

jssor.slider-22.2.10.mini.js:2 Uncaught RangeError: Maximum call stack size exceeded
    at Object.n [as a] (jssor.slider-22.2.10.mini.js:2)
    at T (jssor.slider-22.2.10.mini.js:2)
    at jssor.slider-22.2.10.mini.js:2
    at Object.n [as a] (jssor.slider-22.2.10.mini.js:2)
    at T (jssor.slider-22.2.10.mini.js:2)
    at jssor.slider-22.2.10.mini.js:2
    at Object.n [as a] (jssor.slider-22.2.10.mini.js:2)
    at T (jssor.slider-22.2.10.mini.js:2)
    at jssor.slider-22.2.10.mini.js:2
    at Object.n [as a] (jssor.slider-22.2.10.mini.js:2)
    at T (jssor.slider-22.2.10.mini.js:2)
n @ jssor.slider-22.2.10.mini.js:2
T @ jssor.slider-22.2.10.mini.js:2
(anonymous) @ jssor.slider-22.2.10.mini.js:2
n @ jssor.slider-22.2.10.mini.js:2
T @ jssor.slider-22.2.10.mini.js:2
(anonymous) @ jssor.slider-22.2.10.mini.js:2
n @ jssor.slider-22.2.10.mini.js:2
T @ jssor.slider-22.2.10.mini.js:2
(anonymous) @ jssor.slider-22.2.10.mini.js:2
n @ jssor.slider-22.2.10.mini.js:2
T @ jssor.slider-22.2.10.mini.js:2
E @ jssor.slider-22.2.10.mini.js:2
Bc.d.Yc @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2
Bc.d.zb @ jssor.slider-22.2.10.mini.js:2
G @ jssor.slider-22.2.10.mini.js:2
Bc.d.gg @ jssor.slider-22.2.10.mini.js:2
a.qc @ jssor.slider-22.2.10.mini.js:2
ab @ jssor.slider-22.2.10.mini.js:2
b @ jssor.slider-22.2.10.mini.js:2
P @ jssor.slider-22.2.10.mini.js:2

**Comment by mattlevine** [comment]
Would it be possible for you to switch to an unminifeid  version oft he slider js file and rerun it.

**Comment by Tigerlady** [comment]
Matt,  I am not sure I can actually attach a js file but going to try.  
  
 Also here is the error after running an unminified file.
 Uncaught RangeError: Maximum call stack size exceeded
    at T (jssor.slider.js:2402)
    at jssor.slider.js:2468
    at Object.n [as a] (jssor.slider.js:302)
    at T (jssor.slider.js:2429)
    at jssor.slider.js:2468
    at Object.n [as a] (jssor.slider.js:302)
    at T (jssor.slider.js:2429)
    at jssor.slider.js:2468
    at Object.n [as a] (jssor.slider.js:302)
    at T (jssor.slider.js:2429)
  
   Barbara ONeal
President/Co-Founder
Centric Web, Inc.
http://www.centricweb.com
630-541-9956

  

----------------------------------------

**Comment by Tigerlady** [comment]
I turned it into a txt file and now it work. 
[jssor.slider.txt](https://github.com/blueriver/MuraCMS/files/834830/jssor.slider.txt)

**Comment by Tigerlady** [comment]
Any good news on this?

**Comment by mattlevine** [comment]
Unfortunately, no.  Are you able to give me access to where it's happening?

**Comment by Tigerlady** [comment]
Sure do you have an email that I can send some credentials to?  I don't want to post them here on the message

**Comment by mattlevine** [comment]
matt.levine@blueriver.com

**Comment by mattlevine** [comment]
I'm not sure what the recursion is, but a workaround is to not use dspObject() for the component.  Instead directly load the content node  

```
#m.getBean('content').loadBy(title='component title').getbody()#
```
