### ISSUE TITLE
mura-[width] width in display objects not added

### ISSUE THREAD

**Issue by ekim2091** [blueriver/MuraCMS#2553]
mura-[width] 
The display object width attribute is not being appended to a display object that is rendered within a display region. 
Happening with collections and components

When rendered in a display region, in my case #$.dspObjects(2)# I get

> div class="mura-object mura-async-object" data-object="container"...

Instead of 

> div class="mura-async-object mura-object mura-object-select mura-six" data-object="container"...

when I drag it to the body content section #$.dspBody(body=$.content('body')...)# of my template

mura 7
Core Version 7.0.6943
Site Version 7.0.6921

**Comment by mubashirqayyum86** [comment]
did you find any solution?

**Comment by mattlevine** [comment]
I just tested locally without issue.  Perhaps update your core?

**Comment by mattlevine** [comment]
OK, I think I was able to replicate this issue.  Please update your core and retest.

https://github.com/blueriver/MuraCMS/commit/b670196754e642879499eb64f690618c6344542c
