### ISSUE TITLE
Mura 7 mixed https content in calendar and findCalendarItems request

### ISSUE THREAD

**Issue by CFJEFF** [blueriver/MuraCMS#2559]
I forcessl if an editor and logged in OR ALTERNATIVELY if you set the page to "Make this Calendar secure via SSL? " the calendar will fail in browsers that don't allow mixed content.   The findCalendarItems request from jquery doesn't use https although the rest of the page does.  

If you set "sitewide" ssl, then it will work and the findCalendarItems request uses https.

Core Version 7.0.6951
Site Version 7.0.6951
App Server ColdFusion (11,0,11,301867)
DB Server Microsoft SQL Server (Microsoft SQL Server 2008 R2 - 10.50.6000.34)
OS Version Windows Server 2008 R2 (6.1)

**Comment by mattlevine** [comment]
I think the bug is that we need to not allow partial ssl.  If you have ssl setup, you should use it for your entire site.  So the first two scenarios are deprecated. 

-Matt

**Comment by CFJEFF** [comment]
Point taken.
