### ISSUE TITLE
updated application.cfc or configBean.cfc not allowing DOI in URL for a link content type

### ISSUE THREAD

**Issue by brimard** [blueriver/MuraCMS#2594]
Suddenly getting a "The posted request contained restricted file types" error after updating the two core files when a URL in a link content type contains a DOI such as: http://journals.ametsoc.org/doi/abs/10.1175/BAMS-D-16-0103.1

Removing the period from the URL allows it to post, but obviously breaks the URL.

**Comment by mattlevine** [comment]
For security reason we add a list of default file extensions that would be allowed.

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/configBean.cfc#L186

For now, try setting this   in your /config/settings.ini.cfm and reload and retest:

FMAllowedExtensions=

-Matt

**Comment by brimard** [comment]
Matt, thanks for the quick reply and fix!
