### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by srtempleton** [blueriver/MuraCMS#2595]
Error on Installation using Oracle database
The value of parameter 3 of the function Mid, which is now -1, must be a non-negative integer
at cfdbUtility2ecfc1860695571$funcTRANSFORMCOLUMNMETADATA.runFunction(C:\webspace\requirements\mura\dbUtility.cfc:1038)

**Comment by mattlevine** [comment]
As a test can you please manually update this file

https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/dbUtility.cfc

and then make a request to your Mura root  ?appreload&applydbupdates in the URL

http://domain.com?appreload&applydbupdates

-Matt

**Comment by srtempleton** [comment]
Thanks,
That did the trick.

**Comment by mattlevine** [comment]
Awesome!
