### ISSUE TITLE
Unable to update Mura Core

### ISSUE THREAD

**Issue by mudassarhayee** [blueriver/MuraCMS#2611]
I get this message when trying to update Mura Core.

"An Error has occurred.

The current production version data is currently not available. Please try again later. "

I am running coldfusion 2016 on localhost

**Comment by mattlevine** [comment]
If you have problems with the auto-updater I would just do a manual update following these instructions:

1. Back everything up, especially your config/settings.ini.cfm

2. Download the latest Mura standard and unzip it to your desktop

3. Copy everything by the "default" directory and paste it over your Mura root

4. If not on windows get your backed up config/settings.ini.cfm and restore it.

5. Make a request to your Mura root in the browser with your appreloadkey and applydbupdates in the url.  By default it would be http://domain.com/?appreload&applydbupdates

**Comment by mudassarhayee** [comment]
Hi Matt,

I am running ColdFusion 9 and I think the latest version of Mura requires
ColdFusion 10+.

How will I be able to transfer my website to the latest version of Mura?
My current version of Mura is 6.

Will i need to do a fresh install? How will I be able to transfer the old
site to the new version?

Thank you,
Mudassar

**Comment by mattlevine** [comment]
You can just move all the files to a new CF instance with a datasource of the same name pointing ar you existing database and auto update or manually update.

And if you run into any issues you can manually update by:

1. Back everything up, especially your config/settings.ini.cfm

2. Download the latest Mura standard and unzip it to your desktop

3. Copy everything by the "default" directory and paste it over your Mura root

4. If not on windows get your backed up config/settings.ini.cfm and restore it.

5. Make a request to your Mura root in the browser with your appreloadkey and applydbupdates in the url.  By default it would be http://domain.com/?appreload&applydbupdates
