### ISSUE TITLE
Mura ORM property validate attribute

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2614]
I tried to use the "validate" attribute for a property, as described in the Mura 7 [documentation](http://docs.getmura.com/v7/mura-developers/mura-beans-objects/custom-objects/mura-orm/mura-orm-entity/). It was ignored, and I don't see it being taken into account in `bean.getValidations()`. Is this implemented at all ?

**Comment by mattlevine** [comment]
Did you reload after making the change? Also, can you provide example code of what you did?

**Comment by damien-git** [comment]
Yes, I used `?appreload&applydbupdates`.

Here is an example:
```
    property name="externalBinding" datatype="varchar" length="15" required=false
        validate="regex" regex="^\d+\.\d+\.\d+\.\d+$";

```

I don't understand what you mean about a "category", but I have only tried it as a superuser.

**Comment by damien-git** [comment]
To save the bean I use something like this. I do get errors for property types.
```
 try {
  site.set('externalBinding', form.externalBinding);
  var result = site.save();
  var errors = result.get('errors');
  if (isDefined('errors') && structCount(errors)) {
    // handling errors
  }
} catch (any e) {
  // handling errors
}
```

**Comment by mattlevine** [comment]
Please update and retest.  Also just to make sure, is your "site" entity a custom entity?

Also, one technique that I use alot when it comes to validation is to just override the validate method with something like:

```
function validate(){
    super.validate(argumentCollection=arguments);

   if(![validation logic]){
        getErrors().mycustomerror="My custom error message";
    }
}
```

thanks,
-Matt

**Comment by damien-git** [comment]
Yes, my "site" is a custom entity. I am aware of the possibility to add custom validation, but I thought I would use Mura's features as much as I could.

You fixed it for regex, but (just to make sure you are aware of it) there are other values for the validate attribute which are still not handled (you did not add them to basicRules yet):  date, datetime, numeric, email, url.

Thanks.

**Comment by mattlevine** [comment]
Thanks for pointing that out.  Those don't work quite the same as the others.  Date, datetime, numeric would typically be validated against the datatype but there was definitely a problem that should be fixed now.

-Matt

**Comment by damien-git** [comment]
I tested with email and it worked. Thanks for fixing this.
