### ISSUE TITLE
Mura action menu items stay gray during hover

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2615]
With collections and users (possibly others in the admin area), action menu items stay gray during mouse hover. It does not happen with content.
I used the following CSS to work around it in a plugin, but a fix in Mura would be better:
```
ul.actions-list>li>a:hover {
    color: #545454 !important;
    i:before {
        color: #545454 !important;
    }
}
```

**Comment by mattlevine** [comment]
This commit should fix that

https://github.com/blueriver/MuraCMS/issues/2615
