### ISSUE TITLE
Select/Search New Parent Does Not Show File/Default Types

### ISSUE THREAD

**Issue by encipherdesign** [blueriver/MuraCMS#2618]
I am nesting the File/Default types to create a gallery of additional views of the parent File. 
![image](https://user-images.githubusercontent.com/4871682/28228966-a202fec0-6895-11e7-8349-c5c48a9de710.png)

When I need to move a File to a different Parent File, the Select New Parent returns no results when searching the File by exact Name or Title.

![image](https://user-images.githubusercontent.com/4871682/28228888-4131ec64-6895-11e7-9d2e-d798b9aeade5.png)

Searches for other Types (Folders/Pages) do appear. Allowing to search for specific types would be helpful. LMK if you need more info.

**Comment by mattlevine** [comment]
Please update and retest.

**Comment by encipherdesign** [comment]
thanks for the quick fix!
