### ISSUE TITLE
Update to version 7.0.7022 breaks inline editing

### ISSUE THREAD

**Issue by tbugler** [blueriver/MuraCMS#2620]
Updated core to version 7.0.7022 and I can no longer activate inline editing. Console error shows:

Uncaught ReferenceError: CKEDITOR is not defined
    at Object.init (frontendtools.js.cfm:575)
    at HTMLAnchorElement.onclick (site.localhost/:541) 

Second site same error - last line references line 483

Tested update on two sites.

**Comment by encipherdesign** [comment]
i get the same error. the ckeditor.js is not is not loading after this update.

the script path is called from the root at  '/vendor/ckeditor/ckeditor.js' with no resolution or redirect.
$.getScript(**'#variables.$.globalConfig("corepath")#**/vendor/ckeditor/ckeditor.js'); is corepath meant to return an empty string?

**Comment by mattlevine** [comment]
Please update and retest.

**Comment by tbugler** [comment]
Working now as expected - thanks!
