### ISSUE TITLE
Forgot Password redirect URL not working

### ISSUE THREAD

**Issue by matthewfair** [blueriver/MuraCMS#2622]
We now have 3 Mura 7 sites where the URL that is emailed when the user completes the forgot password form takes the user to a 404 page.  CF10.

**Comment by mattlevine** [comment]
Ah, thanks for pointing that out!

**Comment by matthewfair** [comment]
No, it happens the first time the link is clicked, which is strange.  I understand the need to keep the tredirects table clean and also the need for security to kill the redirect once it has been used.  I wish I could come up with a way to do it all.
