### ISSUE TITLE
Change set changes not showing in related pages on site

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2624]
Hi chaps,

We have some functionality on one of our sites that is behaving not quite as I would expect, let me explain...

We have a page, which contains 'master content', a descriptive field, and some other meta info settings. 

We then have some child pages, which have their own settings, mainly some dates/times.

When we view a child page, the descriptive field, and the meta info is pulled in from the parent page through some custom rendering. 

So, into the field come Change Sets... 

So create a new change set, and make an edit to the parent page.

Preview the change set, view the child page, the updated information from the parent page is *not* visible. 

I assume this is coming from the use of $.getParent() not honouring the changeset that is being viewed at the time. My feeling is that this is not desirable behaviour, certainly not what the CMS users are expecting.

Interestingly, if you update a child page to a folder, and preview the change set, it appears to be working fine.

All help appreciated :)

Thanks,

Peter.

**Comment by mattlevine** [comment]
I think it may be a caching issue.  When you using $.getParent() is actually populates the returned contentNavBean with data from the crumb list.  As a test please tweak your code to use $.content().getParent() instead.  

-Matt

**Comment by PeterBowater** [comment]
@mattlevine , you star, that does indeed fix it! 👍 

Many thanks,

Peter.
