### ISSUE TITLE
Mura ORM: double type rounded to integer with mssql

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2626]
dbUtility.cfc returns "Decimal" in the case of mssql for the double type. It should give a precision, otherwise it is an integer.
By the way, applydbupdates doesn't update the datatype in the database. Is there a way to do that from Mura so I can fix my database automatically once this issue is resolved ?

**Comment by mattlevine** [comment]
What is your datatype for the ORM property set to?

-Matt

**Comment by damien-git** [comment]
double

**Comment by mattlevine** [comment]
So basically in MSSQL it's a float,  why not use float?

If you manually update this file it may work:
https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/dbUtility.cfc

**Comment by damien-git** [comment]
I wanted a higher precision than float (but not the "float" of MSSQL, which is a double by default). I was thinking the type I define with Mura is independant of the underlying database, which may change. Actually, it would be nice if the documentation explained what "float" and "double" mean for Mura.
Your fix worked. I had to delete the tables to test.
