### ISSUE TITLE
URL Rewrite - No trailing slashes added.

### ISSUE THREAD

**Issue by awalczak** [blueriver/MuraCMS#2661]
I've deployed a site bundle on the newest docker image of Mura. When I visit a URL with no backslash on the end, there is no URL redirect. Instead I get a 404 that the page isn't found.

Is this a tomcat issue? Can I edit these settings somewhere in Mura's core files? Please let me know.

**Comment by mattlevine** [comment]
Just to confirm, this is the image you are using?

https://hub.docker.com/r/blueriver/muracms/

**Comment by awalczak** [comment]
Correct, this is the version I am using. The bundle was made in Mura 7.0. Are there older docker images I can use compatible with 7.0? That would be a huge help.

**Comment by stevewithington** [comment]
@awalczak did you have the issue prior to deploying the bundle? Is your site bundle accessible somewhere for testing?

**Comment by awalczak** [comment]
I haven't had this issue before. Whats the best way to send it/for you to access it.

**Comment by stevewithington** [comment]
Can you zip it up and post it somewhere? Even if temporarily?

**Comment by awalczak** [comment]
I shared a private repo. Let me know if it's not accessible.

**Comment by stevewithington** [comment]
@awalczak Can you post, or send me a copy of the `Dockerfile` and `docker-compose.yml` files you're using?

**Comment by stevewithington** [comment]
@awalczak hold tight ... I was finally able to replicate this issue and am working on it. Thanks!

**Comment by mattlevine** [comment]
Please pull down the latest image and restart the container with:

  MURA_INDEXFILEINURLS: "false"

https://github.com/blueriver/MuraCMS/commit/0eb44ad4818f9e089c78152207cc555ba595b6bb

**Comment by awalczak** [comment]
Worked! Thank you!
