### ISSUE TITLE
Link Dialog no longer working 

### ISSUE THREAD

**Issue by kucits** [blueriver/MuraCMS#2665]
Since updating the Link dialog box no longer retains the existing link information, not can I change an existing link. I can create a new link, but that is all.

Also,  interface of the link dialog by default is showing all three options (url, email and anchor) when it first opens. This is happening on 3 sites I've updated.

I can only manually update links via the source code.

![screenshotatuploadcc_1508239616137](https://user-images.githubusercontent.com/32268291/31662508-9ef180d2-b30c-11e7-9c91-62d5298a7a46.png)

Mura 7.0.7044 & 7.0.7045
Lucee 5.2.4
Win Server 2012 R2

**Comment by kucits** [comment]
I do have once site that is running 7.0.7044 and the dialog box is functioning properly; however the site version is 7.0.736. I'll make a clone of the site and update and see if the site  update breaks the dialog box.

**Comment by kucits** [comment]
I can confirm any site/core pre 7.0.7044  the dialog box for links acts as expected. Updating core and site seems to break something. I did notice that in sites after 7.0.742 the ckeditor folder under requirements has extra dailog.css files for ie, ie7, ie8 and opera. Other than that I don't seen any differences.

Restroring the ckeditor directory to a previous version fixes the issue.

**Comment by gowestweb** [comment]
Are you seeing any javascript errors when the weird behavior occurs?

**Comment by kucits** [comment]
no javascript errors. Disabled caching - same issue. This has cropped up on 4 site across three different servers. Tried clear cache, clearing server cache - even went so far as to restart the server. Only fix was to revert to a previous install of ckeditor (from 7.0.7042).

**Comment by seanschroeder** [comment]
I also found this error today, coincidentally. We’ll take a look.

**Comment by kucits** [comment]
I've narrowed it down to the config.js.cfm file. If I replace that with a previous version everything works correctly. Was their a change to the ckeditor config,js.cfm file after 7.0.4.042?

**Comment by gowestweb** [comment]
I'll push up a fix for this shortly. @kucits  I did modify the ckeditor config file (config.js.cfm) in order to center the dialog windows when using the front end "Full Edit" mode. However, I was overriding the default onShow() behavior for the link dialog, now I have it appending our logic to the default method so links are centered and still usable. Thanks for pointing it out.
