### ISSUE TITLE
API issue for feed showNavOnly, includeHomePage, showExcludeSearch

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2666]
The [documentation ](http://docs.getmura.com/v7/mura-developers/mura-beans-objects/common-bean-objects/feed-bean/) states that `includeHomePage`, `showNavOnly` and `showExcludeSearch` are booleans.
Yet, using `feedBean.setShowNavOnly(false)` does not work, because `feedBean.setShowNavOnly()` only sets the value if it is numeric. Similarly, it looks like the code assumes that the others are also numeric (there might be others, I was only using these properties).

**Comment by stevewithington** [comment]
@damien-git thanks for the heads up...we'll take a look.
