### ISSUE TITLE
Disappearing Display Objects

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2685]
We noticed that after a day or two, components and display objects were disappearing on our site. Only an application reload would bring them back.
The source code had errors like that:
`<!-- The requested file 'component/index.cfm' could not be found.-->`
Not all components or display objects were disappearing, but that seemed random.

The error seemed to happen in `settingsBean.lookupDisplayObjectFilePath`. Debugging that, I found that Mura was looking for `mura7\admin\core\views\carch\objectclass\component\index.cfm`, and not finding it.
We were able to trigger the error by simply using plugins on the admin side (most of them are based on the github MuraPlugin project, some are using FW1). I noticed that just looking at a plugin based on MuraPlugin (with the same Application.cfc) was triggering `settingsBean.init()` for all sites. This reinitializes `displayObjectFilePathLookup`.

I am guessing there might be 2 bugs here:
1) merely using a plugin should not reinitialize the settings bean.
2) sometimes, Mura looks at the wrong place for display objects or components. When it does, the empty path is cached in `displayObjectFilePathLookup`, so they keep missing afterwards.

**Comment by damien-git** [comment]
Just to clarify: when `component/index.cfm` is not found in `settingsBean.lookupDisplayObjectFilePath`, the only entry in `displayObjectLoopUpArray` is `/muraWRM//admin/core/views/carch/objectclass\`.

**Comment by damien-git** [comment]
Some other observations:
- sometimes other files are missing, for instance `dsp_template.cfm` or `object/meta.cfm`
- we can easily reproduce the bug by opening a plugin on admin while another user loads a page on the site
- there is a unique set of missing components for each user

**Comment by stevewithington** [comment]
@damien-git, thanks for the details ... we'll take a look.

**Comment by stevewithington** [comment]
@damien-git, I tried duplicating your issue, and unfortunately, I'm unable to on my end. That said, I've taken a look at [MuraPlugin](https://github.com/stevewithington/MuraPlugin), and made some adjustments to the `Application.cfc` regarding reloading the application, which may be impacting things. So, if you could try updating [that file](https://github.com/stevewithington/MuraPlugin/blob/develop/Application.cfc), reload, and then see if that makes any difference. Thanks!

**Comment by damien-git** [comment]
Thanks ! We tried with the old and the new version. With the old one, we get a bug right away. We don't with the new one, and the plugin shows up a lot faster. So I think that fixes bug 1). But could bug 2) happen without 1), for instance if the plugin uses reloadApplicationOnEveryRequest ?

**Comment by damien-git** [comment]
We did another test, trying to see if an application reload triggered manually from admin would cause the bug. It did not cause any bug.

**Comment by stevewithington** [comment]
@damien-git, thanks for testing, and the feedback. Since I'm unable to replicate your issue, I'm unable to answer the 2nd part of your question, regarding setting `reloadApplicationOnEveryRequest` to `true`. I suspect it might cause your issue to reappear. However, that setting is in place for development purposes only, and not intended to be set to `true` for production, so I would mark that lower on the priority list at this point. Since it appears the plugin was causing the issue, I'll mark this as `closed` for now. If I've missed something, or you disagree, please feel free to reopen! Thanks.
