### ISSUE TITLE
Can't save after adding properties (Custom Content / ORM)

### ISSUE THREAD

**Issue by bowler865** [blueriver/MuraCMS#2688]
I created a new entity called "Champions". ChampionsID and SiteID were automatically there to start. I added "firstname" and "lastname" properties and clicked "Save". The green bar confirming save appeared at the top of the page. Then I created a new Entity, called "Titles", added properties, saved, everything seemed fine. I added a "championsid" field, setup a many-to-one relationship with the championsid of the Champions entity. Saved, all seemed good.

I went back into "Champions" to add a "remoteID" property for importing purposes and only championsid and siteid were visible in the Properties sidebar. Refreshing made the First Name and Last Name properties appear. I added the remoteid property, saved, everything seemed fine but now that I think about it I'm not sure the green confirmation alert appeared at the top of the page as every time I try to add a property now it does not show a confirmation message. I looked for a response in the network tab but there is nothing that contains an error.

The firstname and lastname columns were created in dyn_champions but the remoteID column was never created.

I tried reloading Mura, nothing helps this issue while using the ORM Module.

Updating the entity record in the "tentity" table (added firstname, lastname and remoteid) gets reflected in the Custom content editor and the column was created in the dyn_champions following a reload.

Same issue now if I try to add any properties to to the "Titles" Entity using the Entity Editor. The property is created after clicking "Add Property" on the "Add Property" screen but then the "Save" button on the "Edit Entity" page does nothing.

**Comment by mattlevine** [comment]
Can you try doing  a ?appreload&applydbupdates  request.  I doubt it will be the fix, but it's worth a test.

**Comment by bowler865** [comment]
Here's the response for clicking "save" after editing (in this case I deleted a property).

error	{…}
message	Unhandled Exception
code	server_error
stacktrace	{…}
extended_info	
message	
queryerror	ALTER TABLE dyn_titles ADD COL… default ''
sql	ALTER TABLE dyn_titles ADD COL… default ''
detail	Invalid default value for 'titledate'
sqlstate	42000
additional	{…}
sql	ALTER TABLE dyn_titles ADD COL… default ''
databasename	MySQL
databaseversion	5.7.10
drivername	MySQL Connector Java
driverversion	mysql-connector-java-5.1.38 ( …39c74cc727c5da96c1028b4834a )
datasource	neba_mura_dsn
tagcontext	[…]
0	{…}
raw_trace	dbutility_cfc$cf.udfCall2(/mura/dbUtility.cfc:323)
codeprintplain	321: </cfif> 322: </c… <cfcase value="postgresql">
column	0
line	323
template	C:\home\website.com\website\core\mura\dbUtility.cfc
id	??
type	cfml
codeprinthtml	321: &lt;/cfif&gt;<br> 32…uot;postgresql&quot;&gt;<br>
1	{…}
raw_trace	bean.beanorm_cfc$cf.udfCall2(/mura/bean/beanORM.cfc:245)
codeprintplain	243: for(var prop in props)…s(props[prop],"fieldtype")){
column	0
line	245
template	C:\home\website.com\website\core\mura\bean\beanORM.cfc
id	??
type	cfml
codeprinthtml	243: for(var prop in props)…&quot;fieldtype&quot;)){<br>
2	{…}
raw_trace	configbean_cfc$cf.udfCallk(/mura/configBean.cfc:1908)
codeprintplain	1906: 1907: <cfif checkSc…()> 1909: </cfif> 1910:
column	0
line	1908
template	C:\home\website.com\website\core\mura\configBean.cfc
id	??
type	cfml
codeprinthtml	1906: <br> 1907: &lt;cfif …&lt;/cfif&gt;<br> 1910: <br>
3	{…}
raw_trace	bean.beanfactory_cfc$cf.udfCal…ura/bean/beanFactory.cfc:215)
codeprintplain	213: moduleid="00000… ); 216: } 217:
column	0
line	215
template	C:\home\website.com\website\core\mura\bean\beanFactory.cfc
id	??
type	cfml
codeprinthtml	213: moduleid=&quot;…> 216: }<br> 217: <br>
4	{…}
raw_trace	bean.beanfactory_cfc$cf.udfCal…ura/bean/beanFactory.cfc:122)
codeprintplain	120: 121: var rsSit… 124: return this;
column	0
line	122
template	C:\home\website.com\website\core\mura\bean\beanFactory.cfc
id	??
type	cfml
codeprinthtml	120: <br> 121: var r…: return this;<br>
5	{…}
raw_trace	client.api.json.v1.apiutility_…i/json/v1/apiUtility.cfc:157)
codeprintplain	155: param name="obj.publi….appInitialized=false; 159:
column	0
line	157
template	C:\home\website.com\website\cor…nt\api\json\v1\apiUtility.cfc
id	??
type	cfml
codeprinthtml	155: param name=&quot;obj.…ialized=false;<br> 159: <br>
6	{…}
raw_trace	client.api.json.v1.apiutility_…i/json/v1/apiUtility.cfc:682)
codeprintplain	680: if(isDefined('#params…4: if(!isJson(result)){
column	0
line	682
template	C:\home\website.com\website\cor…nt\api\json\v1\apiUtility.cfc
id	??
type	cfml
codeprinthtml	680: if(isDefined('#params… if(!isJson(result)){<br>
7	{…}
raw_trace	content.contentserver_cfc$cf.u…ontent/contentServer.cfc:528)
codeprintplain	526: <cfset request.muraAPIR…cessRequest(arguments.path)>
column	0
line	528
template	C:\home\website.com\website\cor…ura\content\contentServer.cfc
id	??
type	cfml
codeprinthtml	526: &lt;cfset request.muraA…uest(arguments.path)&gt;<br>
8	{…}
raw_trace	content.contentserver_cfc$cf.u…ontent/contentServer.cfc:667)
codeprintplain	665: 666: <cfif listFindNoCa…(path)> 668: <cfelse> 669:
column	0
line	667
template	C:\home\website.com\website\cor…ura\content\contentServer.cfc
id	??
type	cfml
codeprinthtml	665: <br> 666: &lt;cfif listF…&lt;cfelse&gt;<br> 669: <br>
9	{…}
raw_trace	index_cfm$cf.call(/index.cfm:46)
codeprintplain	44: modified version; it is yo…dleRootRequest()#</cfoutput>
column	0
line	46
template	C:\home\website.com\website\index.cfm
id	??
type	cfml
codeprinthtml	44: modified version; it is yo…()#&lt;/cfoutput&gt;</b><br>
errorcode	0
nativeerrorcode	1067
type	database
datasource	neba_mura_dsn
stacktrace	lucee.runtime.exp.DatabaseExce…Thread.run(Thread.java:745)
where	
extendedinfo	
params	{…}
csrf_token	59A9F3979BF551E0F3925F0BE2B49EEB
siteid	bowlneba
csrf_token_expires	171113194323878
fieldnames	method,entityConfig,csrf_token,csrf_token_expires
entityconfig	%7B%22entityname%22%3A%22title…%22dynamic%22%3A%22true%22%7D
method	declareEntity
apiversion	v1

**Comment by mattlevine** [comment]
Is the 'titledate' field not allowed to have null values?  And did you
remove any fields that were not allowed to have null values?

**Comment by bowler865** [comment]
Unfortunately that is a different issue I created by editing the entity code in the tentity table.

property name="titledate" required=false orderno="5" rendertype="textfield" displayname="Title Date" html=false datatype="datetime" default="";

I tried [m]now()[/m] for the default value but that didn't work. If I wanted the current date/time as the default value, what would I enter?

I removed that line from the code column of the titles row in tentity to get that out of the way for now. I went into "titles" in the "custom" content editor, added "something" property, not required, varchar, textfield, etc. Click "add" it shows up in the properties sidebar with the others. Clicking save does nothing at all, doesn't initiate anything, nothing happens in the network panel, it's like the button is disabled.

**Comment by mattlevine** [comment]
Please update and retest.

https://github.com/blueriver/MuraCMS/commit/a3dbaa60ca8810a734292ba06b72dda5be4cae0b

Unfortunately, for now the only default value that is supported is either now or now() and it gets applied within the component and not in the db.

**Comment by bowler865** [comment]
Matt,

I did the update and now when I remove default="" from the property in the "code" column of the tentity table, appreload&applydbupdates the column gets created in dyn_titles and I can see it in the properties of the custom content object "Titles" in the Mura admin.

However, I still cannot add any kind of property to any entity, after doing so the save button does nothing.

Sorry to repeat myself, and to muddy up the bug report with two different things going on. One down, one to go.

Thanks,
Scott

**Comment by grantshepert** [comment]
There were a couple of issues here, mostly related to the sorting. Update and retest. 

Note that it is still important to update Mura whenever you *update* a dynamic object (every time you hit SAVE). This is due to a separate issue yet to be resolved.

**Comment by bowler865** [comment]
Grant,

Works perfectly now, thanks!

-Scott
