### ISSUE TITLE
Extra menu items in CKEditor's Styles menu on frontend

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2690]
We have been seeing extra menu items in CKEditor's Styles menu when using inline edit. They don't match anything specified in js/editor/styles.js or the styles.js in Mura requirements, and look pretty bad.

I found that they were created by the stylesheetparser CKEditor plugin. Removing it from config.extraPlugins fixes the issue.

**Comment by cfmitrah** [comment]
@grantshepert 
I've tested this, found the mentioned issue in in-line editing for CK-editor style menu items.
I noticed the above comments "Removing it from config.extraPlugins fixes the issue".  So I identified the file in **requirements\ckeditor\config.js.cfm**  line#173

config.extraPlugins = 'SelectComponent,Selectlink,leaflet,tableresize,onchange,justify,find,bidi,div,showblocks,forms,templates,pagebreak,codemirror,widget,lineutils,dialog,oembed,sourcedialog,fakeobjects,dialogui,showprotected,**stylesheetparser**,balloonpanel,a11ychecker';

I removed the **stylesheetparser** list values from the above line. And tested the same now the issue has been fixed.

**Comment by mattlevine** [comment]
Thanks for pointing that out!

**Comment by cfmitrah** [comment]
can we create a pull request for these?

**Comment by mattlevine** [comment]
What other issues with the config have you found.  I'll need to review them with internal resources that may use them in specific ways.  If you did do a pull request it would highlight the issues.

**Comment by cfmitrah** [comment]
As of now, only issue we came across was mentioned by  **damien-git in original issue.**

**Comment by damien-git** [comment]
I think this bug is fixed. Closing it.
