### ISSUE TITLE
encoding problem with import of class extensions

### ISSUE THREAD

**Issue by j-herden** [blueriver/MuraCMS#2691]
Having an umlaut in the description of a class extension creates two wrong characters after the import.
I used this file:
`
<?xml version="1.0" encoding="UTF-8"?>
	<mura xmlns="">
		<extensions xmlns="">
			<extension adminonly="0" availablesubtypes="" basekeyfield="contentHistID" basetable="tcontent" datatable="tclassextenddata" description="Ersatz für 'goto first child'" hasassocfile="1" hasbody="0" hasconfigurator="0" hassummary="1" iconclass="mi-hand-o-right" subtype="firstchild" type="Page" xmlns=""/>
		</extensions>
	</mura>
`

**Comment by David-Polehonski** [comment]
Can you provide a sample import file and/or confim the import file is in UTF-8?

**Comment by j-herden** [comment]
I can not reproduce this error anymore. 
I assume that I have created a XML-file which was not encode in UTF-8.
