### ISSUE TITLE
No contextual menu in CKEditor with inline edit

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2692]
CKEditor has no contextual menu with inline edit. This is particularly bad for tables, because there is no toolbar to edit them. It becomes impossible to add a new table row.

The bug seems to come from the codemirror plugin:
https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/issues/91

Updating to a new version of it fixes the issue.

**Comment by stevewithington** [comment]
fix submitted. thanks.
