### ISSUE TITLE
New Feature for Mura CMS

### ISSUE THREAD

**Issue by gavyjatt** [blueriver/MuraCMS#2695]
Hi, it is a enhancement request rather than a comment, I worked with wordpress and usually see you can just add the wordpress complete website to the wordpress blog and it just creates a seperate site itself, Mura themes are just themes, no working functionality, while wordpress themes has complete working functionality and there are just couple of settings which needs to be done. 

Is there any way we can make mura like wordpress 

Well, I will say that something it is very hard to find data in wordpress with custom themes because they build in such a manner that it is harder for noivoice developer to find and fix something

**Comment by PeterBowater** [comment]
I'm not that clear what you mean here - no working functionality in themes?
You can do very, very complex stuff in themes.

**Comment by seanschroeder** [comment]
I think what you’re looking for are what we call site bundles in Mura. Site bundles include the theme and a completely pre-wired site. Check our theme downloads and select everything when installing it. Hope this is helpful!

**Comment by stevewithington** [comment]
@gavyjatt As @seanschroeder pointed out, I'm pretty sure you're looking for a "Mura Bundle" which includes content, etc. so you can deploy a theme with all of its class extensions, custom display objects, etc.  You might be interested in looking at https://github.com/blueriver/MuraBootstrap4Bundle and https://github.com/blueriver/MuraBootstrap3Bundle, as well as checking out our themes at http://www.getmura.com/downloads/mura-cms-themes/. Just be sure that when importing a bundle, you check the box next to "Site Architecture and Content". You can learn how to deploy/install a site bundle at http://docs.getmura.com/v7/theme-developers/where-to-start/site-bundles/how-to-deploy-install-a-site-bundle/. Cheers!
