### ISSUE TITLE
Related Content - set sort by and order

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2722]
Hey guys,

Hoping you can help... having a bit of trouble getting Related Content back in the order I am expecting, using either:

<cfset relatedQry = $.content().getRelatedContentQuery(name='Equipment', reverse="true", sortBy="afieldname", sortOrder="asc")>
or
<cfset relatedIt = $.content().getRelatedContentIterator(name='Equipment', reverse="true", sortBy="afieldname", sortOrder="asc")>

Is this possible in current form? I can't get the above to work at the moment.

The getRelatedContent() functions in contentNavBean, contentManager, and contentGateway CFCs seem to suggest that it would be possible, no dice.

Am I doing anything wrong or is there a but going on here?

Many thanks,

Peter.

**Comment by grantshepert** [comment]
It should be sortDirection, not sortOrder. Also, is there a specific reason you aren't just using getRelatedContent() instead of the more specific functions?

**Comment by PeterBowater** [comment]
Thanks @grantshepert , yup, my bad on the direction, had mucked about with it so much had missed that mistake.

I've just tried the $.content().getRelatedContent(name='equipment'), with and without 'reverse="true"', and with and without the 'name' from the corresponding content items, and only an empty string is being returned.

I dumped out $.content() and the function is not there.

Reason for trying both query and iterator types is because I have been using both, iterators where simple, and queries so I can easily join them to other queries to aggregate results.

Thanks for the help, Grant :)

Peter.
T

**Comment by stevewithington** [comment]
@PeterBowater what field name are you attempting to order by?

**Comment by stevewithington** [comment]
@PeterBowater also, if you call `reverse`, then I believe it uses the `local` sort order, but just in reverse.

**Comment by PeterBowater** [comment]
Hey Steve, I have an extended attribute called 'squadronOrdering', but have also tried using 'menuTitle' in testing, with same results.

So: 

<cfset relatedIt = $.content().getRelatedContentIterator(name='Equipment', reverse="true", sortBy="menuTitle", sortOrder="asc")>

**Comment by stevewithington** [comment]
@PeterBowater then I believe that's part of your issue ... drop the `reverse` argument. Also, I don't believe it's set up for sorting on an extended attribute at this time.

**Comment by PeterBowater** [comment]
Thanks @stevewithington , yes, reverse does a reverse lookup, i.e. finds which content items this content is related to, very handy for us, as we don't have to do relate stuff twice :)

**Comment by stevewithington** [comment]
@PeterBowater ok

**Comment by stevewithington** [comment]
@PeterBowater I just double-checked, and it doesn't look like we currently allow sorting by an extended attribute.

**Comment by PeterBowater** [comment]
OK, thanks @stevewithington , any ideas why sorting on menuTitle doesn't work either?

Would it be tricky to order by EA?

**Comment by stevewithington** [comment]
These are the fields currently allowed for `menutitle, title, lastupdate, releasedate, displaystart, displaystop, created, tcontent.credits, type, subtype, orderno, rating, comments`

**Comment by stevewithington** [comment]
If `sortBy` is omitted, then it defaults to using `tcontent.orderno asc`

**Comment by stevewithington** [comment]
What CFML engine and version are you using?

**Comment by PeterBowater** [comment]
OK brill, and actually,  just tried again with menutitle, and appears to work, perhaps I got caught by the sortby issue Grant picked me up on.

Lucee 5.1

**Comment by stevewithington** [comment]
Ok ... so it's working with the allowed fields. Good.

As for re-ordering based on an extended attribute, you'd probably have to get the query, loop over the items and append the extended attribute to the query, and resort ... then you could use the new query to seed the `contentIterator` bean.

**Comment by stevewithington** [comment]
@PeterBowater here's a Gist I did something similar with once: https://gist.github.com/stevewithington/4446892

**Comment by stevewithington** [comment]
Since this doesn't appear to be an actual bug at this time, I'm going to close it. Feel free to reopen if you find some other issue/s. Thanks!

**Comment by PeterBowater** [comment]
Thanks very much @stevewithington , agree closed.
