### ISSUE TITLE
Folder "content_types" with a subtype that contains a space

### ISSUE THREAD

**Issue by boris-schwarz** [blueriver/MuraCMS#2747]
I have created a subtype "Page/News Module" in my eventHandler.cfc.

Now creating a folder "/default/includes/content_types/page_news module/" doesn't work.

When I rename the subtype to "Page/NewsModule" and removing the space from the folder "page_newsmodule" it works.

**Comment by boris-schwarz** [comment]
Oh, you can close this error... Seems like contentRendererUtility.lookupCustomContentTypeBody() seems to strip out spaces and other non-alphanumerical characters:

`<cfset var safesubtype=REReplace(arguments.$.content().getSubType(), "[^a-zA-Z0-9_]", "", "ALL")>`

So when having a subtype "Page/News Module", just name the folder "Page_NewsModule".

**Comment by PeterBowater** [comment]
Yup, figured that out myself a while ago, I think it makes sense when you think about it, but couldn't find it in the docs at the time (was when 7 was in beta IIRC)

**Comment by PeterBowater** [comment]
@boris-schwarz , if this is issue is now finished with, could you close it?

**Comment by boris-schwarz** [comment]
Sure, thanks for the hint.
