### ISSUE TITLE
Mura ORM: saving a draft does not make it active

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2758]
When editing a draft content bean (which I am finding using a feed with setLiveOnly(0)) and using .save(), the new draft is saved but not made active, even when I use .setActive(1). So a user editing the content will get the old version (with a warning that there is a newer draft).

It looks like a bug, because this does not happen with non-draft content.

**Comment by mattlevine** [comment]
Use setApproved(1) instead of setActive(1)

**Comment by mattlevine** [comment]
Then set content.setDisplay(0);  It is not possible to make the active content something other than the currently published version.  They are synonymous.

**Comment by damien-git** [comment]
When I click on a draft in tree view, I get to edit one of the different versions. I thought the way Mura was choosing which one gets edited is by selecting the one with active=1 (I noticed that difference by looking at the database). If this is not the case, then I don't want to make it active. I would just like users to get the latest draft after I modify the latest one programmatically, as if I had done it manually.

A workaround would be to use a direct database query to change the settings (I am trying to change the type), but that sounds a bit risky...

**Comment by damien-git** [comment]
I made some experiments, and it turns out that Mura does not behave like I thought it did. It always asks for a draft version to use whenever there is more than one, and only suggests the latest one, with the message "This content has a draft newer than the current published version. Select the version to edit below." (which I don't find intuitive, and the message is misleading when there is no published version). So I guess .save() is behaving normally. Sorry about the confusion.
