### ISSUE TITLE
typo in apiApiUtility.cfc in Mura 7.1

### ISSUE THREAD

**Issue by IvanRotrekl** [blueriver/MuraCMS#2765]
Hi,

there is a small typo in the apiUtility.cfc on line 2244:

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/client/api/json/v1/apiUtility.cfc#L2244

_sProp=left(sProp,len(sProp)-1));_
shoud be
_sProp=left(sProp,len(sProp)-1);_

(there is an extra bracket on the right)

I got a syntax error while trying to deploy MuraBootstrap4 bundle on a fresh install of Mura 7.1, that's why I noticed...

Regards

Ivan

**Comment by stevewithington** [comment]
Fixed. Thanks!
