### ISSUE TITLE
Maximum upload size 

### ISSUE THREAD

**Issue by Gavinr98** [blueriver/MuraCMS#2766]
Does anyone know what the maximum size of a file that can be uploaded. We have a file that is 45MB and we get an error when trying to upload the file. We do not have an issues with files that are 6-10MB, just some larger ones.

We are running Mura CMS V7.0

Thanks,
Gavin

**Comment by stevewithington** [comment]
@Gavinr98 Mura does not restrict filesizes. Filesizes are restricted in two places, on the web server itself, and the ColdFusion Administrator. This is usually linked to a "form post" size restriction. For example, IIS6 default maximum file upload size is around 4MB, and IIS7 is around 28.6 MB. So, check both your web server settings (Apache, IIS, etc) and your CF Administrator.
