### ISSUE TITLE
Issue with long form field titles

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2768]
When a form field is created with a long title, Mura automatically creates a field name based on it. However, that field name sometimes has more than 50 characters, which is beyond the database limit. There is no warning when creating the form, and when a user submits a form, nothing is happening. The following error is visible in the console (which users do not normally look at):
```
Uncaught (in promise) TypeError: Cannot read property 'errors' of undefined
    at mura.min.js?v=7082:4
```
I think Mura should create unique field names shorter than the maximum limit, with numbers at the end if necessary. At the minimum, it should report an error when constructing the form and an error to the end user when a form is not successfully submitted. So this situation is a combination of several bugs.

Related bugs: #1545, #2061

**Comment by PeterBowater** [comment]
As you say, at least a warning is really needed, even if the field name length is not updated.

**Comment by cfmitrah** [comment]
@mattlevine, I have analyzed the issue and it occurs only when the label name Exceeds the length of 50. It occurs not only for text field but also for the hidden field, file upload and the checkbox as well.

The attribute maxLength has set as 250 for these fields. Changing that value to 50 prevents the error. Shall I create a PR for this fix? Or else you can update the length in the DB to 250 by yourself.

**Comment by mattlevine** [comment]
@cfmitrah Is there a stacktrace you can post?  What exactly do you mean by 'label'.  I was just able to successfully create a Mura form with a 267 character long name.  So I'm probably not understanding.

**Comment by cfmitrah** [comment]
@mattlevine we create the form with form fields and the form field's name will address as "Label" this is where we Enter the name for the fields, and the issue occurs while user submits the form[front_end] not while form creation[Form-builder] and you can see the error in Browser console. Due to this error form did not get submitted. 

> I was just able to successfully create a Mura form with a 267 character long name. 

Are you referring the form title or the field label name?

![2018-03-06](https://user-images.githubusercontent.com/532401/37028356-0dc9460a-215a-11e8-8115-4791f8f6b819.png)

**Comment by mattlevine** [comment]
I think if you update your core and apply db updates this issue will hopefully be fixed. 

You can either auto update in the admin or manually update.  Here are instructions fro 7.0

1. Back everything up, especially your config/settings.ini.cfm

2. Download the latest Mura standard and unzip it to your desktop

3. Copy everything but the "default" directory and paste it over your Mura root

4. If not on windows get your backed up config/settings.ini.cfm and restore it.

5. Make a request to your Mura root in the browser with your appreloadkey and applydbupdates in the url.  By default it would be http://domain.com/?appreload&applydbupdates

**Comment by mattlevine** [comment]
There shouldn't be an error. The field name field has been expanded so the long form fields should save without an error.

**Comment by mattlevine** [comment]
But I'
