### ISSUE TITLE
FEATURE REQUEST: Allow bulk delete of form data from admin UI

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#2779]
Hi chaps,

With GDPR on the horizon, it means we need to be more scrupulous about what data we keep hold of.

So... to delete form data in Mura at the moment, we appear to need to delete each entry alone, it would be great if we had a 'Nuke all' button which we could periodically push to clear all the form data out.

Alternatively, and certainly the gold-plated solution would be to be able to schedule a data delete for each form, say every XX days or similar, so that manual intervention is not required at all.

Any thoughts?

Aware we can do something with lucee scheduled tasks directly in the DB, but something configurable in the CMS seems a useful addition for many users.

Many thanks!

Peter.

**Comment by seanschroeder** [comment]
Peter, what’s the specific rule on data retention? Does an opt-in of any sort release you from the bounds of the retention policy?

**Comment by mattlevine** [comment]
@PeterBowater  Did you see Sean's question? 

Thanks!
-Matt

**Comment by PeterBowater** [comment]
@mattlevine , apologies , no, I hadn't.

@seanschroeder , there's no fixed timeframe, the onus is on the organisation to set what is deemed to be reasonable retention times for any data, this is not just related to the web, but any 'data controller'. 

For site forms we are now expected to give inline help for how long we will keep data, and what it will be used for, we can do this quite easily in Mura forms of course.

So, for a site feedback form, which is reviewed regularly, we think 30 days is probably a good time, but will vary wildly for each use case.

Does that help?

The principles of GDPR are laid out here: https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/principles/

You can read the whole thing if you have a couple of days to spare...

Thanks for coming back!


Peter.
