### ISSUE TITLE
Give option not to redirect after a successful login

### ISSUE THREAD

**Issue by tomysaman** [blueriver/MuraCMS#2789]
Give option not to redirect after a successful login

Scope: Feature request
Mura version: 7.0 & 7.1

Use case: 
- We have site domain for several countries like mysite.com, mysite.co.uk, and mysite.com.au
- We turn on extranet feature and created corresponding Mura user for each country domain, e.g. user-us, user-uk, and user-au
- We want to log user in automatically base on the domain user is visiting, e.g. log user in as "user-uk" when he is on mysite.co.uk
- We do this setup so that user will see different content (i.e. content permissions) and other custom logic, base on the country domain user is on (e.g. the Mura user he is logged in to be)
- So we want an option not to redirect user after we log user in. Otherwise a new user will get 302 redirect first before seeing the content (results in more server load and slow page load). Also it will be bad for search engine bots and social media preview as they will see 302 too.

Files: loginManager.cfc (same codes for 7.0 and 7.1)
- Mura 7.1: https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/login/loginManager.cfc#L79-L125
- Mura 7.0: https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/login/loginManager.cfc#L79-L125

Function: handleSuccess()
- Check arguments.redirect to determine if we want to redirect or not (default to true) at https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/login/loginManager.cfc#L123
- There is actually already an arguments.data.redirect in loginByUserID() function, guess someone already have this in mind but it is just never implemented https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/login/loginManager.cfc#L353
- Also apply this to login() function 

Pull request:
- I can submit a pull request, but think I should probably check with you guys first

**Comment by mattlevine** [comment]
Perhaps you could set your own redirect to the current url in an onAfterSiteLoginSuccess event

```
function(m){
    m.redirect('./');
}
```

Or event just set the returnURL:

```
m.event('returnURL','./');
```

**Comment by tomysaman** [comment]
Hi @mattlevine 

What I want is NOT to redirect

I perform the login action in onSiteRequestStart() using the loginManager.cfc and want an option not to redirect user after successful login. I've modified handleSuccess() in loginManager.cfc in my project and thought we can have this in Mura repo too

**Comment by mattlevine** [comment]
If you're doing it programmatically, you may be able to just reference the userUtility

```
m.getBean('userUtility').loginByUserId(siteid={yoursiteid},userid={youruserid);
```

**Comment by tomysaman** [comment]
Thanks @mattlevine 

I was on the wrong route looking at the loginByUserId in loginManager.cfc and didn't realise the one in userUtility bean can do what I want.

Closing this now
