### ISSUE TITLE
Including tag cloud throws file not found error

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#2802]
https://github.com/blueriver/MuraCMS/blob/ea6d2bc291212e3dab428a73bc16fdc4fbe50203/core/mura/content/contentRenderer.cfc#L1385-L1390

First IF condition is checking if **dsp_tag_cloud.cfm** exists in **/muraWRM/modules/nav/** and it's then loads it from **/muraWRM/display_objects/nav/**. Something similar is also happening on the 2nd IF.

Both of these throw an error, to recreate, include tag cloud to your content.

I think it should be this

	```<cfelseif fileExists(expandPath("/muraWRM/modules/nav/dsp_tag_cloud.cfm"))>
		<cfset tracePoint=initTracePoint("/modules/nav/dsp_tag_cloud.cfm")>
		<cfinclude template="/muraWRM/modules/nav/dsp_tag_cloud.cfm" />

	<cfelseif fileExists(expandPath("/muraWRM/display_objects/nav/dsp_tag_cloud.cfm"))>
		<cfset tracePoint=initTracePoint("/display_objects/nav/dsp_tag_cloud.cfm")>
		<cfinclude template="/muraWRM/display_objects/nav/dsp_tag_cloud.cfm" />```

**Comment by alladinUK** [comment]
When is this fix likely to be added?

**Comment by mattlevine** [comment]
Please update your core and retest.

**Comment by alladinUK** [comment]
The error still occurs, the issue is on line 1387 as its trying to load dsp_tag_cloud.cfm from display_objects when it should be modules

**Comment by mattlevine** [comment]
@alladinUK 

As a test can you manually update the contentRenderer.cfc more and confirm that's now fixed.

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/content/contentRenderer.cfc

Thanks for pointing out that it was still an issue.

-Matt

**Comment by alladinUK** [comment]
Hi Matt,

This is now fixed :+1: 

Thank you.
