### ISSUE TITLE
Typo in settings template for settings.ini file

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#2803]
https://github.com/blueriver/MuraCMS/blob/ea6d2bc291212e3dab428a73bc16fdc4fbe50203/core/templates/settings.template.cfm#L5

Typo in variable name, should be admindir. This is causing an issue when renaming the admin folder.

**Comment by mattlevine** [comment]
https://github.com/blueriver/MuraCMS/commit/e66d528cdfaf7ccca9911645f1500ce5cb3fb207

https://github.com/blueriver/MuraCMS/commit/2382528b4fbfd40413a5b8f2851d4221ccefb102
