### ISSUE TITLE
Possible bug: unscoped variables are not searched across all scopes

### ISSUE THREAD

**Issue by sowmyanayak** [blueriver/MuraCMS#2826]
Lucee version: 5.2.7
Mura version: 7.0

When including the following snippet in a plugin view or a display object, it returns false for the the first dump & true for the second. I have the defaults in the Lucee admin for scope cascading. And it returns true for both in a cfm page (without mura) on lucee 5.2.7.  

```
<cfscript>
url.foo = "foo!";
writedump("isDefined(foo) = " & isDefined("foo")); //true
writedump("isDefined(url.foo) = " & isDefined("url.foo")); //true\
</cfscript>
```

**Comment by jamiejackson** [comment]
FWIW, from #mura on Slack, from @jsieber-aca :

>jsieber [12:17 PM]
I ran into this with FW/1 based Mura plugins when converting to ACF2106 from ACF10. I did not dig into it deeper at the time either, in my case I scoped the variables in my plugins giving me the problem.

**Comment by mattlevine** [comment]
This is most likely caused by this setting in Mura's application.cfc settings:

https://github.com/blueriver/MuraCMS/blob/7.1/core/appcfc/applicationSettings.cfm#L99

If you want to change that you can add 

````
<cfscript>
this.searchImplicitScopes=true;
</cfscript>
```

In your config/cfapplication.cfm file.
