### ISSUE TITLE
Export content breaks on images with srcset attributes

### ISSUE THREAD

**Issue by DamianWilson** [blueriver/MuraCMS#2841]
Mura 7.0.6959 on Lucee 5.2.5.20

Exporting content from a page containing an image with a multi-resolution srcset tag e.g. 
````
<img alt="Apply Online"
     src="/default/assets/File/Apply-Online.png"
     srcset="/default/assets/File/Apply-Online-4x.png 4x,
             /default/assets/File/Apply-Online-2x.png 2x" />
````

is generating a 500 error that says
`
lucee.runtime.exp.NativeException: can't create directory D:\Tomcat\webapps_www\ROOT\admin\temp\proc\Bundle_8DC08BE7-28B4-4E76-A6EEEC4F9168B26A\assets\File\Apply-Online-4x.png 4x, \default\assets\
`

Not sure why it is trying to create a directory here, but it looks like it is misinterpreting the tag in some manner.

**Comment by mattlevine** [comment]
Do you have access to the full stacktrace?

**Comment by DamianWilson** [comment]
lucee.runtime.exp.NativeException: can't create directory D:\Tomcat\webapps_www\ROOT\admin\temp\proc\Bundle_8DC08BE7-28B4-4E76-A6EEEC4F9168B26A\assets\File\Apply-Online-4x.png 4x, \default\assets\File at lucee.commons.io.res.type.file.FileResource.createDirectory(FileResource.java:293) at lucee.runtime.tag.Directory.actionCreate(Directory.java:637) at lucee.runtime.functions.file.DirectoryCreate.call(DirectoryCreate.java:41) at lucee.runtime.functions.file.DirectoryCreate.call(DirectoryCreate.java:36) at lucee.runtime.functions.file.DirectoryCreate.call(DirectoryCreate.java:32) at settings.settingsbundle_cfc$cf.udfCall1(/mura/settings/settingsBundle.cfc:420) at settings.settingsbundle_cfc$cf.udfCall(/mura/settings/settingsBundle.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212) at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:780) at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833) at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1719) at settings.settingsbundle_cfc$cf.udfCall2(/mura/settings/settingsBundle.cfc:1763) at settings.settingsbundle_cfc$cf.udfCall(/mura/settings/settingsBundle.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:705) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:587) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1981) at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833) at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1719) at admin.core.controllers.carch_cfc$cf.udfCall1(/muraWRM/admin/core/controllers/carch.cfc:154) at admin.core.controllers.carch_cfc$cf.udfCall(/muraWRM/admin/core/controllers/carch.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:705) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:587) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1977) at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221) at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194) at admin.framework_cfc$cf.udfCall6(/Admin/framework.cfc:1308) at admin.framework_cfc$cf.udfCall(/Admin/framework.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226) at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:771) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1698) at admin.framework_cfc$cf.udfCall2(/Admin/framework.cfc:517) at admin.framework_cfc$cf.udfCall(/Admin/framework.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:704) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:587) at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1964) at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:419) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:221) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2405) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2395) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2363) at lucee.runtime.engine.Request.exe(Request.java:44) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1091) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1039) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1441) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) Caused by: java.io.IOException: can't create directory D:\Tomcat\webapps_www\ROOT\admin\temp\proc\Bundle_8DC08BE7-28B4-4E76-A6EEEC4F9168B26A\assets\File\Apply-Online-4x.png 4x, \default\assets\File ... 83 more

**Comment by mattlevine** [comment]
Would you mind manually updating this file and reload and retest?

7.0
https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/settings/settingsBundle.cfc

7.1
https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/settings/settingsBundle.cfc

**Comment by DamianWilson** [comment]
Thank you for working on this Matt, I did the update and it's closer to working. New stacktrace below.

lucee.runtime.exp.FunctionException: invalid call of the function FileCopy, first Argument (source) is invalid, source file [D:\Tomcat\webapps_www\ROOT\default\assets\File\Apply-Online-4x.png 4x] does not exist at lucee.runtime.functions.file.FileCopy.call(FileCopy.java:34) at settings.settingsbundle_cfc$cf.udfCall1(/mura/settings/settingsBundle.cfc:424) at settings.settingsbundle_cfc$cf.udfCall(/mura/settings/settingsBundle.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212) at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:780) at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833) at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1719) at settings.settingsbundle_cfc$cf.udfCall2(/mura/settings/settingsBundle.cfc:1767) at settings.settingsbundle_cfc$cf.udfCall(/mura/settings/settingsBundle.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:705) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:587) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1981) at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833) at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1719) at admin.core.controllers.carch_cfc$cf.udfCall1(/muraWRM/admin/core/controllers/carch.cfc:154) at admin.core.controllers.carch_cfc$cf.udfCall(/muraWRM/admin/core/controllers/carch.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:705) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:587) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1977) at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221) at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194) at admin.framework_cfc$cf.udfCall6(/Admin/framework.cfc:1308) at admin.framework_cfc$cf.udfCall(/Admin/framework.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226) at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:771) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1698) at admin.framework_cfc$cf.udfCall2(/Admin/framework.cfc:517) at admin.framework_cfc$cf.udfCall(/Admin/framework.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:704) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:587) at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1964) at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:419) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:221) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2405) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2395) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2363) at lucee.runtime.engine.Request.exe(Request.java:44) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1091) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1039) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1441) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748)

**Comment by mattlevine** [comment]
Please manually re-update the same file and retest once more.

**Comment by DamianWilson** [comment]
Thanks Matt. Further follow-up:

lucee.runtime.exp.ExpressionException: No matching property [path] found in [string] at lucee.runtime.reflection.Reflector.getGetter(Reflector.java:964) at lucee.runtime.reflection.Reflector.callGetter(Reflector.java:996) at lucee.runtime.reflection.Reflector.getProperty(Reflector.java:1195) at lucee.runtime.util.VariableUtilImpl.get(VariableUtilImpl.java:330) at lucee.runtime.PageContextImpl.get(PageContextImpl.java:1467) at settings.settingsbundle_cfc$cf.udfCall1(/mura/settings/settingsBundle.cfc:415) at settings.settingsbundle_cfc$cf.udfCall(/mura/settings/settingsBundle.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212) at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:780) at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833) at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1719) at settings.settingsbundle_cfc$cf.udfCall2(/mura/settings/settingsBundle.cfc:1773) at settings.settingsbundle_cfc$cf.udfCall(/mura/settings/settingsBundle.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:705) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:587) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1981) at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:833) at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1719) at admin.core.controllers.carch_cfc$cf.udfCall1(/muraWRM/admin/core/controllers/carch.cfc:154) at admin.core.controllers.carch_cfc$cf.udfCall(/muraWRM/admin/core/controllers/carch.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:705) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:587) at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1977) at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221) at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194) at admin.framework_cfc$cf.udfCall6(/Admin/framework.cfc:1308) at admin.framework_cfc$cf.udfCall(/Admin/framework.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226) at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:771) at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:756) at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1698) at admin.framework_cfc$cf.udfCall2(/Admin/framework.cfc:517) at admin.framework_cfc$cf.udfCall(/Admin/framework.cfc) at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:107) at lucee.runtime.type.UDFImpl._call(UDFImpl.java:366) at lucee.runtime.type.UDFImpl.call(UDFImpl.java:226) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:704) at lucee.runtime.ComponentImpl._call(ComponentImpl.java:587) at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1964) at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:419) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:221) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2405) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2395) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2363) at lucee.runtime.engine.Request.exe(Request.java:44) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1091) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1039) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1441) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748)

**Comment by mattlevine** [comment]
Please update once more.

**Comment by DamianWilson** [comment]
That did the trick, thank you!
