### ISSUE TITLE
Can't insert an embed DO with an iframe outside of the body display region

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2854]
When I try to insert an embed with a youtube video on a fresh Mura 7.1 site (or a Mura 7.0 site), it works inside the body display region, but the code is replaced by [INVALID] inside any other display region. I do not know if that behavior is intended, but it is a bit confusing for end users.

**Comment by damien-git** [comment]
We didn't change that setting, it is set at the value you give.

**Comment by mattlevine** [comment]
Try this

```scriptprotectexceptions=body,source,params,objectlist1,objectlist2,objectlist3,objectlist4```

**Comment by damien-git** [comment]
It works. Should we set that as the new default ?
