### ISSUE TITLE
Recaptcha no longer working as of 5/3

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2868]
The request `https://www.google.com/recaptcha/api.js?onload=Mura.checkForReCaptcha&render=explicit&hl=en` from mura.js no longer works: We are getting a 400 (Bad Request). It looks like removing the dot in "Mura.checkForReCaptcha" fixes it, so that might be a workaround...

**Comment by jsieber-aca** [comment]
We are seeing this as well on 7.0.xxx. Was this a change in the Google ReCaptcha API causing this issue?

**Comment by jsieber-aca** [comment]
We are on 7.0.6872 and we don't see the Mura. part in Mura.js. 

```
function(){
                    mura.reCAPTCHALanguage=mura.reCAPTCHALanguage || 'en';

    				if(find(".g-recaptcha" ).length){
    					var fileref=document.createElement('script')
    				        fileref.setAttribute("type","text/javascript")
    				        fileref.setAttribute("src", "https://www.google.com/recaptcha/api.js?onload=checkForReCaptcha&render=explicit&hl=" + mura.reCAPTCHALanguage)

    					document.getElementsByTagName("head")[0].appendChild(fileref)

    				}
```

**Comment by damien-git** [comment]
Right, I don't see it either and yet we had issues with 7.0 too. So maybe the dot was not the issue (it looked like that when I tried various requests in the browser, but maybe it was failing randomly and some cache made me think the results were consistent)...

**Comment by mattlevine** [comment]
I confirm that the dot did cause a 404 and have not been able to reproduce any errors with the "fix".  Just a guess, but perhaps there may be an issues cause by the roll out of the new version.

**Comment by wesme1337** [comment]
@mattlevine we are experiencing it on older mura 6 sites without the dot notation onload function.

Example: https://www.jasonsconnection.org/contact-us/

**Comment by mattlevine** [comment]
Please update and retest.

**Comment by damien-git** [comment]
It works in both Mura 7.0 and 7.1, thanks !
