### ISSUE TITLE
"The SiteID you entered is already being used." after a reload

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2879]
We have been getting this error in our logs since the update to Mura 7.1. `onApplicationStart_include.cfm` tries to create the default site if it does not exist, but the site existence check fails. I tried to debug that a little bit, and found that `structKeyList(application.settingsManager.getSites())` returns nothing just before `if(!application.settingsManager.siteExists(projectSiteID)){` in `onApplicationStart_include.cfm`. Later in `settingsManager.cfc`, Mura checks the database and realizes the site actually exists. The error does not happen on every reload, it seems random as far as I can tell.

`May 21, 2018 11:54:37 AM Error [ajp-bio-8014-exec-60] - coldfusion.runtime.EventHandlerException: Event handler exception. at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:287) at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:463) at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42) at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at coldfusion.filter.PathFilter.invoke(PathFilter.java:153) at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58) at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) at coldfusion.CfmServlet.service(CfmServlet.java:219) at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:466) at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) Caused by: coldfusion.runtime.CustomException: The SiteID you entered is already being used. at coldfusion.tagext.lang.ThrowTag.doStartTag(ThrowTag.java:142) at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000) at cfsettingsManager2ecfc919811170$funcCREATE.runFunction(E:\web-files\mura7\core\mura\settings\settingsManager.cfc:328) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483) at cfonApplicationStart_include2ecfm31812326._factor45(E:\web-files\mura7\core\appcfc\onApplicationStart_include.cfm:701) at cfonApplicationStart_include2ecfm31812326._factor49(E:\web-files\mura7\core\appcfc\onApplicationStart_include.cfm:95) at cfonApplicationStart_include2ecfm31812326.runPage(E:\web-files\mura7\core\appcfc\onApplicationStart_include.cfm:1) at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246) at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736) at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572) at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000) at cfonRequestStart_include2ecfm1202106998._factor0(E:\web-files\mura7\core\appcfc\onRequestStart_include.cfm:101) at cfonRequestStart_include2ecfm1202106998._factor2(E:\web-files\mura7\core\appcfc\onRequestStart_include.cfm:82) at cfonRequestStart_include2ecfm1202106998.runPage(E:\web-files\mura7\core\appcfc\onRequestStart_include.cfm:2) at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246) at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736) at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572) at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000) at cfApplication2ecfc191519290$funcONREQUESTSTART.runFunction(E:\web-files\mura7\admin\Application.cfc:177) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487) at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402) at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108) at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:279) ... 33 more `

**Comment by mattlevine** [comment]
Please let me know if you run into this again.

**Comment by damien-git** [comment]
We are not using the ProjectSiteID property, so this should fix it for us.

**Comment by damien-git** [comment]
If you try to fix this bug for ProjectSiteID: I noticed it is happening when settingsManager.setSites() starts before the settingsManager.siteExists() test in onApplicationStart_include (probably in another thread), and ends afterwards. It looks like some thread synchronization would be needed between the code in onApplicationStart_include and the one in settingsManager.setSites().
