### ISSUE TITLE
[Bug] Console errors 

### ISSUE THREAD

**Issue by davidpanzarella** [blueriver/MuraCMS#2880]
So I've been in the process of upgrading a site, and I noticed a few issues on the front end of Bootstrap 4 Theme. I've tried both themes (eg. default that ships with core & individual bootstrap4 theme). Both return the following in the console:

`(index):89 Uncaught ReferenceError: Mura is not defined
    at (index):89
(anonymous) @ (index):89
(index):473 Uncaught ReferenceError: Mura is not defined
    at (index):473
(anonymous) @ (index):473
mura.displayobject.cta.min.js:1 Uncaught TypeError: Cannot read property 'template' of undefined
    at mura.displayobject.cta.min.js:1
(anonymous) @ mura.displayobject.cta.min.js:1
VM63633:431 Uncaught TypeError: utility is not a function
    at checkToolbarDisplay (<anonymous>:431:3)
    at initToolbar (<anonymous>:517:3)
    at <anonymous>:543:2
    at <anonymous>:1592:3
    at m (jquery-3.3.1.min.js:2)
    at Function.globalEval (jquery-3.3.1.min.js:2)
    at text script (jquery-3.3.1.min.js:2)
    at Ut (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)`

Anyone else seeing this?

Core Version 7.1.218

**Comment by mattlevine** [comment]
Can you add `this.deferMuraJS=true;` to your theme's contentRenderer.cfc and reload and retest.

**Comment by mattlevine** [comment]
Also, do you have custom htmlhead/global.cfm?  It was updated in 7.1.  

https://github.com/blueriver/MuraCMS/blob/7.1/core/modules/v1/htmlhead/global.cfm

**Comment by davidpanzarella** [comment]
I'm using the default contentrenderer, so yes, that option is enabled:

`		// GENERAL
		this.deferMuraJS=true;
		this.layoutmanager=true;
		this.legacyobjects=false;
		this.validateCSRFTokens=true; //This will eventually default to true
		this.jsLib = "jquery";
		this.jsLibLoaded = true;
		this.suppressWhitespace = false;
		this.generalWrapperClass = "";
		this.generalWrapperBodyClass = "";

		this.bodymetaImageClass = "";
`

I'm not using anything outside what came with the default theme. I'm only adapting my changes as I go, but even when I pick a different theme (eg. the default bs4 one) there error remains.

**Comment by mattlevine** [comment]
Can you post the rendered output of the global.cfm and then <script> tag for the mura.displayobject.cta.min.js

They should both be deferred or not deferred.

**Comment by davidpanzarella** [comment]
So doesn't look like Global is deferred.
```
<script type="text/javascript" src="/sites/default/js/global.js"></script>
<script type="text/javascript">
var mura={
	loginURL:"?display=login",
	siteid:"default", 
	siteID:"default", 
	context:"", 
	jslib:"jquery",
	assetpath:"/sites/default",
	themepath:"/themes/eah",
	htmlEditorType:"",
	rb:"en",
	dtExample:"11/10/2018",
	dtCh:"/",
	dtFormat:[0,1,2],
	dtLocale:"en"
}
$.extend(window,mura);

</script>
```

And the `Mura` object can't be found here as a result:

```
<script>
Mura(function(){
	if(typeof Mura.deInitLayoutManager != 'undefined'
		&& typeof Mura.editing != 'undefined'
		&& Mura.editing){
			Mura.deInitLayoutManager();
	}
	Mura.loader().load('/admin/assets/js/layoutmanager.js',
		function(){
			
			Mura('body').addClass('mura-sidebar-state__hidden--right');
			Mura('body').removeClass('mura-sidebar-state__pushed--right');
			Mura('#mura-sidebar-container').show();
			Mura('#mura-objects-legacy-btn').click(function(e){
				e.preventDefault();
				MuraInlineEditor.sidebarAction('showlegacyobjects');
			});
			Mura('#mura-objects-openregions-btn').click(function(e){
				e.preventDefault();
				var el=Mura('body');
				if(el.hasClass('mura-regions-state__pushed--right')){
					el.removeClass('mura-regions-state__pushed--right');
				} else {
					el.addClass('mura-regions-state__pushed--right');
				}
			});
			Mura('#mura-objects-closeregions-btn').click(function(e){
				e.preventDefault();
				Mura('body').removeClass('mura-regions-state__pushed--right');
			});
			Mura('.mura-objects-back-btn').click(function(e){
				e.preventDefault();
				MuraInlineEditor.sidebarAction('showobjects');
			});
			//Mura('.mura-region.mura-editable').attr('style','clear:both;');
			Mura.rb.saveasdraft='Would\x20you\x20like\x20to\x20save\x20your\x20changes\x20as\x20a\x20draft\x3F';
			Mura.adminpath='/admin';
		}
	);
});
</script>
<div class="mura" id="frontEndToolsModalTarget"></div> 
<script src="//localhost:8080/core/modules/v1/cta/js/mura.displayobject.cta.min.js" defer="defer"></script>
```

**Comment by mattlevine** [comment]
Mura 7.0+ no longer use the global.js.  You must have a custom global.cfm.

**Comment by mattlevine** [comment]
OR you have not removed old legacy display objects in your siteid directory.  Those are no longer used and should only contain site level customizations.  As a rule when updating you should just rename that directory and then move any needed customization into a new empty directory or into the theme.

**Comment by davidpanzarella** [comment]
Oh! Ok, so that worked. Essentially the only thing that lives in sites anymore is `assets`, `cache`, `modules`, and `themes`? If you have event/content handlers, then do those get fired first?
