### ISSUE TITLE
non-super admin user seeing super admins

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#2890]
As non-super admin user, I am able to see super admin accounts and I'm able to change their details or even delete them. This shouldn't be the case.

I can see as an non-super admin I'm not able to set super admin status, however all a non-super admin needs to do is update a super admin account's password and login.

[https://groups.google.com/forum/#!topic/mura-cms-developers/tfdOZVQP7T4](url)

**Comment by mattlevine** [comment]
What core version are you on? And can you confirm that you aren't an super user yourself?   

There logic to not allow non super users to edit certain attributes of a super user (ie.  username, email, password)

https://github.com/blueriver/MuraCMS/blob/7.1/admin/core/views/cusers/edituser.cfm#L81

https://github.com/blueriver/MuraCMS/blob/7.1/admin/core/views/cusers/edituser.cfm#L173-L204

And then the controller also has logic to not allow those updates

https://github.com/blueriver/MuraCMS/blob/7.1/admin/core/controllers/cusers.cfc#L261-L280

But is does allow super users to edit other super's.

-Matt

**Comment by alladinUK** [comment]
Hi Matt,

I didn't realise the fix was already implemented.

I've tested this and it works perfectly.

thank you
