### ISSUE TITLE
Duplicate session cookies

### ISSUE THREAD

**Issue by ajays28** [blueriver/MuraCMS#2897]
Mura is creating duplicate JSESSIONID and CFID/CFTOKEN with an expiration date (persistent cookie) causing authentication issues in IE11 and Windows 7.
Initial secure cookie was created by Lucee/Tomcat without expiration date (session only cookie).

File: \requirements\mura\utility.cfc
Function: setSessionCookies()
Function: setCookie()
<hr/>

<code>
<cfif isDefined('sessionTokens.jsessionid') and (arguments.reset or not isDefined('cookie.jsessionid'))>
	<cfif application.configBean.getSessionCookiesExpires() EQ "" OR application.configBean.getSessionCookiesExpires() EQ "session">
		<cfset setCookie(name="JSESSIONID", value=sessionTokens.jsessionid, encodevalue=false) />
	<cfelse>
		<cfset setCookie(name="JSESSIONID", value=sessionTokens.jsessionid, expires=application.configBean.getSessionCookiesExpires(), encodevalue=false) />
	</cfif>
</cfif>
</code>

In the settings.ini.cfm file, 
	if the value of the 'sessioncookiesexpires' is blank or session, Mura is creating JSESSIONID with an expiration date.
	Reason: Not passing 'expires' argument to 'setCookie()' function and default value for 'expires' is 'never'
	setSessionCookies()
	<code>
	<cfset setCookie(name="JSESSIONID", value=sessionTokens.jsessionid, encodevalue=false) />
	</code>
	
	setCookie()
	<code>
	<cfargument name="expires" type="string" default="never">
	</code>
	
	Valid values for 'expires' are [session only,now,never]. Default is 'never'. 
	<cfif not (
			isDate(arguments.expires)
			or isNumeric(arguments.expires)
			or listFindNoCase('session only,now,never',arguments.expires)
		)>
		<cfset structDelete(arguments,'expires')>
	</cfif>	
	
	If the value of 'sessioncookiesexpires' is 'session only', Lucee is generating an error.
	cannot cast [session only] string to a number value.
	
Temporarily we are commenting out application.utility.setSessionCookies(); in onRequestStart_include.cfm
\config\appcfc\onRequestStart_include.cfm

Eg:
JSESSIONID=FA844EE1CD2154B90739A3C23889D511; Path=/; Secure; HttpOnly
(Mura)
JSESSIONID=FA844EE1CD2154B90739A3C23889D511;Path=/;Expires=Sat, 06-Jun-2048 04:35:30 UTC;HTTPOnly

Is here any setting to not to call setSessionCookies() function if the session cookies already exists?

**Comment by mattlevine** [comment]
The setSessionCookies() allows sessions to configurable with Mura environment / settings.ini.cfm variables.  

Looking into this it appears that Lucee doesn't support "session only" cookies.

While we look into this commenting that line out in the meantime shouldn't cause any issues.

**Comment by mattlevine** [comment]
As a test can you try setting your sessioncookiesexpires attribute to just 'session' instead of 'session only'

**Comment by mattlevine** [comment]
Ok, if you update you can now set manageSessionCookies=false in your /config/settings.ini.cfm and Mura will not reset the cookies.

I did however, add some logic to hopefully prevent the issue from happening in the the first place.

**Comment by sowmyanayak** [comment]
I don't think this issue is resolved or maybe I misunderstood. Without the manageSessionCookies=false, I still see duplicate cookies for cfid & cftoken. From your earlier comment 
> I did however, add some logic to hopefully prevent the issue from happening in the the first place.

I thought this shouldn't be happening. Or do we need to explicitly set manageSessionCookies=false?

**Comment by mattlevine** [comment]
You need to set  manageSessionCookies=false in you /config/settings.ini.cfm .  You'll also have to clear the cookies to test.

**Comment by sowmyanayak** [comment]
Thanks Matt. But when manageSessionCookies is not set (which is the default), shouldn't we still see only 1 set of cookies for cfid & cftoken? I am seeing duplicates.

**Comment by mattlevine** [comment]
@sowmyanayak   Unfortunately, we can reproduce and we don't know why you are getting the duplicate cookies.  By default manages sessions cookies, so for you the solution is to turn that functionality off.

**Comment by sowmyanayak** [comment]
Thanks @mattlevine. I'll keep digging.

**Comment by sowmyanayak** [comment]
The issue occurs in 7.0 and not 7.1. In /mura/utility.cfc, maintaincase=true is not passed in to setCookieLegacy(). 

```
<cfset setCookieLegacy(name='cfid', value=sessionTokens.CFID, encodevalue=false )>

<cfset setCookieLegacy(name='cftoken', value=sessionTokens.CFTOKEN, encodevalue=false )>
```

**Comment by mattlevine** [comment]
If you add maintaincase to the method call, does the issue go away?

**Comment by sowmyanayak** [comment]
Yes, that fixes it.
