### ISSUE TITLE
Error after upgrade to Mura 7.1.235

### ISSUE THREAD

**Issue by IvanRotrekl** [blueriver/MuraCMS#2901]
Hi, 

I've got an error after upgrading to Mura 7.1.235 via the autoupdater:

key [PACKAGE] doesn't exist in argument scope. existing keys are [dir]

This error points to  /core/mura/settings/settingsBean.cfc, function registerContentTypeDir, line 1674 a1676 where arguments.package is used, but not passed in as an argument from the calling function ( discoverGlobalContentTypes, line 1611). 

This happens only on reload and might be a bug. 

(I could quick fix it locally by adding a default package argument (empty string)  to registerContentTypeDir, just to keep going)

Regards

Ivan

**Comment by mattlevine** [comment]
Thanks for the debugging.  It should be fixed now.
