### ISSUE TITLE
Key 'Columns' not defined

### ISSUE THREAD

**Issue by David-Polehonski** [blueriver/MuraCMS#2904]
This commit https://github.com/blueriver/MuraCMS/commit/f59ea6f555a36a0b9c57b52334dedb5d9465d8dc
is causing an issue when attempting to load a feed of content beans:

m.getBean('Feed').where().prop('type').isEq('File').getIterator();
![issue](https://user-images.githubusercontent.com/2487640/41858890-d5c26ab2-7892-11e8-973c-3cf547710852.JPG)

**Comment by David-Polehonski** [comment]
Either; this feed/query syntax was never meant to be used to retrieve content beans, and I've been using it as an undocumented feature; or it's broken.

**Comment by mattlevine** [comment]
It is supposed to be used with content beans. I believe I found the issue. Please update and retest.  I also added a unit test for this specific issue to make sure it doesn't pop up again.
