### ISSUE TITLE
Make HSTS Header optional

### ISSUE THREAD

**Issue by MordantWastrel** [blueriver/MuraCMS#2906]
We had to track down the source of a duplicate HSTS header this morning when testing a new server with Mura 7.1 in Docker (which was super easy to work with, by the way). It looks like the `onRequestStart` code always adds it, and while the number of days is in the config bean, whether or not to add it at all is not.

We handle this through nginx on the front end so disabled it in the code, but in our new containerized deployment we don't even have our own fork of Mura -- and we'd just as soon not make one. Could this be made into settings.ini (and therefor env variable) option?

**Comment by mattlevine** [comment]
I made an update that if you set HSTSMaxAge=0 in you /config/settings.ini.cfm or set MURA_HSTSMAXAGE: 0 as an environment variable Mura will not add it.

It will be in next build.
