### ISSUE TITLE
Adding a page under a folder in Mura 7.1.259 throws error on public site

### ISSUE THREAD

**Issue by JonasEriksson** [blueriver/MuraCMS#2920]
Lucee 5.2.8.50
Ubuntu 16.04 LTS Apache2/Tomcat8
DB MySQL 5.7.23

Component [muraWRM.sites.mySiteName.contentRenderer] has no accessible Member with name [ITERATOR]

lucee.runtime.exp.ExpressionException: Component [muraWRM.sites.mySiteName.contentRenderer] has no accessible Member with name [ITERATOR]
	at lucee.runtime.ComponentScopeShadow.get(ComponentScopeShadow.java:124)
	at core.modules.v1.collection.layouts.list.index_cfm$cf.call(/muraWRM/core/modules/v1/collection/layouts/list/index.cfm:53)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:899)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:821)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:803)
...

Column: 0
ID: ??
Line: 53
Raw Trace: core.modules.v1.collection.layouts.list.index_cfm$cf.call(/muraWRM/core/modules/v1/collection/layouts/list/index.cfm:53)
Template: /var/www/mysitedir/core/modules/v1/collection/layouts/list/index.cfm
Type: cfml

**Comment by mattlevine** [comment]
As a test can you add 

```
<cfset variables.iterator=iterator>
```

before this line:

https://github.com/blueriver/MuraCMS/blob/7.1/core/modules/v1/collection/index.cfm#L218

I wonder if Lucee 5.2 has change the default scope in a component from variables?

**Comment by mattlevine** [comment]
Or better yet, just take the variables scope off of this line

https://github.com/blueriver/MuraCMS/blob/7.1/core/modules/v1/collection/layouts/list/index.cfm#L53

so it's just `iterator` instead of `variables.iterator`

**Comment by JonasEriksson** [comment]
Hi Matt, thanks for your super-fast reply even on a weekend! I first tried your first suggestion, which worked fine. I then commented out that fix, and tried your "or better yet" suggestion - I can confirm this error is now gone using that version as well.

Again, thanks a lot for a quick solution!
