### ISSUE TITLE
settings.ini.cfm assetpath points to wrong path

### ISSUE THREAD

**Issue by naziz0822** [blueriver/MuraCMS#2923]
Version: Mura 7.1
Backend: ColdFusion 2018
Database: MSSQL 17
Theme: MuraBootstrap4

Building Mura 7.1 from scratch, images fail to load. Tried both version from website and repo
http://www.getmura.com/downloads/download-mura-cms/
https://github.com/blueriver/MuraCMS

Images points to 
```
localhost:8500/MuraCMS-master/default/cache/file/83B34C35-A73F-6FD3-D752FA8C34D8B217.jpg
```

And should really be pointed to
```
localhost:8500/MuraCMS-master/sites/default/cache/file/83B34C35-A73F-6FD3-D752FA8C34D8B217.jpg
```

Modifying settings.ini.cfm to the following fixes it for me:
```ColdFusion
<cfabort/>
...
assetpath=/MuraCMS-master/sites
...
```

**Comment by mattlevine** [comment]
do you have a directory named 'default' in your Mura root directory?  If so Mura will think that the siteid directories are in the Mura root.

**Comment by naziz0822** [comment]
Nope, the site was built off of the latest bundle. So it has the same directory structure at 7.1.

**Comment by naziz0822** [comment]
The test.cfm file outputs the following paths for me:

```
MuraWRM: C:\ColdFusion\cfusion\wwwroot\MuraCMS-master
SitesDir: C:\ColdFusion\cfusion\wwwroot\MuraCMS-master\sites
DefaultDir: C:\ColdFusion\cfusion\wwwroot\MuraCMS-master\default
```

**Comment by naziz0822** [comment]
That DefaultDir seems like it's still based off of the previous directory structure from v6 and v7.

**Comment by mattlevine** [comment]
How about outputting

<cfoutput>
MuraWRM: #expandPath('/muraWRM')#<br/> 
SitesDir: #directoryExists(expandPath('/muraWRM/sites'))#<br/> 
DefaultDir: #directoryExists(expandPath('/muraWRM/default'))#<br/>
SetValue:#application.Mura.globalConfig('siteDir')# 
</cfoutput>

**Comment by naziz0822** [comment]
I get the following output:

```
MuraWRM: C:\ColdFusion\cfusion\wwwroot\MuraCMS-master SitesDir: YES DefaultDir: NO SetValue:C:\ColdFusion\cfusion\wwwroot\MuraCMS-master\sites
```

**Comment by mattlevine** [comment]
Yes, that's the point. It follows where the default site is.  So you can have a pre Mura 7.1 site directory structure with 7.1.

**Comment by mattlevine** [comment]
Can you point me at the code in the theme that is rendering incorrectly?  That all seems correct.

**Comment by mattlevine** [comment]
How about this:

```<cfoutput>
#application.mura.getBean('settingsManager').getSite('default').getFileAssetPath()#
</cfoutput>
```

**Comment by naziz0822** [comment]
Sure, with the original assetpath back in.. anywhere an image should be rendered mura has a problem locating the it (404)

Example, the home.cfm from MuraBootstrap4 contains the dspCaraouselByFeedname object. Going to the home page of the site nothing shows up in the slideshow.

** Id point you to code in github, but github repo has a .zip file of the Bundle.
https://github.com/blueriver/MuraBootstrap4Bundle/

**Comment by naziz0822** [comment]
Calling getFileAssetPath() I get this for the output

```
/MuraCMS-master/sites/default
```

**Comment by mattlevine** [comment]
You can find it here
https://github.com/blueriver/MuraBootstrap4/

And can you set 

assetpath=/MuraCMS-master

in you settings.ini.cfm and do that last request.

**Comment by naziz0822** [comment]
Same output with the assetpath set to _/MuraCMS-master_ and _/MuraCMS-master/sites_

**Comment by mattlevine** [comment]
You need to reload after each change.

**Comment by mattlevine** [comment]
And the value you received  (/MuraCMS-master/sites/default) is correct.

**Comment by naziz0822** [comment]
Did just that...

had to make sure so I did it by appending _?appreload_ to the url and pushing the reload app buton in the admin UI screen.

**Comment by naziz0822** [comment]
And for the home.cfm file from the MuraBoostrap4 theme:

https://github.com/blueriver/MuraBootstrap4/blob/master/templates/home.cfm#L17-L24

**Comment by mattlevine** [comment]
Can you manually update this file and reload and retest.

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/content/file/fileManager.cfc

**Comment by naziz0822** [comment]
Seems to be working now.

* Manually updated fileManager.cfc file
* set context=/MuraCMS-master
* set assetpath=/MuraCMS-master
* Running test outputs:
```
/MuraCMS-master/sites/default
```

**Comment by naziz0822** [comment]
Tested the latest commit and its working fine. Thanks @mattlevine
