### ISSUE TITLE
The word 'Notes:' get appended every time the page is updated

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#2925]
https://github.com/blueriver/MuraCMS/blob/633a2ec8523323368f8d83fc22ecb0f0957fea44/admin/core/views/carch/form/dsp_tab_publishing.cfm#L237

Having the following in the textarea as a 'Label' get appended every time one updates a page.
#application.rbFactory.getKeyValue(session.rb,"sitemanager.content.notes")#:

**Comment by mattlevine** [comment]
https://github.com/blueriver/MuraCMS/commit/c2277e94049db434da30bd4bf54c6b6638cee669
