### ISSUE TITLE
Front End editing of Local Collection Selected Fields not posibble with many Extended Attributes

### ISSUE THREAD

**Issue by JonasEriksson** [blueriver/MuraCMS#2928]
I think there is a bug when one has many extended attributes which may show in the list of Fields for a Local Index/Collection. See attached Screenshot - even on a 32" monitor or 5K iMac, I can not get to the "Publish" button at the end. 
![screenshot 2018-09-16 14 26 52](https://user-images.githubusercontent.com/701938/45596477-9172a500-b9bc-11e8-9da5-0b7b45bcce8e.png)

**Comment by gowestweb** [comment]
Noted. And agreed, that's a lot of extended attributes, but the basic functionality should still be reachable. We're looking at a few ways to deal with long lists in the UI in general, and this use case brings up a good point, thanks.

**Comment by gowestweb** [comment]
Will be resolved in Mura 7.2
