### ISSUE TITLE
Locale file name

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#2952]
https://github.com/blueriver/MuraCMS/blob/9a6894156aab3d98377789ce269086fe7497bfdc/core/mura/resourceBundle/resourceBundle.cfc#L113

This line seems to generate an incorrect file name. Changing the local setting in Site setting to English (Ireland) seems to generate a value of en_IE_en_IE

See generated output in attached files for locale English (Ireland) 

![sourcecode](https://user-images.githubusercontent.com/7131420/49234328-bf7a5980-f3ef-11e8-81a3-f796eac2cd13.png)
![output](https://user-images.githubusercontent.com/7131420/49234348-cb661b80-f3ef-11e8-81a0-00fdeec4f569.png)

**Comment by mattlevine** [comment]
Please manually update to the latest version and retest

https://github.com/blueriver/MuraCMS/blob/9a6894156aab3d98377789ce269086fe7497bfdc/core/mura/resourceBundle/resourceBundle.cfc

**Comment by alladinUK** [comment]
This is now working, thank you
