### ISSUE TITLE
Site copy functionality not working

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#2959]
Hi,

I've tried using the Site copy functionality in Mura (7.1.320) and it doesn't seem to work.

Having created a new site (siteid=TestSite"), using the Site Copy I selected Default as my "Source" site and TestSite as my "Destination" site. 

The DB content was copied successfully but all the images and PDF's in my source site's /cache/file directory have been corrupted and I'm unable to open any of them. Plus nothing was copied to the destination site's /cache/file directory.

**Comment by mattlevine** [comment]
Would you happen to be using a shared file pool between already between those sites?

**Comment by alladinUK** [comment]
Hi,
No, I'm not sharing anything between these site

**Comment by mattlevine** [comment]
Unfortunately, then I'm a bit stump because it works for me in my local testing.  I did however recently add exclusive locks in Mura's fileWriter.  Can you manually update and retest?

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/fileWriter.cfc

What OS and CFML compiler are you using?

**Comment by alladinUK** [comment]
Hi again!
Just tested this and it NO longer corrupts the source site's files. However, it does NOT copy the files to the destination site.

**Comment by alladinUK** [comment]
I found the issue was down to [publisher.cfc#L4038](https://github.com/blueriver/MuraCMS/blob/7f99839727c893a9082a1b5dcb928a9251660cd2/core/mura/publisher.cfc#L4038). This line does a replace but the values it's trying to replace are not in the same case.

For example
This value is obtained from the database, note the drive letter is stored as a capital in the database but the arguments are using lower case.
_#rs.directory##fileDelim#_ = **D**:\webapps\MuraFiles\muraI1\mySourceSite\cache\file\ 

_#arguments.baseDir#_ = **d**:\webapps\MuraFiles\muraI1\mySourceSite\cache\file\ 
_#arguments.destDir#_ = **d**:\webapps\MuraFiles\muraI1\myDestinationSite\cache\file\ 

The same issue would apply to these lines too
[publisher.cfc#L4019](https://github.com/blueriver/MuraCMS/blob/7f99839727c893a9082a1b5dcb928a9251660cd2/core/mura/publisher.cfc#L4019)

[publisher.cfc#L4028](https://github.com/blueriver/MuraCMS/blob/7f99839727c893a9082a1b5dcb928a9251660cd2/core/mura/publisher.cfc#L4028)

[publisher.cfc#L4038](https://github.com/blueriver/MuraCMS/blob/7f99839727c893a9082a1b5dcb928a9251660cd2/core/mura/publisher.cfc#L4038)

**Comment by mattlevine** [comment]
Thanks for the debugging, I truly appreciate it!  It in the latest build.

**Comment by alladinUK** [comment]
It my pleasure Matt. Thank you guys for everything and putting the fix in so quickly.
