### ISSUE TITLE
The form data scrollbar is barely visible

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2973]
In form data, View Data, the results can have a horizontal scrollbar at the bottom if there are enough rows and columns.
This scrollbar is currently half or 90% hidden (depending on the system & browser), which can prevent users from seeing the columns beyond the visible part of the table.
A CSS workaround would be to add a `margin-bottom` to `.mura #manage-data .mura-grid-container`, to plan for extra space for that scrollbar.

**Comment by gowestweb** [comment]
This will be fixed in Mura 7.2
