### ISSUE TITLE
Inline publish error with some characters and ACF 11 u 16

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2978]
We are seeing errors when inserting curly double quotes in a page, publishing, doing an inline edit and publishing again. It started after we updated to CF11 update 16 but I am not sure if it is related (although we did notice another issue related to URL encoding and special characters with this update).
I am not sure why Mura is URL-encoding page content anyway...

**Comment by mattlevine** [comment]
Can you post the error?

**Comment by damien-git** [comment]
This message shows up in an alert on frontend:
`{"apiversion":"v1","method":"validate","error":{"message":"Invalid parameters","code":"invalid_request"}}`
I have not seen any error in CF logs.

I don't think an HTML entity is used in the source, it is just the UTF-8 character. The first one gets URL-encoded as `%E2%80%9C`.
We haven't changed our database or CF data source (which still has unicode enabled), so I don't think this is related.

**Comment by mattlevine** [comment]
When specifically does that error show up?  When clicking to save the content or perhaps when working with the layout manager in someway?  Can you look in the browser network debugger can and post a sample url?

**Comment by damien-git** [comment]
When clicking on Publish. The request is:
`/index.cfm/_api/json/v1/[siteid]//validate/`
and it returns a 400 code with the message I mentioned earlier.

**Comment by mattlevine** [comment]
I'm pretty sure that it's coming from this right here:

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/client/api/json/v1/apiUtility.cfc#L3317-L3321

Which basically means that the data string can't be deserialized from JSON?  I think it may be that since it's not a norm quote it's not getting escaped with a / in the stringified JSON.  But when it's deserialized it's considering it as proper string quote and since it's not escaped, it breaks the JSON.

What browser are you on?  I don't the problem locally.

-Matt

**Comment by mattlevine** [comment]
Also, is this content that's going into the main body or a configurator?

**Comment by damien-git** [comment]
I guess that update breaks deserializeJSON then. Adobe probably fixed a vulnerability in it without checking backward compatibility. I will do some tests to get more information from the lines of code you mentioned.
We've noticed the same issue with Firefox and Chrome, although sometimes we've had to try to edit and publish another time to make it break.
The content is in the main body.

**Comment by damien-git** [comment]
OK, I guess it's not deserializeJSON after all. But it throws the exception where you thought.
Here is a dump of `arguments` (I copied your text with the curly quotes in the body):
```
struct

DATA: {"muraaction":"carch.update","action":"add","ajaxrequest":true,"siteid":"[siteid]","contenthistid":"7F9B8E49-AD82-92CD-976872485A7C3046","contentid":"3F7C5C05-155D-E644-113883EA414B0672","parentid":"00000000000000000000000000000000001","moduleid":"00000000000000000000000000000000000","approved":"1","changesetid":"","bean":"content","loadby":"contenthistid","approvalstatus":"","csrf_token":"CF4706BB894DD6D165D2DB9CEF259702","csrf_token_expires":"190222125456310","body":"<p>for " and " in you text instead of the " and "</p>\n\n<p>&nbsp;</p>\n"}
FIELDNAMES: DATA,VALIDATIONS
METHOD: validate
VALIDATIONS: {"properties":{}}
siteid: [siteid]

```
It looks like the curly quotes were turned into straight quotes !

**Comment by damien-git** [comment]
I'm seeing the same thing when doing a dump of `form` in `processRequest`.

**Comment by damien-git** [comment]
Adobe just released CF11 update 17 to fix some of the many issues with update 16 (such as the removal of all tasks (yes, we enjoyed that too)).
It did not fix this bug.

**Comment by mattlevine** [comment]
I'm going to see if I can do a replace() for “ and \” to “ and \”  right before the deserialization.  But I have reproduced it yet locally.  I update my commandbox image and now things are a bit out of wack.  Once I figure that part out, I'll see if I can reproduce the issue and then add the din replace() method.

**Comment by damien-git** [comment]
The issue happens with Windows Server 1012 and 2016. I don't know if it could make a difference...

**Comment by damien-git** [comment]
Interestingly, this only affects validation, because when the client sends the content after validation it does not url-encode it.
So for instance, I am not getting an error for
`“,“test“:“bad“,“rest“:“`
and it gets stored normally (because this looks like a real JSON structure for validation, even though I modified it a bit, and the error only happens when the content is url-encoded).

**Comment by damien-git** [comment]
I tried to reproduce that behavior outside of Mura. A form parameter gets URL-decoded automatically by CF, but I get a curly quote when I input `%E2%80%9C`...

**Comment by damien-git** [comment]
I found that the bug does not happen when I disable scriptProtectionFilter (Portcullis) in Mura.

**Comment by mattlevine** [comment]
hmm, that's interesting?

**Comment by damien-git** [comment]
...which contains the following code:
```
		<!---trim white space and deal with "smart quotes" from MS Word, etc. This code came from Shawn Gorrell's popular cf_xssblock tag - http://www.illumineti.com/documents/xssblock.txt --->
		<cfset result.originalText = trim(replaceList(arguments.text,chr(8216) & "," & chr(8217) & "," & chr(8220) & "," & chr(8221) & "," & chr(8212) & "," & chr(8213) & "," & chr(8230),"',',"","",--,--,..."))/>

```

**Comment by mattlevine** [comment]
I wonder if they have force CF script protection all the time or broke the Application.cfc setting.

Mura is supposed to turn it off:
https://github.com/blueriver/MuraCMS/blob/7.1/core/appcfc/applicationSettings.cfm#L136

Can you test turning it off at the CF admin level?

**Comment by damien-git** [comment]
The first thing I tried was to disable "Enable Global Script Protection" in cfadmin, but that didn't change anything...

**Comment by damien-git** [comment]
Ah, I found that we have a `scriptprotect=true` in our settings.ini...

**Comment by damien-git** [comment]
Maybe you were missing that in your tests ? If I set it to false, the issues does not happen.

**Comment by mattlevine** [comment]
That setting deal withs turning off the portcullis script protection and does not change the CF app.cfc setting.  I sure seems like they removed the ability to disable the CF script protection?

**Comment by damien-git** [comment]
Maybe they did without updating the user interface ?
Either way, if I replace
`<cfset result.originalText = trim(replaceList(arguments.text,chr(8216) & "," & chr(8217) & "," & chr(8220) & "," & chr(8221) & "," & chr(8212) & "," & chr(8213) & "," & chr(8230),"',',"","",--,--,..."))/>`
by
`<cfset result.originalText = arguments.text>`
it solves the problem.
With UTF-8 being used everywhere, I'm not sure these replacements are relevant (or even safe) anymore...

**Comment by damien-git** [comment]
I have been trying to figure out where the form parameters where decoded in Mura.
I found that `setEncoding("form", "utf-8");` in Mura's `onRequestStart_include` prevents the automatic url-decode.
However, `removeNullChars` in `Portcullis.cfc` does this:
`urldecode(replace(urlEncodedFormat(arguments.theString),"%00","","all"))`
which has the effect of url-decoding everything (urlEncodedFormat is deprecated, encodeForURL should be used instead if the goal is simply to remove null chars).
I feel like there are several issues usually cancelling each other, with possible side effects.

I still have not figured how exactly this is connected to CF11 update 16 (I suspect the behavior for urldecode or urlEncodedFormat has changed).

**Comment by mattlevine** [comment]
There are definitely server issue cancelling each other out.  The App.cfc this.scriptprotect should be set to false.  

https://github.com/blueriver/MuraCMS/blob/7.1/core/appcfc/applicationSettings.cfm#L136

Which should turn of CF's script protection to just user Mura's. However, after the update it look as though you can't turn of the CF based script protection which is leading to double script protect.

In regard to removing null chars are you saying it should that method look like this>
```
   <cffunction name="removeNullChars" access="private" output="false">
		<cfargument name="theString" type="string" required="true" />
		<cfreturn urldecode(encodeForURL(arguments.theString)>
	</cffunction>
```

**Comment by mattlevine** [comment]
Also, where did you set setEncoding("form", "utf-8"); ?  It's already there:  

https://github.com/blueriver/MuraCMS/blob/7.1/core/appcfc/onRequestStart_include.cfm#L50-L51

So perhaps something is happening between there where you set it.

**Comment by damien-git** [comment]
I was thinking of
`<cfreturn urldecode(replace(encodeForURL(arguments.theString),"%00","","all"))>`
(without the replace it would be useless)
But I did not test it.

As for `setEncoding("form", "utf-8");`, I saw it in Mura's code where you indicate. I was comparing that with my test outside Mura, where I did not do that initially. This is how I realized that using `setEncoding` prevents the automatic url-decoding.

**Comment by mattlevine** [comment]
Please update and retest.

**Comment by damien-git** [comment]
Your update fixes it. Closing.

**Comment by damien-git** [comment]
This CF issue is probably related: https://tracker.adobe.com/#/view/CF-4204045
