### ISSUE TITLE
Improper usage of <dl> elements for indexes/folders

### ISSUE THREAD

**Issue by JesseEarley** [blueriver/MuraCMS#3025]
Mura folders/indexes use the `<dl> `element to display their content. However, a `<dl>` element needs to always have a `<dt>` element inside of it, and precede a `<dd>` element, in order for it to be both valid in HTML 5 and pass WCAG 2.0.

The current implementation is not valid in HTML 5 nor does it pass WCAG 2.0.

Example of invalid markup from Mura 7.1:
![image](https://user-images.githubusercontent.com/43992633/58725718-d9e8bc00-83ad-11e9-9388-c0a10df4abee.png)

It would make more sense to use a `<div>` as the parent container, and then either a `<div>` or a `<span>` element for each piece of content to be output in the feed.

**Comment by mattlevine** [comment]
Thanks for pointing that out.  We're probably not going to change that midstream on 7.1, but we're currently working on 7.2 and will review this.

**Comment by mattlevine** [comment]
Actually, looking at where that code is output

https://github.com/blueriver/MuraCMS/blob/7.1/core/modules/v1/collection/includes/dsp_content_list.cfm

It runs on contentRenderer variables.  This is the default

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/content/contentRenderer.cfc#L374-L384

I would try overriding it in your theme's contentRenderer.cfc and the reload and test.

**Comment by JesseEarley** [comment]
Hi Matt,

Thanks for the reply. This did the trick, and I was able to output both valid and accessible markup, thanks for pointing that out.

For future reference, if Mura keeps with outputting the `<dl>` as default, the output is actually not valid markup.

**Comment by mattlevine** [comment]
We're going to update the default theme in the next release and make that change at the theme level.  Thanks for pointing it out.
