### ISSUE TITLE
Custom UI container/tab does not work for Site/Default

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#3085]
I've followed the instruction as shown here on how to add customised named tabs for content editing and works a treat! thank you.

I've done something similar for Site / Default class extension, when creating attributes set for Site / Default I selected 'Custom UI' as an option to set the container tab but it doesn't seem to work. 

Should it work?

	<cffunction name="onSiteDefaultEdit" access="public" output="false" returntype="any">
		<cfset $.event('tabLabel', 'Google settings')>
                .....
	</cffunction>

**Comment by mattlevine** [comment]
Unfortunately, custom tabs in the site settings ui is not supported.

**Comment by alladinUK** [comment]
thank you for getting back to me.
