### ISSUE TITLE
Copying a site causes a 500 Error

### ISSUE THREAD

**Issue by aaltenbu** [blueriver/MuraCMS#3150]
Hi,
I am trying to copy a site from "de" to "en".
The Database is copied but the files not. In the htdocs-root folder is a empty folder "en"

Environment:
Core Version 7.1.460
App Server ColdFusion (2016,0,11,314546)
DB Server MySQL (5.7.12)
OS Version UNIX (4.4.0-159-generic)

The Error on Screen:
Attribute validation error for tag CFFILE.
Type:Application
The value of the attribute source, which is currently /srv/websites/site/htdocs/sites/en/cache/file/74F695DF-A0C7-1E47-2D0ADACEF84AA305_small.jpg, is invalid.

	at cffileWriter2ecfc614258970$funcRENAMEFILE.runFunction(/srv/websites/site/htdocs/core/mura/fileWriter.cfc:141)

Then i've logged the arguments in the fileWriter.cfc functions:
copyDir tries to copy files from htdocs/de whereas the files are located in htdocs/sites/de:

"Information","ajp-nio-8016-exec-108","10/28/19","16:08:18","MURA8DF8053F1DF5D07CA1B9BA5AD1209DA4","copyDir, {""BASEDIR"":""/srv/websites/site/htdocs/de/"",""DESTDIR"":""/srv/websites/site/htdocs/en/"",""EXCLUDELIST"":""cache/file"",""SINCEDATE"":"""",""EXCLUDEHIDDENFILES"":true}"

copyFile arguments are weird too

"Information","ajp-nio-8016-exec-108","10/28/19","16:08:18","MURA8DF8053F1DF5D07CA1B9BA5AD1209DA4","copyFile, {""SOURCE"":""/srv/websites/site/htdocs/sites/de/cache/file/74F695DF-A0C7-1E47-2D0ADACEF84AA305_small.jpg"",""DESTINATION"":""/srv/websites/site/htdocs/sites/de/cache/file/"",""MODE"":777}"

thanks in advance
Andreas

**Comment by aaltenbu** [comment]
I've just copied the content from this file but no cure: https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/fileWriter.cfc

**Comment by mattlevine** [comment]
Do you have a value set in your config/settings.ini.cfm fileDir attribute or a MURA_FILEDIR environment variable?  

Also, does your site have a sites directory?

-Matt

**Comment by aaltenbu** [comment]
The filedir attribute in settings.ini.cfm is not set and yes i am using a sites-directory
Andreas

**Comment by aaltenbu** [comment]
I've copied the site via site bundle and it worked that way.
Andreas
