### ISSUE TITLE
Requesting upgrade to Email address validation as its too basic

### ISSUE THREAD

**Issue by alladinUK** [blueriver/MuraCMS#3167]
Email validation seems to be very basic and it's becoming an issue for none experienced users having to add regex every time one creates an extended attributes and form field for email. Currently adding email address such as david.o'reilly@organisation.com is returned as invalid.

Would greatly appreciate if the logic for isEmail is upgraded.
https://github.com/blueriver/MuraCMS/blob/7.1.492/admin/assets/js/admin.js#L220

Thank you,
T

**Comment by alladinUK** [comment]
Thank you

**Comment by alladinUK** [comment]
Hi Matt,

I've tested this and the regex seems to accept invalid email addresses. I've looked at Coldfusion isValid email function and it seems to use the following

`"^[a-zA-Z_0-9-'\+~]+(\.[a-zA-Z_0-9-'\+~]+)*@([a-zA-Z_0-9-]+\.)+[a-zA-Z]{2,7}$"`
[Source](http://tjordahl.blogspot.com/2006/09/coldfusion-email-validation-isvalid.html)

I've tried it out and it seems the above regex is more accurate, not sure how you feel about using the above regex.

Here is a comparison between the two regex's
[Mura version](https://regex101.com/r/9AYPs4/1)
[Coldfusion version](https://regex101.com/r/YE0RHz/1)
 

Many thanks for considering this.

**Comment by alladinUK** [comment]
Just wondering if you would accept the above for the email validation logic.
Thanks you

**Comment by alladinUK** [comment]
Just wondering if you would accept the above for the email validation logic.
Thanks you

**Comment by alladinUK** [comment]
Hi Matt,

In relation to the JS change, there is also a server side email validation that's not inline with the JS logic

https://github.com/blueriver/MuraCMS/blob/7.1/core/mura/extend/extendManager.cfc#L389


I've tested this and the regex seems to accept invalid email addresses. I've looked at Coldfusion isValid email function and it seems to use the following

`"^[a-zA-Z_0-9-'\+~]+(\.[a-zA-Z_0-9-'\+~]+)*@([a-zA-Z_0-9-]+\.)+[a-zA-Z]{2,7}$"`
[Source](http://tjordahl.blogspot.com/2006/09/coldfusion-email-validation-isvalid.html)

I've tried it out and it seems the above regex is more accurate, not sure how you feel about using the above regex.

Here is a comparison between the two regex's
[Mura version](https://regex101.com/r/9AYPs4/1)
[Coldfusion version](https://regex101.com/r/YE0RHz/1)

**Comment by alladinUK** [comment]
Bumping this just in case it's been missed.
Thanks you, 
T

**Comment by alladinUK** [comment]
Hi Matt,
Thank you for updating the email validation logic.
 I've noticed the client side validation in admin.js requires updating too as its not inline with the server side validation. 

https://github.com/blueriver/MuraCMS/blob/7.1.505/admin/assets/js/admin.js#L220

Thank you
T

**Comment by mattlevine** [comment]
https://github.com/blueriver/MuraCMS/commit/2adf418e770425e3a7ac00850f339c4df4c6df1c
