### ISSUE TITLE
Inline Editing : "pencil edit icon" not available on folder type layout

### ISSUE THREAD

**Issue by rasleen-narula** [blueriver/MuraCMS#3184]
I’m testing Mura 7.1.498 and found it is not possible to edit folder layout and the Pencil edit icon is not available. There are no JS error in the browser console.

I am able to add other objects (collection,component,container, etc..) just not able to edit the main layout, I’ve tested this in one of my own themes as well as the default theme.

This only happens on Folder type content. 

I found the issue was introduced in Version 7.1.493 and works fine in 7.1.492

![Folder_page_issue](https://user-images.githubusercontent.com/57096465/81712817-fbcb3980-946c-11ea-9a10-7fa6e88b8830.png)

**Comment by mattlevine** [comment]
I just tested locally and did not have this issue?  As a test would you mind download the latest version of Mura and replacing your core and admin directories.  I'm curious it's related to and update issue?  Just taking a guess.

**Comment by alladinUK** [comment]
Hi Matt,
I just downloaded 7.1.498 and experienced the same issue. Please see attached animated gif.

I added code and admin to an existing Mura instance as well as created a brand new instance. Tested it in Chrome and Firefox. 

Not only that the pencil icon does not appear for the folder layout, but after having added an object to a page, published it, re-edited the page and deleted the object, im unable to drag anything onto the page unless I publish and re-edit again. 


![matt-pencilicon](https://user-images.githubusercontent.com/7131420/81770123-46819b80-94d7-11ea-9e4f-b88fdef24e4e.gif)

**Comment by mattlevine** [comment]
What OS do you happen to be on?  I can't seem to reproduce this.  I checked out a fresh instance and still could not reproduce it.  Definitely not saying it doesn't exist, just a bit tricky.

**Comment by alladinUK** [comment]
Please see below for OS plus other details.

![serveruinfo](https://user-images.githubusercontent.com/7131420/81801980-2a005600-950d-11ea-8ad2-2b1059717d07.png)


Just so it's clear, I downloaded a zip version of 7.1.498 and just extracted admin and core folders. I have compared the whole zip with my website and it almost identical, i think the rest of the files are created on the fly.

![zipcompare](https://user-images.githubusercontent.com/7131420/81804815-aa28ba80-9511-11ea-85d1-f947586e9a5f.png)

I also tried the option and clicked on the "Update Mura Core" button as shown in the first image above, still the same issue.

Oddly enough, once core update completed, I noticed there are differences in the code which what I wasn't expecting as 7.1 apparently should be 7.1.498 according to to what's stated in the image below, yet it seems downloading 7.1.498 zip which has updates related to s3 and doing away with cfzip among other changes is a different version to that downloaded via "Update Mura Core"

[Mura CMS 7.1.498...7.1 compare](https://github.com/blueriver/MuraCMS/compare/7.1.498...7.1)


![git71](https://user-images.githubusercontent.com/7131420/81805449-c5e09080-9512-11ea-8d3d-72ebb839fcd4.png)

**Comment by Tristanimve** [comment]
Hi,
I just have done "Update Mura Core" to 7.1.498 and have the same issue.

Core Version 7.1.498
App Server Lucee (5.2.9.31)
DB Server MySQL (5.7.30-0ubuntu0.18.04.1)
Java Version 1.8.0_181
OS Version Linux (4.15.0-65-generic)

**Comment by alladinUK** [comment]
I've also tested 7.1.498 in my dev environment and got the same issue

App Server Lucee (5.2.8.50)
DB Server Microsoft SQL Server (10.50.6560)
Java Version 1.8.0_191-1-ojdkbuild
OS Version Windows Server 2012 R2 (6.3)

@Tristanimve   Just out of interest, are you experiencing an issue with
[Inline mode full edit publish - (steps to recreate included in the comment)](https://github.com/blueriver/MuraCMS/issues/3073#issuecomment-543400964).

It's an issue I've found in 7.1.424 but Matt couldn't recreate it but i'm finding it exits in 7.1.498 too. It would be interesting to see if you're getting the same issue. Thank you.

**Comment by Tristanimve** [comment]
@alladinUK you are right ! same for me.... it's not too annoying. a reload of the page fix it but you are right and it may cause mistakes...

**Comment by mattlevine** [comment]
I was able to reproduce it.  I'll have a fix soon.

**Comment by alladinUK** [comment]
@mattlevine thank you I'll test first thing tomorrow morning.

@Tristanimve thank you for testing, just wanted to confirm it wasn't only me with this issue. @mattlevine Will there for the page refresh coming soon? 

Thank you both for your time.

**Comment by Tristanimve** [comment]
@mattlevine update to Core Version 7.1.499 and try :
pencil now shows up but when making changes in the settings  it seems that nothing is saved when publish.

**Comment by Tristanimve** [comment]
Made some test on different sites, and I was unable to change settings for Folder view. The settings panel shows up but nothing change when publish. For a new Folder, only the default view can be used.

**Comment by alladinUK** [comment]
Hi Matt,
Just wondering if there will be an update to resolve this soon?
Thank you
T

**Comment by mattlevine** [comment]
Please update and test once more.

**Comment by Tristanimve** [comment]
Update 7.1.500 done.
Looks good to me.
Thanks a lot @mattlevine

**Comment by alladinUK** [comment]
Hi,
7.1.500 fix works for me too.

Thank you

**Comment by rasleen-narula** [comment]
Thanks a lot @mattlevine 
Tested 7.1.500 and it works for me too.
