### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by marbetschar** [blueriver/MuraCMS#770]
The german translation from within mura isn't fully complete and correct (for example "Foldere" instead of "Ordner"). I can do the full german translation of anything if the mura team would like to.

Please provide me with the path of all resourceBundle files I may work through to provide mura a full german translation.

**Comment by stevewithington** [comment]
@marbetschar & @martinschaible if you would like to help with translations, please see the project on CrowdIn: https://crowdin.com/project/muracms  Thanks!
