### ISSUE TITLE
Formbuilder select display_object "dsp_common" missing

### ISSUE THREAD

**Issue by marbetschar** [blueriver/MuraCMS#771]
In the dsp_dropdown.cfm is the call of the display object "dsp_common" missing - therefore custom classes etc. are not added to any select field. As far as I've seen the following line (:53) in the dsp_dropdown.cfm:

    <select name="#arguments.field.name#"

Should be changed to the following:

    <select name="#arguments.field.name#"#variables.$.dspObject_Include(thefile='/formbuilder/fields/dsp_common.cfm',field=arguments.field,dataset=arguments.dataset)#

**Comment by stevewithington** [comment]
Closing issue, as this has been fixed.
