### ISSUE TITLE
select/ed TODAY on Content_Release_Date

### ISSUE THREAD

**Issue by reinhardjung** [blueriver/MuraCMS#789]
Why is the day of today not selected/highlighted within the calendar? :-(
Maybe there should be a button [today] - to got there - as well?

![Content_Release_Date](https://f.cloud.github.com/assets/298616/241151/5273abf8-8991-11e2-9031-022561d9ee08.png)

**Comment by stevewithington** [comment]
Today's date is now highlighted in the most recent version of Mura.

**Comment by al3x-edge** [comment]
:clap:
