### ISSUE TITLE
Text in Input Field not readable in dialogs in editor when using IE9 with v.6.0.5298

### ISSUE THREAD

**Issue by CFJEFF** [blueriver/MuraCMS#792]
When using IE 9,  if you open a dialog box in the editor that has a text input element (for example adding a URL),  the font doesn't fit in the box.  See Attached Image.  
![ie font issue](https://f.cloud.github.com/assets/812893/248862/09fe52e6-8b1d-11e2-976a-0ed77888be14.jpg)

It looks like there is some padding that might be pushing the font down so you only see about half the text.  

There doesn't seem to be anyway to over-ride the css in that box using editor.css for example in the theme.

I was able to temporarily fix the issue by adding the following to /admin/assets/css/admin.min-blessed1.css :

input.cke_dialog_ui_input_text[type="text"] {
	font: monospace;
	height: 30px;
}

**Comment by stevewithington** [comment]
This issue has been resolved for awhile now.
