### ISSUE TITLE
Restoring from Trash Bin throws an error

### ISSUE THREAD

**Issue by wiredmonkey** [blueriver/MuraCMS#799]
Hi

When I try to restore a page with a few extended attributes, I receive the following message:

Data truncation: Truncated incorrect CHAR(1000) value: 'D3AB0390-E081-49B4-EC6E3DF6B03E6737,D3AB0390-E081-49B4-EC6E3DF6B03E6737,D3AB0390-E081-49B4-EC6E3DF6B03E6737,D3AB0390-E081-49B4-E'

I'm running Mura version 6.0.5301. Could it be possible that one of the database fields size hasn't been increased with one of the updates? Below is screengrab of the error.

![Screenshot- 120 ](https://f.cloud.github.com/assets/950788/258413/03d2536a-8c97-11e2-9e7e-bc4e42dacc3c.png)

Cheers

Shaun

**Comment by stevewithington** [comment]
resolved.
