### ISSUE TITLE
Custom class extension won't allow file changes

### ISSUE THREAD

**Issue by richleach** [blueriver/MuraCMS#802]
I just created a new custom class extension (based on the File type) and called it "tbtDocument". I have about a dozen existing PDF files uploaded as type File already and now I need to change their type from "File" to "tbtDocument". When I go to edit an existing File there is no drop down menu, nor any place that allows me to change from type File to my new type of tbtDocument. However if I go to add a new file I can see my new class extension. Is this an error on my part or have I discovered a bug?

Thanks,

Rich

**Comment by stevewithington** [comment]
This has been resolved for awhile now.
