### ISSUE TITLE
CKFinder - Folder mismatch

### ISSUE THREAD

**Issue by raamexpres** [blueriver/MuraCMS#825]
I have 2 sites , each with there own image folders 

I had some issue's with CKFinder in the past and after upgraden and browser cache deleting is works. 

The problem is when I use the editor in the  Email broadcaster, and insert a picture.  CKFinder  is going to the folders of images of SiteA  ,  and it should be the image folders for siteB since the current selected site is siteB   

It works good on normale site manager pages.   it only goes wrong on the email broadcaster! 

Tested in IE9 and  Firefox 
Mura v6.0.5312

**Comment by stevewithington** [comment]
I believe this issue is resolved in the latest version.
