### ISSUE TITLE
Required folders missing when using S3

### ISSUE THREAD

**Issue by quicken** [blueriver/MuraCMS#828]
The amazon S3 module does not create some required folders. When creating a new site mura will create several folders within the S3 bucket. Uploading images works however the thumbnail previews are all broken.

After some searching we found that mura does not create the required Thumbs folder and it's subdirectories within the S3 bucket. We currently have to manually create these missing folders after that the uploaded thumbnails are shown correctly.

**Comment by stevewithington** [comment]
Closing this issue as we've changed this feature, and are now pointing people to our documentation on "How To Use Amazon S3 For File Storage" located at http://docs.getmura.com/v6/installation-setup/how-to-use-amazon-s3-for-file-storage/.
