### ISSUE TITLE
Adding Gallery Content Object to content region results in calendar being displayed

### ISSUE THREAD

**Issue by matthewfair** [blueriver/MuraCMS#830]
Version 5317. 
Using the Layout & Objects section of a page I tried to add a gallery.  When I selected the correct gallery and gallery sub object, after publishing... a calendar is displayed on the page instead of the correct gallery object.

**Comment by stevewithington** [comment]
I know this is an old ticket, but there may have been some confusion on how the "Gallery" display objects actually work. I suspect you selected Galleries > Your Gallery Name > Your Gallery Name - Calendar Navigation, which would indeed display a calendar. The calendar is simply a navigational tool for end users to select content items published during the timeframe displayed.
