### ISSUE TITLE
Upgrading from Sava 5 to Mura 6

### ISSUE THREAD

**Issue by gpbonifazi** [blueriver/MuraCMS#846]
I do not know if this is the right place to raise an issue but upgrading a site from Sava 5 to Mura 6 following these instructions:

http://docs.getmura.com/index.cfm/installation-set-up/upgrading-mura/upgrading-mura-manually/

I had lots of issues. to make it working I had to add in the  /config/applicationSettings.cfm:

cfset this.mappings["/mura"] = variables.mapPrefix & variables.baseDir & "/requirements/mura"
cfset this.mappings["/coldspring"] = variables.mapPrefix & variables.baseDir & "/requirements/coldspring"

Regards

Giampiero

**Comment by stevewithington** [comment]
Closing as no longer an issue.
